// M2-C2A -- Golden Unit M2 / Geometría, Recurso 1 (order 1 en U3). Contenido
// editorial APROBADO externamente, transcrito verbatim. Ajustes solo
// técnicos: contentBlocks (heading/paragraph/formula), LaTeX en `latex`,
// questionKey sin padding.
//
// Answer key: R5 -- C C C C B C A A B B  ("CCCCBCAABB").
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const homoteciaRelacionesGeometricas: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS',
  unitCode: 'M2.GEOMETRIA',
  subjectKey: 'matematica',
  order: 1,
  title: 'Homotecia y relaciones geométricas',
  learningObjective:
    'Comprender y aplicar la homotecia para analizar ampliaciones y reducciones de figuras planas, determinar longitudes y coordenadas, interpretar el efecto de la razón de homotecia y resolver problemas de semejanza y escalamiento geométrico.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Homotecia y relaciones geométricas' },

    { type: 'heading', order: 1, level: 2, text: '1. ¿Qué es una homotecia?' },
    {
      type: 'paragraph',
      order: 2,
      text: 'Una homotecia es una transformación geométrica que cambia el tamaño de una figura manteniendo su forma. Se define mediante: un centro de homotecia; una razón de homotecia k. Si un punto P se transforma en P\u2032, ambos puntos quedan alineados con el centro de homotecia O. Las distancias al centro cumplen:',
    },
    { type: 'formula', order: 3, latex: 'OP\u2032=|k|\\cdot OP' },
    { type: 'paragraph', order: 4, text: 'El valor de k determina cuánto cambia el tamaño y en qué dirección aparece la imagen.' },

    { type: 'heading', order: 5, level: 2, text: '2. Razón de homotecia positiva' },
    { type: 'paragraph', order: 6, text: 'Cuando:' },
    { type: 'formula', order: 7, latex: 'k>0' },
    { type: 'paragraph', order: 8, text: 'el punto original y su imagen se encuentran en la misma dirección desde el centro de homotecia. Por ejemplo, si:' },
    { type: 'formula', order: 9, latex: 'k=2' },
    { type: 'paragraph', order: 10, text: 'la imagen queda al doble de distancia del centro. Si:' },
    { type: 'formula', order: 11, latex: 'k=\\frac12' },
    {
      type: 'paragraph',
      order: 12,
      text: 'la imagen queda a la mitad de la distancia. En ambos casos, el punto y su imagen están sobre la misma semirrecta que parte desde el centro.',
    },

    { type: 'heading', order: 13, level: 2, text: '3. Razón de homotecia negativa' },
    { type: 'paragraph', order: 14, text: 'Cuando:' },
    { type: 'formula', order: 15, latex: 'k<0' },
    { type: 'paragraph', order: 16, text: 'la imagen se encuentra al lado opuesto del centro respecto del punto original. Por ejemplo, si:' },
    { type: 'formula', order: 17, latex: 'k=-2' },
    { type: 'paragraph', order: 18, text: 'la distancia al centro se duplica, pero la imagen aparece en la dirección contraria. El signo determina la orientación relativa respecto del centro, mientras que:' },
    { type: 'formula', order: 19, latex: '|k|' },
    { type: 'paragraph', order: 20, text: 'determina el factor de escala.' },

    { type: 'heading', order: 21, level: 2, text: '4. Ampliaciones y reducciones' },
    { type: 'paragraph', order: 22, text: 'Si:' },
    { type: 'formula', order: 23, latex: '|k|>1' },
    { type: 'paragraph', order: 24, text: 'la homotecia produce una ampliación. Si:' },
    { type: 'formula', order: 25, latex: '0<|k|<1' },
    { type: 'paragraph', order: 26, text: 'produce una reducción. Si:' },
    { type: 'formula', order: 27, latex: '|k|=1' },
    { type: 'paragraph', order: 28, text: 'las longitudes se conservan. Por ejemplo:' },
    { type: 'formula', order: 29, latex: 'k=3' },
    { type: 'paragraph', order: 30, text: 'triplica todas las longitudes. En cambio:' },
    { type: 'formula', order: 31, latex: 'k=\\frac14' },
    { type: 'paragraph', order: 32, text: 'las reduce a la cuarta parte.' },

    { type: 'heading', order: 33, level: 2, text: '5. Longitudes en figuras homotéticas' },
    { type: 'paragraph', order: 34, text: 'Las longitudes correspondientes se multiplican por:' },
    { type: 'formula', order: 35, latex: '|k|' },
    { type: 'paragraph', order: 36, text: 'Si un segmento mide 6 cm y se aplica una homotecia de razón:' },
    { type: 'formula', order: 37, latex: 'k=-3' },
    { type: 'paragraph', order: 38, text: 'la longitud de su imagen será:' },
    { type: 'formula', order: 39, latex: '|-3|\\cdot6=18\\text{ cm}' },
    { type: 'paragraph', order: 40, text: 'El signo de k no hace negativa una longitud.' },

    { type: 'heading', order: 41, level: 2, text: '6. Perímetros bajo una homotecia' },
    { type: 'paragraph', order: 42, text: 'Como todos los lados se multiplican por el mismo factor:' },
    { type: 'formula', order: 43, latex: '|k|' },
    { type: 'paragraph', order: 44, text: 'el perímetro también se multiplica por:' },
    { type: 'formula', order: 45, latex: '|k|' },
    { type: 'paragraph', order: 46, text: 'Si una figura tiene perímetro P, entonces su imagen tendrá:' },
    { type: 'formula', order: 47, latex: 'P\u2032=|k|P' },
    { type: 'paragraph', order: 48, text: 'Por ejemplo, si k=1,5, el nuevo perímetro es 1,5 veces el original.' },

    { type: 'heading', order: 49, level: 2, text: '7. Áreas bajo una homotecia' },
    { type: 'paragraph', order: 50, text: 'Las áreas no se multiplican por |k|, sino por:' },
    { type: 'formula', order: 51, latex: 'k^2' },
    { type: 'paragraph', order: 52, text: 'Si una figura tiene área A, entonces:' },
    { type: 'formula', order: 53, latex: 'A\u2032=k^2A' },
    { type: 'paragraph', order: 54, text: 'Por ejemplo, una homotecia de razón:' },
    { type: 'formula', order: 55, latex: 'k=3' },
    { type: 'paragraph', order: 56, text: 'multiplica cada longitud por 3, pero el área por:' },
    { type: 'formula', order: 57, latex: '3^2=9' },
    { type: 'paragraph', order: 58, text: 'Esta diferencia es fundamental al resolver problemas de escalamiento.' },

    { type: 'heading', order: 59, level: 2, text: '8. Homotecia en el plano cartesiano' },
    { type: 'paragraph', order: 60, text: 'Si el centro de homotecia es el origen:' },
    { type: 'formula', order: 61, latex: 'O=(0,0)' },
    { type: 'paragraph', order: 62, text: 'y un punto tiene coordenadas:' },
    { type: 'formula', order: 63, latex: 'P=(x,y)' },
    { type: 'paragraph', order: 64, text: 'su imagen mediante una razón k es:' },
    { type: 'formula', order: 65, latex: 'P\u2032=(kx,ky)' },
    { type: 'paragraph', order: 66, text: 'Por ejemplo, si:' },
    { type: 'formula', order: 67, latex: 'P=(3,-2)' },
    { type: 'paragraph', order: 68, text: 'y:' },
    { type: 'formula', order: 69, latex: 'k=2' },
    { type: 'paragraph', order: 70, text: 'entonces:' },
    { type: 'formula', order: 71, latex: 'P\u2032=(6,-4)' },

    { type: 'heading', order: 72, level: 2, text: '9. Homotecia con centro distinto del origen' },
    { type: 'paragraph', order: 73, text: 'Si el centro es:' },
    { type: 'formula', order: 74, latex: 'O=(a,b)' },
    { type: 'paragraph', order: 75, text: 'puede analizarse el vector desde O hacia P. Si:' },
    { type: 'formula', order: 76, latex: '\\overrightarrow{OP}=(x-a,\\;y-b)' },
    { type: 'paragraph', order: 77, text: 'entonces:' },
    { type: 'formula', order: 78, latex: '\\overrightarrow{OP\u2032}=k\\overrightarrow{OP}' },
    { type: 'paragraph', order: 79, text: 'y:' },
    { type: 'formula', order: 80, latex: 'P\u2032=O+k(P-O)' },
    { type: 'paragraph', order: 81, text: 'Esto permite determinar coordenadas incluso cuando el centro no coincide con el origen.' },

    { type: 'heading', order: 82, level: 2, text: '10. Homotecia y semejanza' },
    {
      type: 'paragraph',
      order: 83,
      text: 'Las figuras relacionadas mediante homotecia son semejantes. Esto significa que: sus ángulos correspondientes tienen igual medida; sus lados correspondientes son proporcionales; conservan la forma; pueden tener distinto tamaño. Por eso, una homotecia permite resolver problemas relacionados con: escalas; mapas; planos; maquetas; ampliaciones; reducciones; comparación de figuras semejantes.',
    },

    { type: 'heading', order: 84, level: 3, text: 'Situación ZETRYND 1 — Ampliación de un plano' },
    { type: 'paragraph', order: 85, text: 'Un plano rectangular tiene dimensiones:' },
    { type: 'formula', order: 86, latex: '8\\text{ cm}\\times5\\text{ cm}' },
    { type: 'paragraph', order: 87, text: 'y se amplía mediante una homotecia de razón:' },
    { type: 'formula', order: 88, latex: 'k=2,5' },
    { type: 'paragraph', order: 89, text: 'Las nuevas dimensiones son:' },
    { type: 'formula', order: 90, latex: '8\\cdot2,5=20\\text{ cm}' },
    { type: 'paragraph', order: 91, text: 'y:' },
    { type: 'formula', order: 92, latex: '5\\cdot2,5=12,5\\text{ cm}' },
    { type: 'paragraph', order: 93, text: 'El área original era:' },
    { type: 'formula', order: 94, latex: '8\\cdot5=40\\text{ cm}^2' },
    { type: 'paragraph', order: 95, text: 'La nueva área puede obtenerse directamente utilizando:' },
    { type: 'formula', order: 96, latex: 'A\u2032=k^2A' },
    { type: 'paragraph', order: 97, text: 'Entonces:' },
    { type: 'formula', order: 98, latex: 'A\u2032=(2,5)^2\\cdot40' },
    { type: 'formula', order: 99, latex: '=6,25\\cdot40' },
    { type: 'formula', order: 100, latex: '=250\\text{ cm}^2' },

    { type: 'heading', order: 101, level: 3, text: 'Situación ZETRYND 2 — Transformación en coordenadas' },
    { type: 'paragraph', order: 102, text: 'Se considera un punto:' },
    { type: 'formula', order: 103, latex: 'P=(5,3)' },
    { type: 'paragraph', order: 104, text: 'y un centro de homotecia:' },
    { type: 'formula', order: 105, latex: 'O=(1,1)' },
    { type: 'paragraph', order: 106, text: 'Se aplica una homotecia de razón:' },
    { type: 'formula', order: 107, latex: 'k=2' },
    { type: 'paragraph', order: 108, text: 'El vector desde el centro hasta el punto es:' },
    { type: 'formula', order: 109, latex: '\\overrightarrow{OP}=(4,2)' },
    { type: 'paragraph', order: 110, text: 'Multiplicando por 2:' },
    { type: 'formula', order: 111, latex: '\\overrightarrow{OP\u2032}=(8,4)' },
    { type: 'paragraph', order: 112, text: 'Sumando nuevamente las coordenadas del centro:' },
    { type: 'formula', order: 113, latex: 'P\u2032=(1+8,\\;1+4)' },
    { type: 'formula', order: 114, latex: 'P\u2032=(9,5)' },
  ],
  questions: [
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un segmento mide 7 cm. Se aplica una homotecia de razón:' },
        { type: 'formula', order: 1, latex: 'k=3' },
        { type: 'paragraph', order: 2, text: '¿Cuánto mide su imagen?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '10 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '14 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '21 cm' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '28 cm' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Las longitudes se multiplican por:' },
        { type: 'formula', order: 1, latex: '|k|' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '7\\cdot3=21' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál de los siguientes valores de k representa una reducción?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'k=2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'k=-3' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'k=\\frac12' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'k=4' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Una reducción ocurre cuando:' },
        { type: 'formula', order: 1, latex: '0<|k|<1' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\left|\\frac12\\right|<1' },
        { type: 'paragraph', order: 4, text: 'se trata de una reducción.' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un triángulo tiene perímetro:' },
        { type: 'formula', order: 1, latex: '24\\text{ cm}' },
        { type: 'paragraph', order: 2, text: 'Se aplica una homotecia de razón:' },
        { type: 'formula', order: 3, latex: 'k=-2' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el perímetro de la imagen?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '12 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '24 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '48 cm' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '96 cm' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'El perímetro se multiplica por:' },
        { type: 'formula', order: 1, latex: '|k|=2' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '24\\cdot2=48' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una figura tiene un área de:' },
        { type: 'formula', order: 1, latex: '18\\text{ cm}^2' },
        { type: 'paragraph', order: 2, text: 'Se aplica una homotecia de razón:' },
        { type: 'formula', order: 3, latex: 'k=3' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el área de la imagen?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '54\\text{ cm}^2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '108\\text{ cm}^2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '162\\text{ cm}^2' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '486\\text{ cm}^2' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Las áreas se multiplican por:' },
        { type: 'formula', order: 1, latex: 'k^2' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto:' },
        { type: 'formula', order: 3, latex: '18\\cdot3^2' },
        { type: 'formula', order: 4, latex: '=18\\cdot9' },
        { type: 'formula', order: 5, latex: '=162' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'El punto:' },
        { type: 'formula', order: 1, latex: 'P=(4,-3)' },
        { type: 'paragraph', order: 2, text: 'se transforma mediante una homotecia con centro en el origen y razón:' },
        { type: 'formula', order: 3, latex: 'k=-2' },
        { type: 'paragraph', order: 4, text: '¿Cuáles son las coordenadas de P\u2032?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '(8,-6)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(-8,6)' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '(-2,1,5)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(2,-1,5)' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Como el centro es el origen:' },
        { type: 'formula', order: 1, latex: 'P\u2032=(kx,ky)' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: 'P\u2032=(-2\\cdot4,\\;-2\\cdot(-3))' },
        { type: 'formula', order: 4, latex: '=(-8,6)' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Dos figuras homotéticas tienen lados correspondientes de 6 cm y 15 cm. ¿Cuál es el valor de |k| si la segunda figura es la imagen de la primera?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '1,5' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '2' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '2,5' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La razón de las longitudes correspondientes es:' },
        { type: 'formula', order: 1, latex: '|k|=\\frac{15}{6}' },
        { type: 'formula', order: 2, latex: '=2,5' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una figura tiene área:' },
        { type: 'formula', order: 1, latex: '48\\text{ cm}^2' },
        { type: 'paragraph', order: 2, text: 'Después de una homotecia, su imagen tiene área:' },
        { type: 'formula', order: 3, latex: '108\\text{ cm}^2' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el valor de |k|?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac32' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac94' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac52' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Las áreas cumplen:' },
        { type: 'formula', order: 1, latex: '108=k^2\\cdot48' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: 'k^2=\\frac{108}{48}' },
        { type: 'formula', order: 4, latex: 'k^2=\\frac94' },
        { type: 'paragraph', order: 5, text: 'Por lo tanto:' },
        { type: 'formula', order: 6, latex: '|k|=\\frac32' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se considera una homotecia de centro:' },
        { type: 'formula', order: 1, latex: 'O=(2,-1)' },
        { type: 'paragraph', order: 2, text: 'El punto:' },
        { type: 'formula', order: 3, latex: 'P=(5,3)' },
        { type: 'paragraph', order: 4, text: 'se transforma con razón:' },
        { type: 'formula', order: 5, latex: 'k=-2' },
        { type: 'paragraph', order: 6, text: '¿Cuáles son las coordenadas de P\u2032?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '(-4,-9)' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '(-4,-5)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(8,7)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(-6,-7)' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Primero:' },
        { type: 'formula', order: 1, latex: 'P-O=(5-2,\\;3-(-1))' },
        { type: 'formula', order: 2, latex: '=(3,4)' },
        { type: 'paragraph', order: 3, text: 'Multiplicando por k=-2:' },
        { type: 'formula', order: 4, latex: '-2(3,4)=(-6,-8)' },
        { type: 'paragraph', order: 5, text: 'Sumando el centro:' },
        { type: 'formula', order: 6, latex: 'P\u2032=(2,-1)+(-6,-8)' },
        { type: 'formula', order: 7, latex: '=(-4,-9)' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Dos polígonos semejantes están relacionados mediante una homotecia. El perímetro de la figura original es:' },
        { type: 'formula', order: 1, latex: '30\\text{ cm}' },
        { type: 'paragraph', order: 2, text: 'y el área de su imagen es cuatro veces el área original. ¿Cuál es el perímetro de la imagen?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '15 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '60 cm' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '90 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '120 cm' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Si el área se multiplica por 4:' },
        { type: 'formula', order: 1, latex: 'k^2=4' },
        { type: 'paragraph', order: 2, text: 'por lo que:' },
        { type: 'formula', order: 3, latex: '|k|=2' },
        { type: 'paragraph', order: 4, text: 'El perímetro se multiplica por |k|:' },
        { type: 'formula', order: 5, latex: '30\\cdot2=60' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.HOMOTECIA_RELACIONES_GEOMETRICAS.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un triángulo ABC se transforma mediante una homotecia de centro O y razón k. Se sabe que el área del triángulo imagen es:' },
        { type: 'formula', order: 1, latex: '25' },
        { type: 'paragraph', order: 2, text: 'veces el área del triángulo original y que A y A\u2032 se encuentran en lados opuestos del centro O. ¿Cuál es la razón de homotecia?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'k=5' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'k=-5' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'k=25' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'k=-25' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Como las áreas se relacionan mediante:' },
        { type: 'formula', order: 1, latex: 'k^2=25' },
        { type: 'paragraph', order: 2, text: 'se obtiene:' },
        { type: 'formula', order: 3, latex: '|k|=5' },
        { type: 'paragraph', order: 4, text: 'Además, A y A\u2032 están en lados opuestos del centro, lo que indica que:' },
        { type: 'formula', order: 5, latex: 'k<0' },
        { type: 'paragraph', order: 6, text: 'Por lo tanto:' },
        { type: 'formula', order: 7, latex: 'k=-5' },
      ],
    },
  ],
};

export default homoteciaRelacionesGeometricas;
