// M2-C2A -- Golden Unit M2 / Geometría, Recurso 2 (order 2 en U3). Contenido
// editorial APROBADO externamente, transcrito verbatim. Ajustes solo
// técnicos: contentBlocks (heading/paragraph/formula), LaTeX en `latex`,
// questionKey sin padding.
//
// Answer key: R6 -- A B C B B C B C B B  ("ABCBBCBCBB").
// (Clave DEFINITIVA tras revisión editorial; una línea compacta defectuosa
// de un borrador previo fue descartada.)
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const trigonometriaTriangulosRectangulos: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS',
  unitCode: 'M2.GEOMETRIA',
  subjectKey: 'matematica',
  order: 2,
  title: 'Trigonometría en triángulos rectángulos',
  learningObjective:
    'Aplicar las razones trigonométricas seno, coseno y tangente en triángulos rectángulos para determinar longitudes y ángulos, interpretar relaciones geométricas y resolver problemas contextualizados de alturas, distancias e inclinaciones.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Trigonometría en triángulos rectángulos' },

    { type: 'heading', order: 1, level: 2, text: '1. Triángulos rectángulos' },
    { type: 'paragraph', order: 2, text: 'Un triángulo rectángulo tiene un ángulo de:' },
    { type: 'formula', order: 3, latex: '90^\\circ' },
    {
      type: 'paragraph',
      order: 4,
      text: 'El lado opuesto al ángulo recto se denomina hipotenusa. Los otros dos lados se denominan catetos. Respecto de un ángulo agudo \\theta, los catetos pueden distinguirse como: cateto opuesto a \\theta; cateto adyacente a \\theta. Esta identificación depende del ángulo que se esté considerando.',
    },

    { type: 'heading', order: 5, level: 2, text: '2. Razón seno' },
    { type: 'paragraph', order: 6, text: 'En un triángulo rectángulo:' },
    { type: 'formula', order: 7, latex: '\\sin(\\theta)=\\frac{\\text{cateto opuesto}}{\\text{hipotenusa}}' },
    { type: 'paragraph', order: 8, text: 'Por ejemplo, si respecto de un ángulo \\theta el cateto opuesto mide 6 y la hipotenusa mide 10:' },
    { type: 'formula', order: 9, latex: '\\sin(\\theta)=\\frac{6}{10}' },
    { type: 'formula', order: 10, latex: '=\\frac35' },
    { type: 'paragraph', order: 11, text: 'El seno relaciona el cateto opuesto con la hipotenusa.' },

    { type: 'heading', order: 12, level: 2, text: '3. Razón coseno' },
    { type: 'paragraph', order: 13, text: 'El coseno se define mediante:' },
    { type: 'formula', order: 14, latex: '\\cos(\\theta)=\\frac{\\text{cateto adyacente}}{\\text{hipotenusa}}' },
    { type: 'paragraph', order: 15, text: 'Si el cateto adyacente mide 8 y la hipotenusa mide 10:' },
    { type: 'formula', order: 16, latex: '\\cos(\\theta)=\\frac{8}{10}' },
    { type: 'formula', order: 17, latex: '=\\frac45' },
    { type: 'paragraph', order: 18, text: 'El coseno resulta útil cuando aparecen el cateto adyacente y la hipotenusa.' },

    { type: 'heading', order: 19, level: 2, text: '4. Razón tangente' },
    { type: 'paragraph', order: 20, text: 'La tangente relaciona los dos catetos:' },
    { type: 'formula', order: 21, latex: '\\tan(\\theta)=\\frac{\\text{cateto opuesto}}{\\text{cateto adyacente}}' },
    { type: 'paragraph', order: 22, text: 'Por ejemplo, si el cateto opuesto mide 6 y el adyacente mide 8:' },
    { type: 'formula', order: 23, latex: '\\tan(\\theta)=\\frac68' },
    { type: 'formula', order: 24, latex: '=\\frac34' },
    { type: 'paragraph', order: 25, text: 'La tangente permite trabajar sin conocer directamente la hipotenusa.' },

    { type: 'heading', order: 26, level: 2, text: '5. Elegir la razón adecuada' },
    {
      type: 'paragraph',
      order: 27,
      text: 'La razón trigonométrica debe elegirse según los lados conocidos y el lado que se desea determinar. Por ejemplo, si conocemos: el ángulo; la hipotenusa; y queremos encontrar el cateto opuesto, conviene usar:',
    },
    { type: 'formula', order: 28, latex: '\\sin(\\theta)' },
    { type: 'paragraph', order: 29, text: 'Si conocemos: el ángulo; el cateto adyacente; y queremos encontrar el cateto opuesto, conviene usar:' },
    { type: 'formula', order: 30, latex: '\\tan(\\theta)' },
    { type: 'paragraph', order: 31, text: 'Identificar primero los lados evita aplicar una razón incorrecta.' },

    { type: 'heading', order: 32, level: 2, text: '6. Determinar una longitud' },
    { type: 'paragraph', order: 33, text: 'Supongamos que:' },
    { type: 'formula', order: 34, latex: '\\sin(30^\\circ)=\\frac12' },
    { type: 'paragraph', order: 35, text: 'y un triángulo tiene hipotenusa de 12 cm. Si x es el cateto opuesto:' },
    { type: 'formula', order: 36, latex: '\\sin(30^\\circ)=\\frac{x}{12}' },
    { type: 'paragraph', order: 37, text: 'Entonces:' },
    { type: 'formula', order: 38, latex: '\\frac12=\\frac{x}{12}' },
    { type: 'paragraph', order: 39, text: 'y:' },
    { type: 'formula', order: 40, latex: 'x=6' },
    { type: 'paragraph', order: 41, text: 'La trigonometría permite determinar longitudes a partir de ángulos y otras medidas.' },

    { type: 'heading', order: 42, level: 2, text: '7. Determinar un ángulo' },
    { type: 'paragraph', order: 43, text: 'Si se conocen dos lados de un triángulo rectángulo, también puede determinarse un ángulo. Por ejemplo, si:' },
    { type: 'formula', order: 44, latex: '\\tan(\\theta)=\\frac34' },
    { type: 'paragraph', order: 45, text: 'entonces:' },
    { type: 'formula', order: 46, latex: '\\theta=\\tan^{-1}\\left(\\frac34\\right)' },
    { type: 'paragraph', order: 47, text: 'La expresión:' },
    { type: 'formula', order: 48, latex: '\\tan^{-1}' },
    { type: 'paragraph', order: 49, text: 'representa la función inversa de la tangente. De manera análoga pueden utilizarse:' },
    { type: 'formula', order: 50, latex: '\\sin^{-1}' },
    { type: 'paragraph', order: 51, text: 'y:' },
    { type: 'formula', order: 52, latex: '\\cos^{-1}' },
    { type: 'paragraph', order: 53, text: 'cuando corresponda.' },

    { type: 'heading', order: 54, level: 2, text: '8. Relaciones entre razones trigonométricas' },
    { type: 'paragraph', order: 55, text: 'En un triángulo rectángulo con catetos a y b, e hipotenusa c, respecto de cierto ángulo \\theta:' },
    { type: 'formula', order: 56, latex: '\\sin(\\theta)=\\frac{a}{c}' },
    { type: 'formula', order: 57, latex: '\\cos(\\theta)=\\frac{b}{c}' },
    { type: 'paragraph', order: 58, text: 'Por el teorema de Pitágoras:' },
    { type: 'formula', order: 59, latex: 'a^2+b^2=c^2' },
    { type: 'paragraph', order: 60, text: 'Entonces:' },
    { type: 'formula', order: 61, latex: '\\sin^2(\\theta)+\\cos^2(\\theta)=1' },
    { type: 'paragraph', order: 62, text: 'Esta relación conecta las razones trigonométricas con la geometría del triángulo rectángulo.' },

    { type: 'heading', order: 63, level: 2, text: '9. Ángulos de elevación y depresión' },
    {
      type: 'paragraph',
      order: 64,
      text: 'Un ángulo de elevación se forma cuando se observa un objeto situado por encima de una línea horizontal. Por ejemplo, al mirar la parte superior de un edificio desde el suelo. Un ángulo de depresión se forma cuando se observa un objeto situado por debajo de una línea horizontal. Estas situaciones pueden representarse mediante triángulos rectángulos y resolverse usando razones trigonométricas.',
    },

    { type: 'heading', order: 65, level: 2, text: '10. Modelar antes de calcular' },
    {
      type: 'paragraph',
      order: 66,
      text: 'En problemas geométricos conviene seguir este proceso: 1. identificar el triángulo rectángulo; 2. marcar el ángulo conocido; 3. identificar cateto opuesto, adyacente e hipotenusa; 4. elegir la razón trigonométrica adecuada; 5. plantear la ecuación; 6. resolver; 7. interpretar el resultado en su contexto. La parte más importante no siempre es el cálculo, sino construir correctamente el modelo geométrico.',
    },

    { type: 'heading', order: 67, level: 3, text: 'Situación ZETRYND 1 — Altura de una estructura' },
    { type: 'paragraph', order: 68, text: 'Desde un punto situado a 20 m de la base de una estructura se observa su parte superior con un ángulo de elevación de:' },
    { type: 'formula', order: 69, latex: '45^\\circ' },
    { type: 'paragraph', order: 70, text: 'Si h representa la altura de la estructura:' },
    { type: 'formula', order: 71, latex: '\\tan(45^\\circ)=\\frac{h}{20}' },
    { type: 'paragraph', order: 72, text: 'Como:' },
    { type: 'formula', order: 73, latex: '\\tan(45^\\circ)=1' },
    { type: 'paragraph', order: 74, text: 'se obtiene:' },
    { type: 'formula', order: 75, latex: '1=\\frac{h}{20}' },
    { type: 'paragraph', order: 76, text: 'Por lo tanto:' },
    { type: 'formula', order: 77, latex: 'h=20\\text{ m}' },

    { type: 'heading', order: 78, level: 3, text: 'Situación ZETRYND 2 — Cable de soporte' },
    { type: 'paragraph', order: 79, text: 'Un cable de 10 m une la parte superior de un poste con un punto del suelo. El cable forma un ángulo de:' },
    { type: 'formula', order: 80, latex: '60^\\circ' },
    { type: 'paragraph', order: 81, text: 'con el suelo. Si h representa la altura del punto donde se fija el cable:' },
    { type: 'formula', order: 82, latex: '\\sin(60^\\circ)=\\frac{h}{10}' },
    { type: 'paragraph', order: 83, text: 'Por lo tanto:' },
    { type: 'formula', order: 84, latex: 'h=10\\sin(60^\\circ)' },
    { type: 'paragraph', order: 85, text: 'Como:' },
    { type: 'formula', order: 86, latex: '\\sin(60^\\circ)=\\frac{\\sqrt3}{2}' },
    { type: 'paragraph', order: 87, text: 'se obtiene:' },
    { type: 'formula', order: 88, latex: 'h=5\\sqrt3\\text{ m}' },
  ],
  questions: [
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo, respecto de un ángulo \\theta, el cateto opuesto mide 6 cm y la hipotenusa mide 10 cm. ¿Cuál es el valor de:' },
        { type: 'formula', order: 1, latex: '\\sin(\\theta)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac35' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac45' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac53' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac34' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Por definición:' },
        { type: 'formula', order: 1, latex: '\\sin(\\theta)=\\frac{\\text{cateto opuesto}}{\\text{hipotenusa}}' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '\\sin(\\theta)=\\frac6{10}=\\frac35' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo, respecto de un ángulo \\theta, el cateto opuesto mide 8 y el cateto adyacente mide 4. ¿Cuál es el valor de:' },
        { type: 'formula', order: 1, latex: '\\tan(\\theta)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac12' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '2' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La tangente se define como:' },
        { type: 'formula', order: 1, latex: '\\tan(\\theta)=\\frac{\\text{cateto opuesto}}{\\text{cateto adyacente}}' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto:' },
        { type: 'formula', order: 3, latex: '\\tan(\\theta)=\\frac84=2' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo:' },
        { type: 'formula', order: 1, latex: '\\cos(\\theta)=\\frac45' },
        { type: 'paragraph', order: 2, text: 'y la hipotenusa mide 15 cm. ¿Cuánto mide el cateto adyacente a \\theta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '9 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '10 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '12 cm' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '20 cm' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se tiene:' },
        { type: 'formula', order: 1, latex: '\\frac45=\\frac{x}{15}' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: 'x=15\\cdot\\frac45' },
        { type: 'formula', order: 4, latex: 'x=12' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un poste proyecta una sombra de 10 m. El ángulo de elevación del Sol respecto del extremo de la sombra es de:' },
        { type: 'formula', order: 1, latex: '45^\\circ' },
        { type: 'paragraph', order: 2, text: '¿Cuál es la altura del poste?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '5 m' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '10 m' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '10\\sqrt2 \\text{ m}' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '20 m' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La altura es el cateto opuesto y la sombra es el cateto adyacente:' },
        { type: 'formula', order: 1, latex: '\\tan(45^\\circ)=\\frac{h}{10}' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\tan(45^\\circ)=1' },
        { type: 'paragraph', order: 4, text: 'se obtiene:' },
        { type: 'formula', order: 5, latex: 'h=10' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo, la hipotenusa mide 12 cm y uno de sus ángulos agudos mide:' },
        { type: 'formula', order: 1, latex: '30^\\circ' },
        { type: 'paragraph', order: 2, text: '¿Cuánto mide el cateto opuesto a ese ángulo?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '4 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '6 cm' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '6\\sqrt3 \\text{ cm}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '12\\sqrt3 \\text{ cm}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se utiliza:' },
        { type: 'formula', order: 1, latex: '\\sin(30^\\circ)=\\frac{x}{12}' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\sin(30^\\circ)=\\frac12' },
        { type: 'paragraph', order: 4, text: 'entonces:' },
        { type: 'formula', order: 5, latex: 'x=6' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo se cumple:' },
        { type: 'formula', order: 1, latex: '\\sin(\\theta)=\\frac5{13}' },
        { type: 'paragraph', order: 2, text: 'Si el cateto opuesto mide 10 cm, ¿cuánto mide la hipotenusa?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '13 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '20 cm' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '26 cm' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '30 cm' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se plantea:' },
        { type: 'formula', order: 1, latex: '\\frac5{13}=\\frac{10}{h}' },
        { type: 'paragraph', order: 2, text: 'Multiplicando:' },
        { type: 'formula', order: 3, latex: '5h=130' },
        { type: 'paragraph', order: 4, text: 'Por lo tanto:' },
        { type: 'formula', order: 5, latex: 'h=26' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un triángulo rectángulo tiene catetos de 9 cm y 12 cm. Sea \\theta el ángulo opuesto al cateto de 9 cm. ¿Cuál es el valor de:' },
        { type: 'formula', order: 1, latex: '\\cos(\\theta)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac35' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac45' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac34' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac43' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Primero calculamos la hipotenusa:' },
        { type: 'formula', order: 1, latex: 'c=\\sqrt{9^2+12^2}' },
        { type: 'formula', order: 2, latex: 'c=\\sqrt{81+144}' },
        { type: 'formula', order: 3, latex: 'c=15' },
        { type: 'paragraph', order: 4, text: 'Respecto de \\theta, el cateto adyacente mide 12. Entonces:' },
        { type: 'formula', order: 5, latex: '\\cos(\\theta)=\\frac{12}{15}=\\frac45' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Desde un punto del suelo se observa la parte superior de una torre con un ángulo de elevación de:' },
        { type: 'formula', order: 1, latex: '30^\\circ' },
        { type: 'paragraph', order: 2, text: 'La distancia horizontal entre el observador y la base de la torre es:' },
        { type: 'formula', order: 3, latex: '18\\sqrt3\\text{ m}' },
        { type: 'paragraph', order: 4, text: '¿Cuál es la altura de la torre?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '6 m' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9 m' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '18 m' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '36 m' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se utiliza:' },
        { type: 'formula', order: 1, latex: '\\tan(30^\\circ)=\\frac{h}{18\\sqrt3}' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\tan(30^\\circ)=\\frac1{\\sqrt3}' },
        { type: 'paragraph', order: 4, text: 'entonces:' },
        { type: 'formula', order: 5, latex: '\\frac1{\\sqrt3}=\\frac{h}{18\\sqrt3}' },
        { type: 'paragraph', order: 6, text: 'Por lo tanto:' },
        { type: 'formula', order: 7, latex: 'h=18' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un triángulo rectángulo se cumple:' },
        { type: 'formula', order: 1, latex: '\\sin(\\theta)=\\frac{12}{13}' },
        { type: 'paragraph', order: 2, text: 'donde \\theta es agudo. ¿Cuál es el valor de:' },
        { type: 'formula', order: 3, latex: '\\tan(\\theta)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac5{12}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac{12}{5}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac{12}{13}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac{13}{5}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Si:' },
        { type: 'formula', order: 1, latex: '\\sin(\\theta)=\\frac{12}{13}' },
        { type: 'paragraph', order: 2, text: 'podemos considerar: cateto opuesto = 12; hipotenusa = 13. Por Pitágoras, el cateto adyacente es:' },
        { type: 'formula', order: 3, latex: '\\sqrt{13^2-12^2}' },
        { type: 'formula', order: 4, latex: '=\\sqrt{169-144}' },
        { type: 'formula', order: 5, latex: '=5' },
        { type: 'paragraph', order: 6, text: 'Entonces:' },
        { type: 'formula', order: 7, latex: '\\tan(\\theta)=\\frac{12}{5}' },
      ],
    },
    {
      questionKey: 'M2.GEOMETRIA.TRIGONOMETRIA_TRIANGULOS_RECTANGULOS.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Desde un punto A se observa la parte superior de una estructura con un ángulo de elevación de:' },
        { type: 'formula', order: 1, latex: '30^\\circ' },
        { type: 'paragraph', order: 2, text: 'Al avanzar horizontalmente 20 m hacia la estructura hasta un punto B, el ángulo de elevación pasa a ser:' },
        { type: 'formula', order: 3, latex: '45^\\circ' },
        { type: 'paragraph', order: 4, text: 'Suponiendo terreno horizontal y que ambos puntos están alineados con la base de la estructura, ¿cuál es la altura de la estructura?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '10(\\sqrt3-1)\\text{ m}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '10(\\sqrt3+1)\\text{ m}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '20\\sqrt3\\text{ m}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '20(\\sqrt3+1)\\text{ m}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Sea x la distancia desde B hasta la base de la estructura y h su altura. Desde B:' },
        { type: 'formula', order: 1, latex: '\\tan(45^\\circ)=\\frac{h}{x}' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\tan(45^\\circ)=1' },
        { type: 'paragraph', order: 4, text: 'se obtiene:' },
        { type: 'formula', order: 5, latex: 'h=x' },
        { type: 'paragraph', order: 6, text: 'Desde A, la distancia horizontal es:' },
        { type: 'formula', order: 7, latex: 'x+20' },
        { type: 'paragraph', order: 8, text: 'Entonces:' },
        { type: 'formula', order: 9, latex: '\\tan(30^\\circ)=\\frac{h}{x+20}' },
        { type: 'paragraph', order: 10, text: 'Como:' },
        { type: 'formula', order: 11, latex: '\\tan(30^\\circ)=\\frac1{\\sqrt3}' },
        { type: 'paragraph', order: 12, text: 'y h=x:' },
        { type: 'formula', order: 13, latex: '\\frac1{\\sqrt3}=\\frac{x}{x+20}' },
        { type: 'paragraph', order: 14, text: 'Por lo tanto:' },
        { type: 'formula', order: 15, latex: 'x\\sqrt3=x+20' },
        { type: 'formula', order: 16, latex: 'x(\\sqrt3-1)=20' },
        { type: 'formula', order: 17, latex: 'x=\\frac{20}{\\sqrt3-1}' },
        { type: 'paragraph', order: 18, text: 'Racionalizando:' },
        { type: 'formula', order: 19, latex: 'x=\\frac{20(\\sqrt3+1)}{2}' },
        { type: 'formula', order: 20, latex: 'x=10(\\sqrt3+1)' },
        { type: 'paragraph', order: 21, text: 'Como:' },
        { type: 'formula', order: 22, latex: 'h=x' },
        { type: 'paragraph', order: 23, text: 'la altura es:' },
        { type: 'formula', order: 24, latex: '10(\\sqrt3+1)\\text{ m}' },
      ],
    },
  ],
};

export default trigonometriaTriangulosRectangulos;
