// M2-C1A -- Golden Unit M2 / Álgebra y funciones, Recurso 2 (order 2 en U2).
// Contenido editorial APROBADO externamente, transcrito verbatim. Ajustes
// solo técnicos: contentBlocks (heading/paragraph/formula), LaTeX en el
// campo `latex`, questionKey sin padding.
//
// Answer key: R4 -- C D C D C B D A C B  ("CDCDCBDACB").
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const funcionPotenciaModelamientoAlgebraico: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO',
  unitCode: 'M2.ALGEBRA_FUNCIONES',
  subjectKey: 'matematica',
  order: 2,
  title: 'Función potencia y modelamiento algebraico',
  learningObjective:
    'Analizar funciones potencia, interpretar el efecto de sus parámetros y exponentes, comparar comportamientos gráficos y utilizar modelos algebraicos para representar y resolver situaciones de crecimiento, variación y proporcionalidad.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Función potencia y modelamiento algebraico' },

    { type: 'heading', order: 1, level: 2, text: '1. ¿Qué es una función potencia?' },
    { type: 'paragraph', order: 2, text: 'Una función potencia puede escribirse en la forma:' },
    { type: 'formula', order: 3, latex: 'f(x)=ax^n' },
    {
      type: 'paragraph',
      order: 4,
      text: 'donde: a es un número real distinto de cero; n es un exponente; x es la variable independiente. Algunos ejemplos son:',
    },
    { type: 'formula', order: 5, latex: 'f(x)=x^2' },
    { type: 'formula', order: 6, latex: 'g(x)=3x^4' },
    { type: 'formula', order: 7, latex: 'h(x)=-2x^3' },
    { type: 'paragraph', order: 8, text: 'El valor del exponente y del coeficiente determina gran parte del comportamiento de la función.' },

    { type: 'heading', order: 9, level: 2, text: '2. Exponentes pares' },
    { type: 'paragraph', order: 10, text: 'Cuando el exponente es un número entero positivo par, como en:' },
    { type: 'formula', order: 11, latex: 'f(x)=x^2' },
    { type: 'paragraph', order: 12, text: 'se cumple:' },
    { type: 'formula', order: 13, latex: 'f(-x)=f(x)' },
    { type: 'paragraph', order: 14, text: 'Por ejemplo:' },
    { type: 'formula', order: 15, latex: '(-3)^2=3^2=9' },
    { type: 'paragraph', order: 16, text: 'Esto produce una simetría respecto del eje y. En general, para funciones de la forma:' },
    { type: 'formula', order: 17, latex: 'f(x)=ax^n' },
    { type: 'paragraph', order: 18, text: 'con n par, los valores correspondientes a x y -x son iguales.' },

    { type: 'heading', order: 19, level: 2, text: '3. Exponentes impares' },
    { type: 'paragraph', order: 20, text: 'Cuando el exponente es impar:' },
    { type: 'formula', order: 21, latex: 'f(x)=x^3' },
    { type: 'paragraph', order: 22, text: 'se cumple:' },
    { type: 'formula', order: 23, latex: 'f(-x)=-f(x)' },
    { type: 'paragraph', order: 24, text: 'Por ejemplo:' },
    { type: 'formula', order: 25, latex: '(-2)^3=-8' },
    { type: 'paragraph', order: 26, text: 'mientras que:' },
    { type: 'formula', order: 27, latex: '2^3=8' },
    {
      type: 'paragraph',
      order: 28,
      text: 'Las funciones potencia con exponente impar presentan un comportamiento distinto a las de exponente par, especialmente cuando la variable toma valores negativos.',
    },

    { type: 'heading', order: 29, level: 2, text: '4. El efecto del coeficiente' },
    { type: 'paragraph', order: 30, text: 'En:' },
    { type: 'formula', order: 31, latex: 'f(x)=ax^n' },
    { type: 'paragraph', order: 32, text: 'el coeficiente a afecta el valor y la orientación de la función. Si:' },
    { type: 'formula', order: 33, latex: 'a>0' },
    { type: 'paragraph', order: 34, text: 'la función conserva la orientación típica asociada al exponente. Si:' },
    { type: 'formula', order: 35, latex: 'a<0' },
    { type: 'paragraph', order: 36, text: 'todos los valores de salida cambian de signo. Por ejemplo:' },
    { type: 'formula', order: 37, latex: 'f(x)=x^2' },
    { type: 'paragraph', order: 38, text: 'y:' },
    { type: 'formula', order: 39, latex: 'g(x)=-x^2' },
    {
      type: 'paragraph',
      order: 40,
      text: 'tienen los mismos valores absolutos, pero signos opuestos. Además, un valor mayor de |a| multiplica todas las imágenes por un factor mayor.',
    },

    { type: 'heading', order: 41, level: 2, text: '5. Comparación entre diferentes potencias' },
    { type: 'paragraph', order: 42, text: 'Consideremos:' },
    { type: 'formula', order: 43, latex: 'f(x)=x^2' },
    { type: 'paragraph', order: 44, text: 'y:' },
    { type: 'formula', order: 45, latex: 'g(x)=x^4' },
    { type: 'paragraph', order: 46, text: 'Cuando:' },
    { type: 'formula', order: 47, latex: '|x|>1' },
    { type: 'paragraph', order: 48, text: 'se cumple:' },
    { type: 'formula', order: 49, latex: 'x^4>x^2' },
    { type: 'paragraph', order: 50, text: 'Por ejemplo:' },
    { type: 'formula', order: 51, latex: '2^4=16>4=2^2' },
    { type: 'paragraph', order: 52, text: 'Pero cuando:' },
    { type: 'formula', order: 53, latex: '0<|x|<1' },
    { type: 'paragraph', order: 54, text: 'ocurre lo contrario. Por ejemplo:' },
    { type: 'formula', order: 55, latex: '\\left(\\frac12\\right)^4=\\frac1{16}' },
    { type: 'paragraph', order: 56, text: 'mientras que:' },
    { type: 'formula', order: 57, latex: '\\left(\\frac12\\right)^2=\\frac14' },
    { type: 'paragraph', order: 58, text: 'Por lo tanto:' },
    { type: 'formula', order: 59, latex: '\\frac1{16}<\\frac14' },
    { type: 'paragraph', order: 60, text: 'El exponente mayor no implica siempre un valor mayor.' },

    { type: 'heading', order: 61, level: 2, text: '6. Dominio e imagen en funciones potencia' },
    { type: 'paragraph', order: 62, text: 'Para una función como:' },
    { type: 'formula', order: 63, latex: 'f(x)=x^2' },
    { type: 'paragraph', order: 64, text: 'todos los números reales pueden utilizarse como valores de x. Por eso, su dominio es:' },
    { type: 'formula', order: 65, latex: '\\mathbb{R}' },
    { type: 'paragraph', order: 66, text: 'Sin embargo:' },
    { type: 'formula', order: 67, latex: 'x^2\\geq0' },
    { type: 'paragraph', order: 68, text: 'por lo que la función nunca toma valores negativos. En cambio:' },
    { type: 'formula', order: 69, latex: 'g(x)=x^3' },
    {
      type: 'paragraph',
      order: 70,
      text: 'puede tomar cualquier valor real, tanto positivo como negativo. Así, distintas funciones potencia pueden tener comportamientos diferentes aunque compartan el mismo dominio.',
    },

    { type: 'heading', order: 71, level: 2, text: '7. Proporcionalidad mediante potencias' },
    { type: 'paragraph', order: 72, text: 'Muchas situaciones pueden modelarse mediante relaciones del tipo:' },
    { type: 'formula', order: 73, latex: 'y=kx^n' },
    { type: 'paragraph', order: 74, text: 'Por ejemplo, el área de un cuadrado de lado x es:' },
    { type: 'formula', order: 75, latex: 'A=x^2' },
    { type: 'paragraph', order: 76, text: 'Si el lado se duplica:' },
    { type: 'formula', order: 77, latex: 'A(2x)=(2x)^2=4x^2' },
    {
      type: 'paragraph',
      order: 78,
      text: 'Por lo tanto, duplicar una magnitud no siempre duplica el resultado. En una relación cuadrática, duplicar la entrada multiplica la salida por 4.',
    },

    { type: 'heading', order: 79, level: 2, text: '8. Escalamiento' },
    { type: 'paragraph', order: 80, text: 'Si una función tiene la forma:' },
    { type: 'formula', order: 81, latex: 'f(x)=kx^n' },
    { type: 'paragraph', order: 82, text: 'y la entrada se multiplica por un factor c, entonces:' },
    { type: 'formula', order: 83, latex: 'f(cx)=k(cx)^n=c^nkx^n' },
    { type: 'paragraph', order: 84, text: 'Por lo tanto:' },
    { type: 'formula', order: 85, latex: 'f(cx)=c^nf(x)' },
    { type: 'paragraph', order: 86, text: 'Este resultado permite analizar cambios sin calcular cada valor individualmente. Por ejemplo, si:' },
    { type: 'formula', order: 87, latex: 'f(x)=5x^3' },
    { type: 'paragraph', order: 88, text: 'entonces:' },
    { type: 'formula', order: 89, latex: 'f(2x)=2^3f(x)=8f(x)' },

    { type: 'heading', order: 90, level: 2, text: '9. Construcción de modelos algebraicos' },
    { type: 'paragraph', order: 91, text: 'Supongamos que una cantidad Y es directamente proporcional al cuadrado de x. Entonces:' },
    { type: 'formula', order: 92, latex: 'Y=kx^2' },
    { type: 'paragraph', order: 93, text: 'Si además sabemos que cuando:' },
    { type: 'formula', order: 94, latex: 'x=3' },
    { type: 'paragraph', order: 95, text: 'se cumple:' },
    { type: 'formula', order: 96, latex: 'Y=45' },
    { type: 'paragraph', order: 97, text: 'entonces:' },
    { type: 'formula', order: 98, latex: '45=k(3)^2' },
    { type: 'formula', order: 99, latex: '45=9k' },
    { type: 'formula', order: 100, latex: 'k=5' },
    { type: 'paragraph', order: 101, text: 'Por lo tanto, el modelo es:' },
    { type: 'formula', order: 102, latex: 'Y=5x^2' },
    { type: 'paragraph', order: 103, text: 'Un dato conocido permite determinar la constante de proporcionalidad.' },

    { type: 'heading', order: 104, level: 2, text: '10. Interpretar antes de calcular' },
    {
      type: 'paragraph',
      order: 105,
      text: 'En M2 es importante reconocer el comportamiento de un modelo sin depender siempre del cálculo numérico. Por ejemplo, si:',
    },
    { type: 'formula', order: 106, latex: 'P(x)=4x^3' },
    { type: 'paragraph', order: 107, text: 'y x se triplica, entonces:' },
    { type: 'formula', order: 108, latex: 'P(3x)=4(3x)^3=27(4x^3)' },
    { type: 'paragraph', order: 109, text: 'Por lo tanto:' },
    { type: 'formula', order: 110, latex: 'P(3x)=27P(x)' },
    {
      type: 'paragraph',
      order: 111,
      text: 'No fue necesario conocer el valor de x. Identificar la estructura algebraica permite resolver el problema de manera más eficiente.',
    },

    { type: 'heading', order: 112, level: 3, text: 'Situación ZETRYND 1 — Diseño de una superficie cuadrada' },
    { type: 'paragraph', order: 113, text: 'Una plataforma cuadrada tiene lado x metros. Su área está dada por:' },
    { type: 'formula', order: 114, latex: 'A(x)=x^2' },
    { type: 'paragraph', order: 115, text: 'Si el lado aumenta desde x hasta 3x, la nueva área es:' },
    { type: 'formula', order: 116, latex: 'A(3x)=(3x)^2=9x^2' },
    { type: 'paragraph', order: 117, text: 'Por lo tanto:' },
    { type: 'formula', order: 118, latex: 'A(3x)=9A(x)' },
    {
      type: 'paragraph',
      order: 119,
      text: 'Triplicar una longitud produce un área nueve veces mayor. Este tipo de análisis permite anticipar cómo cambia una magnitud cuando depende de una potencia de otra.',
    },

    { type: 'heading', order: 120, level: 3, text: 'Situación ZETRYND 2 — Modelo de energía' },
    { type: 'paragraph', order: 121, text: 'En un modelo simplificado, una cantidad de energía E depende del cubo de una variable v:' },
    { type: 'formula', order: 122, latex: 'E(v)=kv^3' },
    { type: 'paragraph', order: 123, text: 'para cierta constante positiva k. Si:' },
    { type: 'formula', order: 124, latex: 'v=2' },
    { type: 'paragraph', order: 125, text: 'produce:' },
    { type: 'formula', order: 126, latex: 'E=40' },
    { type: 'paragraph', order: 127, text: 'entonces:' },
    { type: 'formula', order: 128, latex: '40=k(2)^3' },
    { type: 'formula', order: 129, latex: '40=8k' },
    { type: 'formula', order: 130, latex: 'k=5' },
    { type: 'paragraph', order: 131, text: 'Por lo tanto:' },
    { type: 'formula', order: 132, latex: 'E(v)=5v^3' },
    { type: 'paragraph', order: 133, text: 'Si posteriormente v se duplica, la energía se multiplica por:' },
    { type: 'formula', order: 134, latex: '2^3=8' },
  ],
  questions: [
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sea:' },
        { type: 'formula', order: 1, latex: 'f(x)=3x^2' },
        { type: 'paragraph', order: 2, text: '¿Cuál es el valor de f(2)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '12' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '18' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Sustituyendo x=2:' },
        { type: 'formula', order: 1, latex: 'f(2)=3(2)^2=3\\cdot4=12' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál de las siguientes funciones cumple:' },
        { type: 'formula', order: 1, latex: 'f(-x)=f(x)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'f(x)=x^3' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)=2x^5' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)=-3x^3' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)=4x^2' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Las potencias de exponente par tienen el mismo valor para x y -x. Como:' },
        { type: 'formula', order: 1, latex: '(-x)^2=x^2' },
        { type: 'paragraph', order: 2, text: 'se cumple:' },
        { type: 'formula', order: 3, latex: '4(-x)^2=4x^2' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sean:' },
        { type: 'formula', order: 1, latex: 'f(x)=x^2' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'g(x)=x^4' },
        { type: 'paragraph', order: 4, text: 'Si:' },
        { type: 'formula', order: 5, latex: '0<x<1' },
        { type: 'paragraph', order: 6, text: '¿cuál relación es correcta?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'f(x)<g(x)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)=g(x)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)>g(x)' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: 'No puede determinarse.' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Cuando 0<x<1, elevar el número a una potencia mayor lo hace más pequeño. Por ejemplo:' },
        { type: 'formula', order: 1, latex: '\\left(\\frac12\\right)^2=\\frac14' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: '\\left(\\frac12\\right)^4=\\frac1{16}' },
        { type: 'paragraph', order: 4, text: 'Entonces:' },
        { type: 'formula', order: 5, latex: 'x^2>x^4' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una cantidad se modela mediante:' },
        { type: 'formula', order: 1, latex: 'P(x)=5x^3' },
        { type: 'paragraph', order: 2, text: 'Si x se duplica, ¿por qué factor se multiplica P(x)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '2' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se tiene:' },
        { type: 'formula', order: 1, latex: 'P(2x)=5(2x)^3=5\\cdot8x^3=8P(x)' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto, la cantidad se multiplica por 8.' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una variable y es directamente proporcional al cuadrado de x. Si:' },
        { type: 'formula', order: 1, latex: 'x=2' },
        { type: 'paragraph', order: 2, text: 'produce:' },
        { type: 'formula', order: 3, latex: 'y=20' },
        { type: 'paragraph', order: 4, text: '¿cuál es el modelo correspondiente?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'y=2x^2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'y=4x^2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'y=5x^2' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'y=10x^2' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Como:' },
        { type: 'formula', order: 1, latex: 'y=kx^2' },
        { type: 'paragraph', order: 2, text: 'se obtiene:' },
        { type: 'formula', order: 3, latex: '20=k(2)^2' },
        { type: 'formula', order: 4, latex: '20=4k' },
        { type: 'formula', order: 5, latex: 'k=5' },
        { type: 'paragraph', order: 6, text: 'Entonces:' },
        { type: 'formula', order: 7, latex: 'y=5x^2' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sea:' },
        { type: 'formula', order: 1, latex: 'f(x)=-2x^4' },
        { type: 'paragraph', order: 2, text: '¿Cuál afirmación es correcta para todo número real x?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'f(x)\\geq0' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)\\leq0' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'f(x)>0' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'f(x)<0' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Como:' },
        { type: 'formula', order: 1, latex: 'x^4\\geq0' },
        { type: 'paragraph', order: 2, text: 'para todo número real x, al multiplicar por -2:' },
        { type: 'formula', order: 3, latex: '-2x^4\\leq0' },
        { type: 'paragraph', order: 4, text: 'Además:' },
        { type: 'formula', order: 5, latex: 'f(0)=0' },
        { type: 'paragraph', order: 6, text: 'por lo que no siempre es estrictamente negativa.' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una magnitud M se modela mediante:' },
        { type: 'formula', order: 1, latex: 'M(x)=kx^4' },
        { type: 'paragraph', order: 2, text: 'con k>0. Si x disminuye a la mitad de su valor original, ¿qué fracción del valor original representa la nueva magnitud?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac12' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac14' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac18' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac1{16}' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se tiene:' },
        { type: 'formula', order: 1, latex: 'M\\left(\\frac{x}{2}\\right)=k\\left(\\frac{x}{2}\\right)^4=\\frac1{16}kx^4' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto:' },
        { type: 'formula', order: 3, latex: 'M\\left(\\frac{x}{2}\\right)=\\frac1{16}M(x)' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se sabe que:' },
        { type: 'formula', order: 1, latex: 'f(x)=ax^3' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'f(2)=24' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 5, latex: 'f(-3)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '-81' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '-54' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '54' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '81' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Primero:' },
        { type: 'formula', order: 1, latex: '24=a(2)^3' },
        { type: 'formula', order: 2, latex: '24=8a' },
        { type: 'formula', order: 3, latex: 'a=3' },
        { type: 'paragraph', order: 4, text: 'Entonces:' },
        { type: 'formula', order: 5, latex: 'f(-3)=3(-3)^3=3(-27)=-81' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una cantidad Q satisface:' },
        { type: 'formula', order: 1, latex: 'Q(x)=kx^n' },
        { type: 'paragraph', order: 2, text: 'con k>0. Se sabe que al duplicar x, el valor de Q se multiplica por 32. ¿Cuál es el valor de n?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '3' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '5' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Al duplicar x:' },
        { type: 'formula', order: 1, latex: 'Q(2x)=k(2x)^n=2^nQ(x)' },
        { type: 'paragraph', order: 2, text: 'Como el valor se multiplica por 32:' },
        { type: 'formula', order: 3, latex: '2^n=32' },
        { type: 'paragraph', order: 4, text: 'y:' },
        { type: 'formula', order: 5, latex: '32=2^5' },
        { type: 'paragraph', order: 6, text: 'Por lo tanto:' },
        { type: 'formula', order: 7, latex: 'n=5' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.FUNCION_POTENCIA_MODELAMIENTO_ALGEBRAICO.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sean las funciones:' },
        { type: 'formula', order: 1, latex: 'f(x)=2x^2' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'g(x)=x^4' },
        { type: 'paragraph', order: 4, text: 'Para valores positivos de x, ¿cuándo se cumple:' },
        { type: 'formula', order: 5, latex: 'f(x)=g(x)?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\text{Solo cuando } x=1' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\text{Solo cuando } x=\\sqrt{2}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\text{Cuando } x=1 \\text{ o } x=2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\text{Para todo } x>0' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Igualamos:' },
        { type: 'formula', order: 1, latex: '2x^2=x^4' },
        { type: 'paragraph', order: 2, text: 'Como x>0, podemos dividir por x^2:' },
        { type: 'formula', order: 3, latex: '2=x^2' },
        { type: 'paragraph', order: 4, text: 'Entonces:' },
        { type: 'formula', order: 5, latex: 'x=\\sqrt{2}' },
        { type: 'paragraph', order: 6, text: 'El valor negativo:' },
        { type: 'formula', order: 7, latex: 'x=-\\sqrt{2}' },
        { type: 'paragraph', order: 8, text: 'también resolvería la ecuación general, pero queda excluido porque el problema pide valores positivos de x.' },
      ],
    },
  ],
};

export default funcionPotenciaModelamientoAlgebraico;
