// M2-C1A -- Golden Unit M2 / Álgebra y funciones, Recurso 1 (order 1 en U2).
// Contenido editorial APROBADO externamente, transcrito verbatim. Ajustes
// solo técnicos: contentBlocks (heading/paragraph/formula), LaTeX en el
// campo `latex`, questionKey sin padding.
//
// Answer key: R3 -- B B D C B B C C A D  ("BBDCBBCCAD").
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const sistemasEcuacionesEcuacionesCuadraticas: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS',
  unitCode: 'M2.ALGEBRA_FUNCIONES',
  subjectKey: 'matematica',
  order: 1,
  title: 'Sistemas de ecuaciones y ecuaciones cuadráticas',
  learningObjective:
    'Resolver, representar e interpretar sistemas de ecuaciones lineales de dos incógnitas y ecuaciones cuadráticas, reconociendo la cantidad y naturaleza de sus soluciones y utilizando propiedades algebraicas y gráficas para resolver problemas.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Sistemas de ecuaciones y ecuaciones cuadráticas' },

    { type: 'heading', order: 1, level: 2, text: '1. Sistemas de ecuaciones lineales' },
    { type: 'paragraph', order: 2, text: 'Un sistema de dos ecuaciones lineales con dos incógnitas puede escribirse como:' },
    { type: 'formula', order: 3, latex: '\\begin{cases} a_1x+b_1y=c_1 \\\\ a_2x+b_2y=c_2 \\end{cases}' },
    { type: 'paragraph', order: 4, text: 'Resolver el sistema significa encontrar los valores de x e y que satisfacen ambas ecuaciones al mismo tiempo. Por ejemplo:' },
    { type: 'formula', order: 5, latex: '\\begin{cases} x+y=7 \\\\ x-y=1 \\end{cases}' },
    { type: 'paragraph', order: 6, text: 'Sumando ambas ecuaciones:' },
    { type: 'formula', order: 7, latex: '2x=8' },
    { type: 'paragraph', order: 8, text: 'por lo que:' },
    { type: 'formula', order: 9, latex: 'x=4' },
    { type: 'paragraph', order: 10, text: 'Luego:' },
    { type: 'formula', order: 11, latex: 'y=3' },
    { type: 'paragraph', order: 12, text: 'La solución es:' },
    { type: 'formula', order: 13, latex: '(x,y)=(4,3)' },

    { type: 'heading', order: 14, level: 2, text: '2. Interpretación gráfica de un sistema' },
    {
      type: 'paragraph',
      order: 15,
      text: 'Cada ecuación lineal de dos incógnitas representa una recta en el plano cartesiano. Resolver un sistema equivale a buscar los puntos que pertenecen simultáneamente a ambas rectas. Pueden ocurrir tres situaciones: las rectas se intersectan en un punto; las rectas coinciden; las rectas son paralelas distintas. Estas situaciones corresponden a distintas cantidades de soluciones.',
    },

    { type: 'heading', order: 16, level: 2, text: '3. Sistema con solución única' },
    {
      type: 'paragraph',
      order: 17,
      text: 'Cuando dos rectas tienen pendientes distintas, se intersectan en un único punto. Entonces el sistema tiene exactamente una solución. Por ejemplo:',
    },
    { type: 'formula', order: 18, latex: 'y=2x+1' },
    { type: 'formula', order: 19, latex: 'y=-x+7' },
    { type: 'paragraph', order: 20, text: 'Como las pendientes son distintas, las rectas se cortan una vez. Igualando:' },
    { type: 'formula', order: 21, latex: '2x+1=-x+7' },
    { type: 'formula', order: 22, latex: '3x=6' },
    { type: 'formula', order: 23, latex: 'x=2' },
    { type: 'paragraph', order: 24, text: 'y:' },
    { type: 'formula', order: 25, latex: 'y=5' },
    { type: 'paragraph', order: 26, text: 'Por lo tanto, la solución es:' },
    { type: 'formula', order: 27, latex: '(2,5)' },

    { type: 'heading', order: 28, level: 2, text: '4. Sistemas sin solución e infinitas soluciones' },
    { type: 'paragraph', order: 29, text: 'Consideremos:' },
    { type: 'formula', order: 30, latex: 'y=3x+2' },
    { type: 'formula', order: 31, latex: 'y=3x-4' },
    {
      type: 'paragraph',
      order: 32,
      text: 'Ambas rectas tienen la misma pendiente, pero diferentes interceptos. Son paralelas y nunca se intersectan. El sistema no tiene solución. En cambio:',
    },
    { type: 'formula', order: 33, latex: '2x+y=6' },
    { type: 'formula', order: 34, latex: '4x+2y=12' },
    {
      type: 'paragraph',
      order: 35,
      text: 'representan la misma recta, porque la segunda ecuación es el doble de la primera. En este caso existen infinitas soluciones.',
    },

    { type: 'heading', order: 36, level: 2, text: '5. Métodos algebraicos de resolución' },
    {
      type: 'paragraph',
      order: 37,
      text: 'Entre los métodos más comunes se encuentran: sustitución; igualación; reducción o eliminación. Por ejemplo:',
    },
    { type: 'formula', order: 38, latex: '\\begin{cases} 2x+y=9 \\\\ x-y=0 \\end{cases}' },
    { type: 'paragraph', order: 39, text: 'Sumando las ecuaciones:' },
    { type: 'formula', order: 40, latex: '3x=9' },
    { type: 'formula', order: 41, latex: 'x=3' },
    { type: 'paragraph', order: 42, text: 'Luego:' },
    { type: 'formula', order: 43, latex: 'y=3' },
    { type: 'paragraph', order: 44, text: 'La elección del método depende de la forma en que aparecen las ecuaciones.' },

    { type: 'heading', order: 45, level: 2, text: '6. Ecuaciones de segundo grado' },
    { type: 'paragraph', order: 46, text: 'Una ecuación cuadrática tiene la forma:' },
    { type: 'formula', order: 47, latex: 'ax^2+bx+c=0' },
    { type: 'paragraph', order: 48, text: 'con:' },
    { type: 'formula', order: 49, latex: 'a\\neq0' },
    { type: 'paragraph', order: 50, text: 'Por ejemplo:' },
    { type: 'formula', order: 51, latex: 'x^2-5x+6=0' },
    { type: 'paragraph', order: 52, text: 'puede factorizarse como:' },
    { type: 'formula', order: 53, latex: '(x-2)(x-3)=0' },
    { type: 'paragraph', order: 54, text: 'Por lo tanto:' },
    { type: 'formula', order: 55, latex: 'x=2' },
    { type: 'paragraph', order: 56, text: 'o:' },
    { type: 'formula', order: 57, latex: 'x=3' },
    { type: 'paragraph', order: 58, text: 'Una ecuación cuadrática puede tener dos, una o ninguna solución real.' },

    { type: 'heading', order: 59, level: 2, text: '7. Fórmula general' },
    { type: 'paragraph', order: 60, text: 'Cuando una ecuación cuadrática no puede factorizarse fácilmente, puede utilizarse la fórmula:' },
    { type: 'formula', order: 61, latex: 'x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}' },
    { type: 'paragraph', order: 62, text: 'Por ejemplo:' },
    { type: 'formula', order: 63, latex: 'x^2-4x-1=0' },
    { type: 'paragraph', order: 64, text: 'Aquí:' },
    { type: 'formula', order: 65, latex: 'a=1,\\quad b=-4,\\quad c=-1' },
    { type: 'paragraph', order: 66, text: 'Entonces:' },
    { type: 'formula', order: 67, latex: 'x=\\frac{4\\pm\\sqrt{16+4}}{2}' },
    { type: 'formula', order: 68, latex: 'x=\\frac{4\\pm\\sqrt{20}}{2}' },

    { type: 'heading', order: 69, level: 2, text: '8. El discriminante' },
    { type: 'paragraph', order: 70, text: 'La expresión:' },
    { type: 'formula', order: 71, latex: '\\Delta=b^2-4ac' },
    { type: 'paragraph', order: 72, text: 'se denomina discriminante. Permite conocer el número de soluciones reales sin resolver completamente la ecuación. Si:' },
    { type: 'formula', order: 73, latex: '\\Delta>0' },
    { type: 'paragraph', order: 74, text: 'hay dos soluciones reales distintas. Si:' },
    { type: 'formula', order: 75, latex: '\\Delta=0' },
    { type: 'paragraph', order: 76, text: 'hay una única solución real. Si:' },
    { type: 'formula', order: 77, latex: '\\Delta<0' },
    { type: 'paragraph', order: 78, text: 'no existen soluciones reales.' },

    { type: 'heading', order: 79, level: 2, text: '9. Interpretación gráfica de una ecuación cuadrática' },
    { type: 'paragraph', order: 80, text: 'La expresión:' },
    { type: 'formula', order: 81, latex: 'y=ax^2+bx+c' },
    { type: 'paragraph', order: 82, text: 'representa una parábola. Resolver:' },
    { type: 'formula', order: 83, latex: 'ax^2+bx+c=0' },
    {
      type: 'paragraph',
      order: 84,
      text: 'equivale a buscar los puntos donde la parábola intersecta el eje x. Por eso: dos intersecciones implican dos soluciones reales; una intersección implica una solución real doble; ninguna intersección implica ausencia de soluciones reales. El álgebra y la geometría describen el mismo fenómeno desde representaciones diferentes.',
    },

    { type: 'heading', order: 85, level: 2, text: '10. Modelamiento mediante ecuaciones' },
    {
      type: 'paragraph',
      order: 86,
      text: 'Los sistemas y ecuaciones cuadráticas pueden aparecer en problemas donde las incógnitas representan cantidades reales. Por ejemplo, si dos números suman 14 y su diferencia es 4:',
    },
    { type: 'formula', order: 87, latex: '\\begin{cases} x+y=14 \\\\ x-y=4 \\end{cases}' },
    { type: 'paragraph', order: 88, text: 'De forma similar, si un rectángulo tiene lados x y x+3, y área 40:' },
    { type: 'formula', order: 89, latex: 'x(x+3)=40' },
    { type: 'paragraph', order: 90, text: 'Entonces:' },
    { type: 'formula', order: 91, latex: 'x^2+3x-40=0' },
    { type: 'paragraph', order: 92, text: 'El modelo algebraico permite transformar una situación en una ecuación que puede resolverse.' },

    { type: 'heading', order: 93, level: 3, text: 'Situación ZETRYND 1 — Dos planes de transporte' },
    { type: 'paragraph', order: 94, text: 'Una empresa compara dos planes de transporte. El costo del Plan A se modela mediante:' },
    { type: 'formula', order: 95, latex: 'C_A(x)=400x+3000' },
    { type: 'paragraph', order: 96, text: 'y el costo del Plan B mediante:' },
    { type: 'formula', order: 97, latex: 'C_B(x)=250x+4500' },
    { type: 'paragraph', order: 98, text: 'donde x representa la cantidad de viajes realizados. Para determinar cuándo ambos planes cuestan lo mismo:' },
    { type: 'formula', order: 99, latex: '400x+3000=250x+4500' },
    { type: 'paragraph', order: 100, text: 'Entonces:' },
    { type: 'formula', order: 101, latex: '150x=1500' },
    { type: 'formula', order: 102, latex: 'x=10' },
    {
      type: 'paragraph',
      order: 103,
      text: 'Con 10 viajes, ambos planes tienen el mismo costo. Antes de ese punto uno puede ser más conveniente y después del punto de intersección puede serlo el otro.',
    },

    { type: 'heading', order: 104, level: 3, text: 'Situación ZETRYND 2 — Diseño de una superficie' },
    { type: 'paragraph', order: 105, text: 'Una superficie rectangular tiene un lado x metros y el otro mide x+4 metros. Si su área es:' },
    { type: 'formula', order: 106, latex: '96\\text{ m}^2' },
    { type: 'paragraph', order: 107, text: 'entonces:' },
    { type: 'formula', order: 108, latex: 'x(x+4)=96' },
    { type: 'formula', order: 109, latex: 'x^2+4x-96=0' },
    { type: 'paragraph', order: 110, text: 'Factorizando:' },
    { type: 'formula', order: 111, latex: '(x+12)(x-8)=0' },
    { type: 'paragraph', order: 112, text: 'Las soluciones algebraicas son:' },
    { type: 'formula', order: 113, latex: 'x=-12' },
    { type: 'paragraph', order: 114, text: 'y:' },
    { type: 'formula', order: 115, latex: 'x=8' },
    { type: 'paragraph', order: 116, text: 'Como una longitud no puede ser negativa, la solución físicamente válida es:' },
    { type: 'formula', order: 117, latex: 'x=8' },
    { type: 'paragraph', order: 118, text: 'Por lo tanto, las dimensiones son 8 m y 12 m.' },
  ],
  questions: [
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál es la solución del sistema?' },
        { type: 'formula', order: 1, latex: '\\begin{cases} x+y=9 \\\\ x-y=3 \\end{cases}' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '(3,6)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(6,3)' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '(9,3)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '(6,6)' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Sumando ambas ecuaciones:' },
        { type: 'formula', order: 1, latex: '2x=12' },
        { type: 'paragraph', order: 2, text: 'por lo que:' },
        { type: 'formula', order: 3, latex: 'x=6' },
        { type: 'paragraph', order: 4, text: 'Luego:' },
        { type: 'formula', order: 5, latex: '6+y=9' },
        { type: 'paragraph', order: 6, text: 'y entonces:' },
        { type: 'formula', order: 7, latex: 'y=3' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuáles son las soluciones de:' },
        { type: 'formula', order: 1, latex: 'x^2-7x+12=0?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'x=2 \\ \\text{y}\\ x=6' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'x=3 \\ \\text{y}\\ x=4' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'x=-3 \\ \\text{y}\\ x=-4' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'x=1 \\ \\text{y}\\ x=12' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se factoriza como:' },
        { type: 'formula', order: 1, latex: '(x-3)(x-4)=0' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto:' },
        { type: 'formula', order: 3, latex: 'x=3' },
        { type: 'paragraph', order: 4, text: 'o:' },
        { type: 'formula', order: 5, latex: 'x=4' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuántas soluciones tiene el siguiente sistema?' },
        { type: 'formula', order: 1, latex: '\\begin{cases} 2x+y=5 \\\\ 4x+2y=10 \\end{cases}' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'Ninguna' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Una' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Dos' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Infinitas' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La segunda ecuación es exactamente el doble de la primera.' },
        { type: 'paragraph', order: 1, text: 'Por lo tanto, ambas representan la misma recta y existen infinitos pares (x,y) que satisfacen el sistema.' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se consideran las rectas:' },
        { type: 'formula', order: 1, latex: 'y=4x+1' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'y=4x-5' },
        { type: 'paragraph', order: 4, text: '¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'Se intersectan en exactamente un punto.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Representan la misma recta.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Son paralelas y el sistema no tiene solución.' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: 'Se intersectan en dos puntos.' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Ambas rectas tienen pendiente 4, pero distintos interceptos.' },
        { type: 'paragraph', order: 1, text: 'Por lo tanto, son paralelas distintas y nunca se intersectan.' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál es el discriminante de la ecuación:' },
        { type: 'formula', order: 1, latex: '2x^2-5x+2=0?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '1' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '17' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '25' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Aquí:' },
        { type: 'formula', order: 1, latex: 'a=2,\\quad b=-5,\\quad c=2' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '\\Delta=b^2-4ac' },
        { type: 'formula', order: 4, latex: '\\Delta=25-16=9' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Una ecuación cuadrática tiene discriminante igual a 0. ¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'Tiene dos soluciones reales distintas.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Tiene exactamente una solución real.' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: 'No tiene soluciones reales.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'Tiene infinitas soluciones reales.' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Cuando:' },
        { type: 'formula', order: 1, latex: '\\Delta=0' },
        { type: 'paragraph', order: 2, text: 'la fórmula general produce el mismo valor para los signos + y -.' },
        { type: 'paragraph', order: 3, text: 'Por eso existe una única solución real.' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Para cierto valor de k, el sistema:' },
        { type: 'formula', order: 1, latex: '\\begin{cases} 2x+3y=7 \\\\ 4x+6y=k \\end{cases}' },
        { type: 'paragraph', order: 2, text: 'tiene infinitas soluciones. ¿Cuál debe ser el valor de k?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '7' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '10' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '14' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '21' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Para representar la misma recta, la segunda ecuación debe ser exactamente el doble de la primera. Multiplicando:' },
        { type: 'formula', order: 1, latex: '2(2x+3y=7)' },
        { type: 'paragraph', order: 2, text: 'se obtiene:' },
        { type: 'formula', order: 3, latex: '4x+6y=14' },
        { type: 'paragraph', order: 4, text: 'Por lo tanto:' },
        { type: 'formula', order: 5, latex: 'k=14' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Para qué valor de m la ecuación:' },
        { type: 'formula', order: 1, latex: 'x^2-6x+m=0' },
        { type: 'paragraph', order: 2, text: 'tiene exactamente una solución real?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'm=6' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'm=8' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'm=9' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'm=12' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Para tener exactamente una solución real debe cumplirse:' },
        { type: 'formula', order: 1, latex: '\\Delta=0' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '(-6)^2-4(1)(m)=0' },
        { type: 'formula', order: 4, latex: '36-4m=0' },
        { type: 'formula', order: 5, latex: 'm=9' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un rectángulo tiene un área de 60 m². Su largo mide 7 metros más que su ancho. Si el ancho es x, ¿cuál ecuación permite determinar sus dimensiones?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'x^2+7x-60=0' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'x^2-7x-60=0' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '2x+7=60' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '7x^2=60' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'El largo es:' },
        { type: 'formula', order: 1, latex: 'x+7' },
        { type: 'paragraph', order: 2, text: 'y el área:' },
        { type: 'formula', order: 3, latex: 'x(x+7)=60' },
        { type: 'paragraph', order: 4, text: 'Desarrollando:' },
        { type: 'formula', order: 5, latex: 'x^2+7x-60=0' },
      ],
    },
    {
      questionKey: 'M2.ALGEBRA_FUNCIONES.SISTEMAS_ECUACIONES_ECUACIONES_CUADRATICAS.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Para cierto valor de k, la ecuación:' },
        { type: 'formula', order: 1, latex: 'x^2+kx+16=0' },
        { type: 'paragraph', order: 2, text: 'tiene una única solución real negativa. ¿Cuál de los siguientes valores de k cumple esta condición?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '-8' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '-4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Para tener una única solución real:' },
        { type: 'formula', order: 1, latex: '\\Delta=0' },
        { type: 'paragraph', order: 2, text: 'Por lo tanto:' },
        { type: 'formula', order: 3, latex: 'k^2-64=0' },
        { type: 'formula', order: 4, latex: 'k=\\pm8' },
        { type: 'paragraph', order: 5, text: 'Si:' },
        { type: 'formula', order: 6, latex: 'k=8' },
        { type: 'paragraph', order: 7, text: 'la ecuación es:' },
        { type: 'formula', order: 8, latex: 'x^2+8x+16=0' },
        { type: 'formula', order: 9, latex: '(x+4)^2=0' },
        { type: 'paragraph', order: 10, text: 'y la única solución es:' },
        { type: 'formula', order: 11, latex: 'x=-4' },
        { type: 'paragraph', order: 12, text: 'que es negativa. Si k=-8, la única solución sería positiva.' },
      ],
    },
  ],
};

export default sistemasEcuacionesEcuacionesCuadraticas;
