// M2-C2A -- Golden Unit M2 / Probabilidad y estadística, Recurso 1 (order 1
// en U4). Contenido editorial APROBADO externamente, transcrito verbatim.
// Ajustes solo técnicos: contentBlocks (heading/paragraph/formula), LaTeX en
// `latex`, questionKey sin padding.
//
// Answer key: R7 -- C B B C B B C A C C  ("CBBCBBCACC").
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const medidasDispersionProbabilidadCondicional: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL',
  unitCode: 'M2.PROBABILIDAD_ESTADISTICA',
  subjectKey: 'matematica',
  order: 1,
  title: 'Medidas de dispersión y probabilidad condicional',
  learningObjective:
    'Analizar la variabilidad de conjuntos de datos mediante medidas de dispersión e interpretar probabilidades condicionadas, utilizando información estadística y relaciones entre eventos para comparar distribuciones y resolver problemas probabilísticos.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Medidas de dispersión y probabilidad condicional' },

    { type: 'heading', order: 1, level: 2, text: '1. ¿Qué significa dispersión?' },
    {
      type: 'paragraph',
      order: 2,
      text: 'Las medidas de tendencia central, como la media, permiten describir un valor representativo de un conjunto de datos. Sin embargo, dos conjuntos pueden tener la misma media y comportarse de manera muy diferente. Por ejemplo:',
    },
    { type: 'paragraph', order: 3, text: 'Conjunto A:' },
    { type: 'formula', order: 4, latex: '4,\\;5,\\;6' },
    { type: 'paragraph', order: 5, text: 'Conjunto B:' },
    { type: 'formula', order: 6, latex: '0,\\;5,\\;10' },
    { type: 'paragraph', order: 7, text: 'Ambos tienen media:' },
    { type: 'formula', order: 8, latex: '5' },
    { type: 'paragraph', order: 9, text: 'pero los datos del conjunto B están mucho más separados entre sí. La dispersión permite describir esta variabilidad.' },

    { type: 'heading', order: 10, level: 2, text: '2. El rango' },
    { type: 'paragraph', order: 11, text: 'Una medida sencilla de dispersión es el rango. Se calcula mediante:' },
    { type: 'formula', order: 12, latex: 'R=x_{\\max}-x_{\\min}' },
    { type: 'paragraph', order: 13, text: 'Por ejemplo, para:' },
    { type: 'formula', order: 14, latex: '3,\\;7,\\;8,\\;11' },
    { type: 'paragraph', order: 15, text: 'el rango es:' },
    { type: 'formula', order: 16, latex: '11-3=8' },
    { type: 'paragraph', order: 17, text: 'El rango es fácil de calcular, pero solo considera los valores extremos y no utiliza toda la información del conjunto.' },

    { type: 'heading', order: 18, level: 2, text: '3. Distancia respecto de la media' },
    { type: 'paragraph', order: 19, text: 'Para estudiar con mayor precisión la dispersión se puede analizar cuánto se aleja cada dato de la media. Si la media es:' },
    { type: 'formula', order: 20, latex: '\\bar{x}' },
    { type: 'paragraph', order: 21, text: 'la diferencia:' },
    { type: 'formula', order: 22, latex: 'x_i-\\bar{x}' },
    {
      type: 'paragraph',
      order: 23,
      text: 'indica cuánto se desvía el dato x_i. Algunas desviaciones pueden ser positivas y otras negativas. Por eso no resulta conveniente simplemente sumarlas, ya que pueden cancelarse entre sí.',
    },

    { type: 'heading', order: 24, level: 2, text: '4. Varianza' },
    { type: 'paragraph', order: 25, text: 'La varianza utiliza los cuadrados de las desviaciones respecto de la media. Para una colección de n datos puede expresarse como:' },
    { type: 'formula', order: 26, latex: '\\sigma^2=\\frac{\\sum_{i=1}^{n}(x_i-\\bar{x})^2}{n}' },
    {
      type: 'paragraph',
      order: 27,
      text: 'en el caso de considerar el conjunto completo como población. Una varianza pequeña indica que los datos se encuentran relativamente cerca de la media. Una varianza mayor indica una distribución más dispersa.',
    },

    { type: 'heading', order: 28, level: 2, text: '5. Desviación estándar' },
    { type: 'paragraph', order: 29, text: 'La desviación estándar es la raíz cuadrada de la varianza:' },
    { type: 'formula', order: 30, latex: '\\sigma=\\sqrt{\\sigma^2}' },
    {
      type: 'paragraph',
      order: 31,
      text: 'Una ventaja de esta medida es que queda expresada en las mismas unidades que los datos originales. Por ejemplo, si las estaturas se miden en centímetros, la desviación estándar también se expresa en centímetros. Una desviación estándar mayor implica, en general, mayor dispersión alrededor de la media.',
    },

    { type: 'heading', order: 32, level: 2, text: '6. Comparar conjuntos de datos' },
    { type: 'paragraph', order: 33, text: 'Supongamos que dos grupos tienen la misma media.' },
    { type: 'paragraph', order: 34, text: 'Grupo A:' },
    { type: 'formula', order: 35, latex: '8,\\;9,\\;10,\\;11,\\;12' },
    { type: 'paragraph', order: 36, text: 'Grupo B:' },
    { type: 'formula', order: 37, latex: '2,\\;6,\\;10,\\;14,\\;18' },
    {
      type: 'paragraph',
      order: 38,
      text: 'Ambos tienen media 10, pero el Grupo B presenta valores mucho más alejados del centro. Por lo tanto, su varianza y su desviación estándar son mayores. La media describe el centro. La desviación estándar describe cuánto se separan los datos de ese centro.',
    },

    { type: 'heading', order: 39, level: 2, text: '7. Probabilidad de un evento' },
    { type: 'paragraph', order: 40, text: 'Si todos los resultados de un experimento son igualmente probables:' },
    { type: 'formula', order: 41, latex: 'P(A)=\\frac{\\text{casos favorables a }A}{\\text{casos posibles}}' },
    { type: 'paragraph', order: 42, text: 'Por ejemplo, al lanzar un dado común:' },
    { type: 'formula', order: 43, latex: 'P(\\text{obtener un número par})=\\frac36=\\frac12' },
    { type: 'paragraph', order: 44, text: 'Pero esta probabilidad puede cambiar cuando se obtiene información adicional.' },

    { type: 'heading', order: 45, level: 2, text: '8. Probabilidad condicional' },
    { type: 'paragraph', order: 46, text: 'La probabilidad condicional de A dado B se representa como:' },
    { type: 'formula', order: 47, latex: 'P(A\\mid B)' },
    { type: 'paragraph', order: 48, text: 'y significa: probabilidad de que ocurra A, sabiendo que ocurrió B. Su fórmula es:' },
    { type: 'formula', order: 49, latex: 'P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}' },
    { type: 'paragraph', order: 50, text: 'si:' },
    { type: 'formula', order: 51, latex: 'P(B)>0' },
    { type: 'paragraph', order: 52, text: 'La información de que ocurrió B modifica el espacio de resultados que debemos considerar.' },

    { type: 'heading', order: 53, level: 2, text: '9. Información condicionada en tablas' },
    {
      type: 'paragraph',
      order: 54,
      text: 'Supongamos que un grupo tiene: 20 estudiantes que practican deporte; de ellos, 8 también participan en un taller musical. Si seleccionamos una persona sabiendo que practica deporte, la probabilidad de que también participe en música es:',
    },
    { type: 'formula', order: 55, latex: 'P(\\text{Música}\\mid\\text{Deporte})=\\frac8{20}' },
    { type: 'formula', order: 56, latex: '=\\frac25' },
    { type: 'paragraph', order: 57, text: 'El denominador ya no es el total general, sino únicamente el grupo indicado por la condición.' },

    { type: 'heading', order: 58, level: 2, text: '10. Independencia de eventos' },
    { type: 'paragraph', order: 59, text: 'Dos eventos A y B son independientes cuando conocer que ocurrió uno no cambia la probabilidad del otro. Una forma de expresarlo es:' },
    { type: 'formula', order: 60, latex: 'P(A\\mid B)=P(A)' },
    { type: 'paragraph', order: 61, text: 'si:' },
    { type: 'formula', order: 62, latex: 'P(B)>0' },
    { type: 'paragraph', order: 63, text: 'Equivalentemente:' },
    { type: 'formula', order: 64, latex: 'P(A\\cap B)=P(A)P(B)' },
    {
      type: 'paragraph',
      order: 65,
      text: 'Si estas relaciones no se cumplen, los eventos no son independientes. Es importante distinguir entre: eventos independientes; eventos mutuamente excluyentes. No significan lo mismo.',
    },

    { type: 'heading', order: 66, level: 3, text: 'Situación ZETRYND 1 — Rendimiento de dos grupos' },
    { type: 'paragraph', order: 67, text: 'Dos grupos obtuvieron los siguientes puntajes:' },
    { type: 'paragraph', order: 68, text: 'Grupo A:' },
    { type: 'formula', order: 69, latex: '60,\\;65,\\;70,\\;75,\\;80' },
    { type: 'paragraph', order: 70, text: 'Grupo B:' },
    { type: 'formula', order: 71, latex: '50,\\;60,\\;70,\\;80,\\;90' },
    { type: 'paragraph', order: 72, text: 'La media de ambos grupos es:' },
    { type: 'formula', order: 73, latex: '70' },
    { type: 'paragraph', order: 74, text: 'Sin embargo, el Grupo B presenta valores más alejados de la media. Para el Grupo A, las desviaciones respecto de 70 son:' },
    { type: 'formula', order: 75, latex: '-10,\\;-5,\\;0,\\;5,\\;10' },
    { type: 'paragraph', order: 76, text: 'Para el Grupo B:' },
    { type: 'formula', order: 77, latex: '-20,\\;-10,\\;0,\\;10,\\;20' },
    {
      type: 'paragraph',
      order: 78,
      text: 'Por lo tanto, el Grupo B tiene una varianza y una desviación estándar mayores. Esto muestra por qué la media por sí sola no describe completamente una distribución.',
    },

    { type: 'heading', order: 79, level: 3, text: 'Situación ZETRYND 2 — Preferencias de estudio' },
    {
      type: 'paragraph',
      order: 80,
      text: 'En un grupo de 100 estudiantes: 60 utilizan videos para estudiar; 40 utilizan tarjetas de memoria; 25 utilizan ambos métodos. Sea: V: utilizar videos; T: utilizar tarjetas. La probabilidad de que un estudiante utilice tarjetas sabiendo que utiliza videos es:',
    },
    { type: 'formula', order: 81, latex: 'P(T\\mid V)=\\frac{P(T\\cap V)}{P(V)}' },
    { type: 'paragraph', order: 82, text: 'Utilizando los conteos:' },
    { type: 'formula', order: 83, latex: 'P(T\\mid V)=\\frac{25}{60}' },
    { type: 'formula', order: 84, latex: '=\\frac5{12}' },
    { type: 'paragraph', order: 85, text: 'La condición "utiliza videos" reduce el grupo relevante de 100 estudiantes a 60.' },
  ],
  questions: [
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál es el rango del conjunto:' },
        { type: 'formula', order: 1, latex: '4,\\;7,\\;9,\\;13,\\;15' },
        { type: 'paragraph', order: 2, text: '?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '11' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '15' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'El rango es:' },
        { type: 'formula', order: 1, latex: '15-4=11' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Dos grupos tienen la misma media. El Grupo A tiene desviación estándar 2 y el Grupo B tiene desviación estándar 7. ¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'El Grupo A tiene necesariamente una media mayor.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'El Grupo B presenta mayor dispersión alrededor de su media.' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: 'Ambos grupos tienen exactamente los mismos datos.' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: 'El Grupo A tiene necesariamente más observaciones.' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Una desviación estándar mayor indica una mayor dispersión de los datos alrededor de la media. Por eso, el Grupo B es más variable.' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál es la media del conjunto:' },
        { type: 'formula', order: 1, latex: '2,\\;4,\\;6,\\;8' },
        { type: 'paragraph', order: 2, text: '?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '5' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La media es:' },
        { type: 'formula', order: 1, latex: '\\frac{2+4+6+8}{4}=\\frac{20}{4}=5' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se consideran los conjuntos:' },
        { type: 'formula', order: 1, latex: 'A=\\{9,10,11\\}' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'B=\\{5,10,15\\}' },
        { type: 'paragraph', order: 4, text: '¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'Ambos tienen igual media e igual dispersión.' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'A \\text{ tiene mayor media.}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\text{Ambos tienen la misma media, pero } B \\text{ tiene mayor dispersión.}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'B \\text{ tiene menor media y menor dispersión.}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Ambos conjuntos tienen media:' },
        { type: 'formula', order: 1, latex: '10' },
        { type: 'paragraph', order: 2, text: 'Sin embargo, en B los valores se encuentran más alejados de 10, por lo que presenta mayor dispersión.' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En una población se cumple:' },
        { type: 'formula', order: 1, latex: 'P(A\\cap B)=0,18' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'P(B)=0,6' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 5, latex: 'P(A\\mid B)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '0,18' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '0,3' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '0,42' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '0,78' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Aplicamos:' },
        { type: 'formula', order: 1, latex: 'P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: 'P(A\\mid B)=\\frac{0,18}{0,6}=0,3' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un grupo de 50 personas, 30 practican natación. De quienes practican natación, 12 también practican ciclismo. Si se elige una persona al azar sabiendo que practica natación, ¿cuál es la probabilidad de que también practique ciclismo?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac6{25}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac25' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac35' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac{12}{50}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La condición restringe el espacio a las 30 personas que practican natación. De ellas, 12 practican ciclismo. Por lo tanto:' },
        { type: 'formula', order: 1, latex: 'P(\\text{Ciclismo}\\mid\\text{Natación})=\\frac{12}{30}=\\frac25' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Los conjuntos:' },
        { type: 'formula', order: 1, latex: 'A=\\{2,4,6,8,10\\}' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: 'B=\\{6,7,8,9,10\\}' },
        { type: 'paragraph', order: 4, text: 'tienen la misma cantidad de datos. ¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: 'Tienen la misma media y la misma dispersión.' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'A \\text{ tiene mayor media y menor dispersión.}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'A \\text{ tiene menor media y mayor dispersión.}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'B \\text{ tiene menor media y mayor dispersión.}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La media de A es:' },
        { type: 'formula', order: 1, latex: '\\frac{2+4+6+8+10}{5}=6' },
        { type: 'paragraph', order: 2, text: 'La media de B es:' },
        { type: 'formula', order: 3, latex: '\\frac{6+7+8+9+10}{5}=8' },
        { type: 'paragraph', order: 4, text: 'Además, los datos de A están más separados entre sí y respecto de su media. Por lo tanto, A tiene menor media y mayor dispersión.' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un grupo de estudiantes:' },
        { type: 'formula', order: 1, latex: 'P(A)=0,5' },
        { type: 'formula', order: 2, latex: 'P(B)=0,4' },
        { type: 'paragraph', order: 3, text: 'y:' },
        { type: 'formula', order: 4, latex: 'P(A\\cap B)=0,2' },
        { type: 'paragraph', order: 5, text: '¿Cuál afirmación es correcta?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'A \\text{ y } B \\text{ son independientes.}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'A \\text{ y } B \\text{ son mutuamente excluyentes.}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'P(A\\mid B)=0,2.' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'P(B\\mid A)=0,8.' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Para que sean independientes debe cumplirse:' },
        { type: 'formula', order: 1, latex: 'P(A\\cap B)=P(A)P(B)' },
        { type: 'paragraph', order: 2, text: 'Calculando:' },
        { type: 'formula', order: 3, latex: '0,5\\cdot0,4=0,2' },
        { type: 'paragraph', order: 4, text: 'Como coincide con:' },
        { type: 'formula', order: 5, latex: 'P(A\\cap B)=0,2' },
        { type: 'paragraph', order: 6, text: 'los eventos son independientes.' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'En un curso, el 60\\% de los estudiantes estudia Matemática y el 45\\% estudia Física. Además, el 30\\% estudia ambas materias. Si se selecciona un estudiante que estudia Física, ¿cuál es la probabilidad de que también estudie Matemática?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac13' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac12' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\frac23' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\frac34' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Se busca:' },
        { type: 'formula', order: 1, latex: 'P(M\\mid F)=\\frac{P(M\\cap F)}{P(F)}' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: 'P(M\\mid F)=\\frac{0,30}{0,45}' },
        { type: 'formula', order: 4, latex: '=\\frac{30}{45}=\\frac23' },
      ],
    },
    {
      questionKey: 'M2.PROBABILIDAD_ESTADISTICA.MEDIDAS_DISPERSION_PROBABILIDAD_CONDICIONAL.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se sabe que:' },
        { type: 'formula', order: 1, latex: 'P(A)=0,4' },
        { type: 'formula', order: 2, latex: 'P(B)=0,5' },
        { type: 'paragraph', order: 3, text: 'y:' },
        { type: 'formula', order: 4, latex: 'P(A\\mid B)=0,6' },
        { type: 'paragraph', order: 5, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 6, latex: 'P(A\\cap B)?' },
        { type: 'paragraph', order: 7, text: 'y qué puede concluirse respecto de la independencia de A y B?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: 'P(A\\cap B)=0,20, \\text{ y son independientes.}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'P(A\\cap B)=0,24, \\text{ y son independientes.}' }, correct: false },
        { content: { type: 'formula', order: 0, latex: 'P(A\\cap B)=0,30, \\text{ y no son independientes.}' }, correct: true },
        { content: { type: 'formula', order: 0, latex: 'P(A\\cap B)=0,30, \\text{ y son independientes.}' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Por definición:' },
        { type: 'formula', order: 1, latex: 'P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}' },
        { type: 'paragraph', order: 2, text: 'Entonces:' },
        { type: 'formula', order: 3, latex: '0,6=\\frac{P(A\\cap B)}{0,5}' },
        { type: 'paragraph', order: 4, text: 'Por lo tanto:' },
        { type: 'formula', order: 5, latex: 'P(A\\cap B)=0,30' },
        { type: 'paragraph', order: 6, text: 'Si fueran independientes:' },
        { type: 'formula', order: 7, latex: 'P(A\\cap B)=P(A)P(B)' },
        { type: 'formula', order: 8, latex: '=0,4\\cdot0,5' },
        { type: 'formula', order: 9, latex: '=0,20' },
        { type: 'paragraph', order: 10, text: 'Como:' },
        { type: 'formula', order: 11, latex: '0,30\\neq0,20' },
        { type: 'paragraph', order: 12, text: 'no son independientes.' },
      ],
    },
  ],
};

export default medidasDispersionProbabilidadCondicional;
