// M2-C1A -- Golden Unit M2 / Números, Recurso 1 (order 1 en U1). Contenido
// editorial APROBADO externamente, transcrito verbatim. Ajustes solo
// técnicos: contentBlocks (heading/paragraph/formula), LaTeX en el campo
// `latex` de bloques `formula`, questionKey sin padding.
//
// Answer key: R1 -- C B B D B A C B B C  ("CBBDBACBBC").
// Dificultad: 2 FACIL / 4 MEDIA / 4 DIFICIL (Q1-Q2 FACIL, Q3-Q6 MEDIA,
// Q7-Q10 DIFICIL).
import type { ResourceContentModule } from '../../schema';

const numerosRealesLogaritmos: ResourceContentModule = {
  kind: 'catalog',
  resourceKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.LECCION',
  resourceType: 'LESSON',
  topicCode: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS',
  unitCode: 'M2.NUMEROS',
  subjectKey: 'matematica',
  order: 1,
  title: 'Números reales y logaritmos',
  learningObjective:
    'Comprender y utilizar propiedades de los números reales, potencias, raíces y logaritmos para representar relaciones numéricas, transformar expresiones y resolver problemas que requieren interpretar equivalencias entre formas exponenciales y logarítmicas.',
  contentBlocks: [
    { type: 'heading', order: 0, level: 1, text: 'Números reales y logaritmos' },

    { type: 'heading', order: 1, level: 2, text: '1. El conjunto de los números reales' },
    {
      type: 'paragraph',
      order: 2,
      text: 'Los números reales, representados por \\mathbb{R}, incluyen todos los números que pueden ubicarse sobre la recta numérica. Dentro de ellos se encuentran distintos conjuntos:',
    },
    { type: 'paragraph', order: 3, text: 'Naturales:' },
    { type: 'formula', order: 4, latex: '1,2,3,\\dots' },
    { type: 'paragraph', order: 5, text: 'Enteros:' },
    { type: 'formula', order: 6, latex: '\\dots,-2,-1,0,1,2,\\dots' },
    { type: 'paragraph', order: 7, text: 'Racionales: números que pueden escribirse como una fracción \\frac{a}{b}, con b\\neq0. Irracionales: números que no pueden expresarse como una fracción de enteros.' },
    { type: 'paragraph', order: 8, text: 'Por ejemplo:' },
    { type: 'formula', order: 9, latex: '\\frac{3}{4},\\;-5,\\;0,125' },
    { type: 'paragraph', order: 10, text: 'son racionales. En cambio:' },
    { type: 'formula', order: 11, latex: '\\sqrt{2},\\;\\pi' },
    { type: 'paragraph', order: 12, text: 'son irracionales. Todos ellos pertenecen a \\mathbb{R}.' },

    { type: 'heading', order: 13, level: 2, text: '2. Representación y comparación de números reales' },
    {
      type: 'paragraph',
      order: 14,
      text: 'Los números reales pueden compararse según su posición en la recta numérica. Si un número se encuentra más a la derecha que otro, entonces es mayor. Para comparar expresiones que contienen raíces puede ser útil utilizar aproximaciones. Por ejemplo:',
    },
    { type: 'formula', order: 15, latex: '\\sqrt{10}\\approx3,16' },
    { type: 'paragraph', order: 16, text: 'por lo que:' },
    { type: 'formula', order: 17, latex: '3<\\sqrt{10}<4' },
    {
      type: 'paragraph',
      order: 18,
      text: 'También puede utilizarse el cuadrado de los números cuando ambos son positivos. Por ejemplo, para comparar \\sqrt{13} y 3,5:',
    },
    { type: 'formula', order: 19, latex: '(\\sqrt{13})^2=13' },
    { type: 'formula', order: 20, latex: '3,5^2=12,25' },
    { type: 'paragraph', order: 21, text: 'Como:' },
    { type: 'formula', order: 22, latex: '13>12,25' },
    { type: 'paragraph', order: 23, text: 'entonces:' },
    { type: 'formula', order: 24, latex: '\\sqrt{13}>3,5' },

    { type: 'heading', order: 25, level: 2, text: '3. Potencias con exponente entero' },
    {
      type: 'paragraph',
      order: 26,
      text: 'Una potencia representa una multiplicación repetida.',
    },
    { type: 'formula', order: 27, latex: 'a^n' },
    {
      type: 'paragraph',
      order: 28,
      text: 'indica que la base a se multiplica por sí misma n veces cuando n es un entero positivo. Algunas propiedades fundamentales son:',
    },
    { type: 'formula', order: 29, latex: 'a^m\\cdot a^n=a^{m+n}' },
    { type: 'formula', order: 30, latex: '\\frac{a^m}{a^n}=a^{m-n}' },
    { type: 'paragraph', order: 31, text: 'para a\\neq0. Además:' },
    { type: 'formula', order: 32, latex: '(a^m)^n=a^{mn}' },
    { type: 'paragraph', order: 33, text: 'y:' },
    { type: 'formula', order: 34, latex: 'a^{-n}=\\frac{1}{a^n}' },
    {
      type: 'paragraph',
      order: 35,
      text: 'para a\\neq0. Estas propiedades permiten transformar expresiones sin calcular necesariamente cada potencia por separado.',
    },

    { type: 'heading', order: 36, level: 2, text: '4. Potencias y raíces' },
    { type: 'paragraph', order: 37, text: 'Las raíces pueden interpretarse mediante exponentes fraccionarios. Por ejemplo:' },
    { type: 'formula', order: 38, latex: '\\sqrt{a}=a^{1/2}' },
    { type: 'paragraph', order: 39, text: 'y:' },
    { type: 'formula', order: 40, latex: '\\sqrt[n]{a}=a^{1/n}' },
    { type: 'paragraph', order: 41, text: 'Por lo tanto:' },
    { type: 'formula', order: 42, latex: '\\sqrt[3]{a^2}=a^{2/3}' },
    {
      type: 'paragraph',
      order: 43,
      text: 'Esta relación permite trabajar con raíces utilizando las mismas propiedades de las potencias. Por ejemplo:',
    },
    { type: 'formula', order: 44, latex: '\\sqrt{x}\\cdot\\sqrt{x}=x' },
    { type: 'paragraph', order: 45, text: 'cuando x\\geq0.' },

    { type: 'heading', order: 46, level: 2, text: '5. ¿Qué es un logaritmo?' },
    {
      type: 'paragraph',
      order: 47,
      text: 'El logaritmo responde una pregunta: ¿A qué exponente debe elevarse una base para obtener determinado número? La expresión:',
    },
    { type: 'formula', order: 48, latex: '\\log_b(a)=c' },
    { type: 'paragraph', order: 49, text: 'significa exactamente que:' },
    { type: 'formula', order: 50, latex: 'b^c=a' },
    { type: 'paragraph', order: 51, text: 'Por ejemplo:' },
    { type: 'formula', order: 52, latex: '\\log_2(8)=3' },
    { type: 'paragraph', order: 53, text: 'porque:' },
    { type: 'formula', order: 54, latex: '2^3=8' },
    { type: 'paragraph', order: 55, text: 'La base debe cumplir:' },
    { type: 'formula', order: 56, latex: 'b>0,\\qquad b\\neq1' },
    { type: 'paragraph', order: 57, text: 'y el argumento del logaritmo debe ser positivo.' },

    { type: 'heading', order: 58, level: 2, text: '6. Forma exponencial y forma logarítmica' },
    { type: 'paragraph', order: 59, text: 'Toda igualdad exponencial apropiada puede escribirse en forma logarítmica. Por ejemplo:' },
    { type: 'formula', order: 60, latex: '5^3=125' },
    { type: 'paragraph', order: 61, text: 'equivale a:' },
    { type: 'formula', order: 62, latex: '\\log_5(125)=3' },
    { type: 'paragraph', order: 63, text: 'Otro ejemplo:' },
    { type: 'formula', order: 64, latex: '10^{-2}=0,01' },
    { type: 'paragraph', order: 65, text: 'equivale a:' },
    { type: 'formula', order: 66, latex: '\\log_{10}(0,01)=-2' },
    {
      type: 'paragraph',
      order: 67,
      text: 'Reconocer esta equivalencia es fundamental para resolver ecuaciones en las que la incógnita aparece como exponente.',
    },

    { type: 'heading', order: 68, level: 2, text: '7. Propiedad del producto' },
    { type: 'paragraph', order: 69, text: 'Para valores positivos de x e y:' },
    { type: 'formula', order: 70, latex: '\\log_b(xy)=\\log_b(x)+\\log_b(y)' },
    { type: 'paragraph', order: 71, text: 'Por ejemplo:' },
    { type: 'formula', order: 72, latex: '\\log_{10}(1000)' },
    { type: 'paragraph', order: 73, text: 'puede pensarse como:' },
    { type: 'formula', order: 74, latex: '\\log_{10}(10\\cdot100)' },
    { type: 'paragraph', order: 75, text: 'Entonces:' },
    { type: 'formula', order: 76, latex: '\\log_{10}(10)+\\log_{10}(100)=1+2=3' },
    { type: 'paragraph', order: 77, text: 'Por eso:' },
    { type: 'formula', order: 78, latex: '\\log_{10}(1000)=3' },

    { type: 'heading', order: 79, level: 2, text: '8. Propiedad del cociente' },
    { type: 'paragraph', order: 80, text: 'Para x>0 e y>0:' },
    { type: 'formula', order: 81, latex: '\\log_b\\left(\\frac{x}{y}\\right)=\\log_b(x)-\\log_b(y)' },
    { type: 'paragraph', order: 82, text: 'Por ejemplo:' },
    { type: 'formula', order: 83, latex: '\\log_2\\left(\\frac{32}{4}\\right)=\\log_2(32)-\\log_2(4)=5-2=3' },
    { type: 'paragraph', order: 84, text: 'lo que coincide con:' },
    { type: 'formula', order: 85, latex: '\\log_2(8)=3' },

    { type: 'heading', order: 86, level: 2, text: '9. Propiedad de la potencia' },
    { type: 'paragraph', order: 87, text: 'Si x>0:' },
    { type: 'formula', order: 88, latex: '\\log_b(x^k)=k\\log_b(x)' },
    { type: 'paragraph', order: 89, text: 'Por ejemplo:' },
    { type: 'formula', order: 90, latex: '\\log_3(81^2)' },
    { type: 'paragraph', order: 91, text: 'Como:' },
    { type: 'formula', order: 92, latex: '81=3^4' },
    { type: 'paragraph', order: 93, text: 'entonces:' },
    { type: 'formula', order: 94, latex: '\\log_3(81^2)=2\\log_3(81)=2\\cdot4=8' },
    { type: 'paragraph', order: 95, text: 'Esta propiedad es especialmente útil cuando el argumento contiene exponentes.' },

    { type: 'heading', order: 96, level: 2, text: '10. Ecuaciones exponenciales y logarítmicas' },
    { type: 'paragraph', order: 97, text: 'La relación entre exponentes y logaritmos permite encontrar incógnitas. Por ejemplo:' },
    { type: 'formula', order: 98, latex: '2^x=32' },
    { type: 'paragraph', order: 99, text: 'Como:' },
    { type: 'formula', order: 100, latex: '32=2^5' },
    { type: 'paragraph', order: 101, text: 'se obtiene:' },
    { type: 'formula', order: 102, latex: 'x=5' },
    { type: 'paragraph', order: 103, text: 'Pero si no es sencillo expresar ambos lados con la misma base:' },
    { type: 'formula', order: 104, latex: '3^x=20' },
    { type: 'paragraph', order: 105, text: 'puede escribirse:' },
    { type: 'formula', order: 106, latex: 'x=\\log_3(20)' },
    {
      type: 'paragraph',
      order: 107,
      text: 'Los logaritmos permiten, por lo tanto, representar exponentes que no necesariamente son enteros.',
    },

    { type: 'heading', order: 108, level: 3, text: 'Situación ZETRYND 1 — Escala de almacenamiento' },
    {
      type: 'paragraph',
      order: 109,
      text: 'Un sistema almacena información utilizando niveles cuya capacidad se duplica de un nivel al siguiente. La capacidad del nivel n, medida en unidades de información, puede representarse mediante:',
    },
    { type: 'formula', order: 110, latex: 'C=2^n' },
    { type: 'paragraph', order: 111, text: 'Un dispositivo determinado puede almacenar 1024 unidades. Como:' },
    { type: 'formula', order: 112, latex: '1024=2^{10}' },
    { type: 'paragraph', order: 113, text: 'el dispositivo corresponde al nivel:' },
    { type: 'formula', order: 114, latex: 'n=10' },
    { type: 'paragraph', order: 115, text: 'La misma relación puede escribirse como:' },
    { type: 'formula', order: 116, latex: '\\log_2(1024)=10' },
    {
      type: 'paragraph',
      order: 117,
      text: 'Si otro dispositivo almacena una cantidad que no corresponde exactamente a una potencia entera de 2, el logaritmo permite describir igualmente su posición dentro de esta escala.',
    },

    { type: 'heading', order: 118, level: 3, text: 'Situación ZETRYND 2 — Comparación de magnitudes' },
    { type: 'paragraph', order: 119, text: 'Dos mediciones positivas A y B están relacionadas por:' },
    { type: 'formula', order: 120, latex: 'A=10^4' },
    { type: 'paragraph', order: 121, text: 'y:' },
    { type: 'formula', order: 122, latex: 'B=10^2' },
    { type: 'paragraph', order: 123, text: 'Entonces:' },
    { type: 'formula', order: 124, latex: '\\frac{A}{B}=\\frac{10^4}{10^2}=10^2=100' },
    { type: 'paragraph', order: 125, text: 'Esto significa que A es cien veces B. Utilizando logaritmos:' },
    { type: 'formula', order: 126, latex: '\\log_{10}(A)-\\log_{10}(B)=4-2=2' },
    {
      type: 'paragraph',
      order: 127,
      text: 'La diferencia entre los logaritmos representa la diferencia entre los exponentes de las potencias de 10.',
    },
  ],
  questions: [
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q1',
      order: 0,
      difficulty: 'FACIL',
      stemContent: [{ type: 'paragraph', order: 0, text: '¿Cuál de los siguientes números es irracional?' }],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\frac{7}{8}' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '0,125' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\sqrt{5}' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '-4' }, correct: false },
      ],
      explanationContent: [
        {
          type: 'paragraph',
          order: 0,
          text: '\\sqrt{5} no puede expresarse como una fracción entre dos enteros, por lo que es irracional. Las otras alternativas corresponden a números racionales.',
        },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q2',
      order: 1,
      difficulty: 'FACIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Si:' },
        { type: 'formula', order: 1, latex: '2^5=32' },
        { type: 'paragraph', order: 2, text: '¿qué igualdad logarítmica representa exactamente la misma relación?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\log_5(32)=2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\log_2(32)=5' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '\\log_{32}(5)=2' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\log_2(5)=32' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La equivalencia general es:' },
        { type: 'formula', order: 1, latex: 'b^c=a \\iff \\log_b(a)=c' },
        { type: 'paragraph', order: 2, text: 'Por eso, 2^5=32 equivale a \\log_2(32)=5.' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q3',
      order: 2,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 1, latex: '\\frac{3^7\\cdot3^{-2}}{3^3}?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '3' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '27' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '81' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Primero se suman los exponentes del numerador:' },
        { type: 'formula', order: 1, latex: '3^7\\cdot3^{-2}=3^5' },
        { type: 'paragraph', order: 2, text: 'Luego:' },
        { type: 'formula', order: 3, latex: '\\frac{3^5}{3^3}=3^2=9' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q4',
      order: 3,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Si:' },
        { type: 'formula', order: 1, latex: '\\log_2(x)=6' },
        { type: 'paragraph', order: 2, text: '¿cuál es el valor de x?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '12' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '32' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '36' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '64' }, correct: true },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'La igualdad:' },
        { type: 'formula', order: 1, latex: '\\log_2(x)=6' },
        { type: 'paragraph', order: 2, text: 'equivale a:' },
        { type: 'formula', order: 3, latex: '2^6=x' },
        { type: 'paragraph', order: 4, text: 'Por lo tanto:' },
        { type: 'formula', order: 5, latex: 'x=64' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q5',
      order: 4,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Si:' },
        { type: 'formula', order: 1, latex: '\\log_3(a)=4' },
        { type: 'paragraph', order: 2, text: '¿cuál es el valor de:' },
        { type: 'formula', order: 3, latex: '\\log_3(a^2)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '12' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '16' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Por la propiedad de la potencia:' },
        { type: 'formula', order: 1, latex: '\\log_3(a^2)=2\\log_3(a)' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\log_3(a)=4' },
        { type: 'paragraph', order: 4, text: 'entonces:' },
        { type: 'formula', order: 5, latex: '2\\cdot4=8' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q6',
      order: 5,
      difficulty: 'MEDIA',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se sabe que:' },
        { type: 'formula', order: 1, latex: '\\log_{10}(x)=3' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: '\\log_{10}(y)=1' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 5, latex: '\\log_{10}\\left(\\frac{x}{y}\\right)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '2' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '3' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '30' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Aplicando la propiedad del cociente:' },
        { type: 'formula', order: 1, latex: '\\log_{10}\\left(\\frac{x}{y}\\right)=\\log_{10}(x)-\\log_{10}(y)=3-1=2' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q7',
      order: 6,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sean a>0 y b>0. Se sabe que:' },
        { type: 'formula', order: 1, latex: '\\log_2(a)=3' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: '\\log_2(b)=5' },
        { type: 'paragraph', order: 4, text: '¿Cuál es el valor de:' },
        { type: 'formula', order: 5, latex: '\\log_2\\left(\\frac{a^2b}{4}\\right)?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '7' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '8' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '11' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Aplicamos las propiedades de los logaritmos:' },
        {
          type: 'formula',
          order: 1,
          latex: '\\log_2\\left(\\frac{a^2b}{4}\\right)=\\log_2(a^2)+\\log_2(b)-\\log_2(4)=2\\log_2(a)+\\log_2(b)-2=2(3)+5-2=9',
        },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q8',
      order: 7,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Un número positivo x cumple:' },
        { type: 'formula', order: 1, latex: '\\log_3(x)+\\log_3(9)=5' },
        { type: 'paragraph', order: 2, text: '¿Cuál es el valor de x?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '9' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '27' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '81' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '243' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Como:' },
        { type: 'formula', order: 1, latex: '\\log_3(9)=2' },
        { type: 'paragraph', order: 2, text: 'la ecuación queda:' },
        { type: 'formula', order: 3, latex: '\\log_3(x)+2=5' },
        { type: 'paragraph', order: 4, text: 'Entonces:' },
        { type: 'formula', order: 5, latex: '\\log_3(x)=3' },
        { type: 'paragraph', order: 6, text: 'y por equivalencia exponencial:' },
        { type: 'formula', order: 7, latex: 'x=3^3=27' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q9',
      order: 8,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Se sabe que:' },
        { type: 'formula', order: 1, latex: '4^x=8^{x-1}' },
        { type: 'paragraph', order: 2, text: '¿Cuál es el valor de x?' },
      ],
      options: [
        { content: { type: 'paragraph', order: 0, text: '2' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '3' }, correct: true },
        { content: { type: 'paragraph', order: 0, text: '4' }, correct: false },
        { content: { type: 'paragraph', order: 0, text: '6' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Escribimos ambas potencias utilizando base 2:' },
        { type: 'formula', order: 1, latex: '4^x=(2^2)^x=2^{2x}' },
        { type: 'paragraph', order: 2, text: 'y:' },
        { type: 'formula', order: 3, latex: '8^{x-1}=(2^3)^{x-1}=2^{3x-3}' },
        { type: 'paragraph', order: 4, text: 'Como las bases son iguales:' },
        { type: 'formula', order: 5, latex: '2x=3x-3' },
        { type: 'paragraph', order: 6, text: 'por lo que:' },
        { type: 'formula', order: 7, latex: 'x=3' },
      ],
    },
    {
      questionKey: 'M2.NUMEROS.NUMEROS_REALES_LOGARITMOS.Q10',
      order: 9,
      difficulty: 'DIFICIL',
      stemContent: [
        { type: 'paragraph', order: 0, text: 'Sean a>0 y b>0, con b\\neq1. Se sabe que:' },
        { type: 'formula', order: 1, latex: '\\log_b(a)=2' },
        { type: 'paragraph', order: 2, text: '¿Cuál de las siguientes expresiones es necesariamente igual a 4?' },
      ],
      options: [
        { content: { type: 'formula', order: 0, latex: '\\log_b(2a)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\log_b(a+2)' }, correct: false },
        { content: { type: 'formula', order: 0, latex: '\\log_b(a^2)' }, correct: true },
        { content: { type: 'formula', order: 0, latex: '(\\log_{b^2}(a))^2' }, correct: false },
      ],
      explanationContent: [
        { type: 'paragraph', order: 0, text: 'Aplicando la propiedad de la potencia:' },
        { type: 'formula', order: 1, latex: '\\log_b(a^2)=2\\log_b(a)' },
        { type: 'paragraph', order: 2, text: 'Como:' },
        { type: 'formula', order: 3, latex: '\\log_b(a)=2' },
        { type: 'paragraph', order: 4, text: 'se obtiene:' },
        { type: 'formula', order: 5, latex: '\\log_b(a^2)=2\\cdot2=4' },
        { type: 'paragraph', order: 6, text: 'Las demás expresiones no tienen necesariamente ese valor.' },
      ],
    },
  ],
};

export default numerosRealesLogaritmos;
