// ENSAYOS-M1-A -- SOURCE del primer Ensayo PAES M1 ZETRYND.
// Contenido editorial APPROVED FOR IMPLEMENTATION, transcrito VERBATIM:
//   - Enunciados + alternativas + respuesta correcta: paquete "ENSAYOS-M1-A"
//     (65 preguntas, "versión editorial final verde").
//   - Explicaciones (visibles solo en revisión): paquete "Explicaciones
//     Q1-Q65 APPROVED".
//   - axis / difficulty / primarySkill por pregunta: paquete "Clasificación
//     editorial Q1-Q65 APPROVED".
//
// Únicas adaptaciones aplicadas -- puramente técnicas, contenido visible
// idéntico (ADR-0024 / ENSAYOS-M1-A §15):
//   - `$$...$$` de la fuente -> bloque `formula` con el LaTeX interior.
//   - `\(x\)` / `\(C(x)\)` / `\(12\)` inline en prosa -> texto plano (visualmente
//     idéntico al render del LaTeX).
//   - Tablas -> filas en párrafos, sin pérdida de ningún valor (regla de
//     tablas del proyecto: representación lossless, FORMAT_ONLY).
//   - En las explicaciones, el artefacto markdown de "render + LaTeX crudo"
//     duplicados (p. ej. `50.000⋅0,8=40.00050.000\cdot0,8=40.000`) se
//     reconstruye como [texto][formula]: el contenido visible -- una sola
//     fórmula -- es idéntico.
//
// Cero cambios de cifras, fórmulas, alternativas, respuesta correcta,
// procedimiento ni estilo. Este archivo NO se importa a DB (eso es
// ENSAYOS-M1-B) y NO forma parte del `CONTENT_MANIFEST` de Study.
import type { ExamSourceModule, ExamSourceQuestion, ExamSourceOption } from '../schema';

type Block = { type: 'paragraph'; text: string } | { type: 'formula'; latex: string };
const p = (text: string): Block => ({ type: 'paragraph', text });
const f = (latex: string): Block => ({ type: 'formula', latex });
const withOrder = (blocks: Block[]) => blocks.map((b, order) => ({ ...b, order }));

const tOpt = (text: string, correct: boolean): ExamSourceOption => ({ content: { type: 'paragraph', order: 0, text }, correct });
const fOpt = (latex: string, correct: boolean): ExamSourceOption => ({ content: { type: 'formula', order: 0, latex }, correct });

const q = (
  n: number,
  axis: ExamSourceQuestion['axis'],
  difficulty: ExamSourceQuestion['difficulty'],
  primarySkill: ExamSourceQuestion['primarySkill'],
  stem: Block[],
  options: ExamSourceOption[],
  explanation: Block[],
): ExamSourceQuestion => ({
  questionKey: `ENSAYO.M1.Q${n}`,
  displayOrder: n,
  axis,
  difficulty,
  primarySkill,
  stemContent: withOrder(stem),
  options,
  explanationContent: withOrder(explanation),
});

const questions: ExamSourceQuestion[] = [
  q(
    1,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una chaqueta tiene un precio original de $50.000. Durante una promoción se aplica primero un descuento del 20% y luego un descuento adicional del 10% sobre el precio ya rebajado.'),
      p('¿Cuál es el precio final de la chaqueta?'),
    ],
    [tOpt('$35.000', false), tOpt('$36.000', true), tOpt('$38.000', false), tOpt('$40.000', false)],
    [
      p('Los descuentos se aplican de manera sucesiva.'),
      p('Primero:'),
      f('50.000\\cdot0,8=40.000'),
      p('Luego:'),
      f('40.000\\cdot0,9=36.000'),
      p('Por lo tanto, el precio final es $36.000.'),
    ],
  ),
  q(
    2,
    'ALGEBRA_FUNCIONES',
    'FACIL',
    'REPRESENTAR',
    [
      p('Una empresa de transporte cobra una tarifa fija de $1.200 más $350 por cada kilómetro recorrido.'),
      p('Si x representa la cantidad de kilómetros y C(x) el costo total, ¿qué expresión representa correctamente esta situación?'),
    ],
    [fOpt('C(x)=1.200x+350', false), fOpt('C(x)=1.550x', false), fOpt('C(x)=350x+1.200', true), fOpt('C(x)=350(x+1.200)', false)],
    [
      p('El costo tiene una parte fija de $1.200 y otra que depende de los kilómetros recorridos.'),
      p('Por cada kilómetro se agregan $350, por lo que:'),
      f('C(x)=350x+1.200'),
    ],
  ),
  q(
    3,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Un patio rectangular mide 12 m de largo y 8 m de ancho. En una de sus esquinas se construye una zona cuadrada de 3 m de lado que no será cubierta con pasto.'),
      p('¿Cuántos metros cuadrados de pasto se necesitan para cubrir el resto del patio?'),
    ],
    [fOpt('87\\text{ m}^2', true), fOpt('81\\text{ m}^2', false), fOpt('93\\text{ m}^2', false), fOpt('96\\text{ m}^2', false)],
    [
      p('El área total del patio es:'),
      f('12\\cdot8=96'),
      p('La zona cuadrada ocupa:'),
      f('3^2=9'),
      p('Entonces el área que debe cubrirse con pasto es:'),
      f('96-9=87\\text{ m}^2'),
    ],
  ),
  q(
    4,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'REPRESENTAR',
    [
      p('Los tiempos, en minutos, que cinco estudiantes tardaron en completar una actividad fueron:'),
      f('18,\\;12,\\;15,\\;20,\\;15'),
      p('¿Cuál es la mediana de estos datos?'),
    ],
    [fOpt('12', false), fOpt('15', true), fOpt('16', false), fOpt('18', false)],
    [
      p('Primero se ordenan los datos:'),
      f('12,\\;15,\\;15,\\;18,\\;20'),
      p('Como existen cinco valores, la mediana corresponde al valor central:'),
      f('15'),
    ],
  ),
  q(
    5,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se consideran las funciones:'),
      f('f(x)=2x+3'),
      p('y:'),
      f('g(x)=kx-1'),
      p('Sus gráficos se intersectan en un punto cuya coordenada x es 4.'),
      p('¿Cuál afirmación es correcta?'),
    ],
    [
      tOpt('k=2, y ambas funciones tienen la misma pendiente.', false),
      tOpt('k=3, y para todo x<4 se cumple g(x)>f(x).', false),
      tOpt('k=3, y para todo x>4 se cumple g(x)>f(x).', true),
      tOpt('k=4, y para todo x>4 se cumple f(x)>g(x).', false),
    ],
    [
      p('Como los gráficos se intersectan cuando x=4:'),
      f('f(4)=2(4)+3=11'),
      p('Entonces:'),
      f('g(4)=4k-1=11'),
      p('De aquí:'),
      f('4k=12'),
      f('k=3'),
      p('La pendiente de g es 3, mayor que la pendiente 2 de f. Después del punto de intersección, es decir para x>4, se cumple:'),
      f('g(x)>f(x)'),
    ],
  ),
  q(
    6,
    'NUMEROS',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Para preparar una mezcla se utilizan 3 partes de agua por cada 2 partes de concentrado.'),
      p('Si se utilizan 12 litros de agua, ¿cuántos litros de concentrado se necesitan?'),
    ],
    [fOpt('8', true), fOpt('6', false), fOpt('10', false), fOpt('18', false)],
    [
      p('La razón agua : concentrado es:'),
      f('3:2'),
      p('Si 3 partes corresponden a 12 litros, una parte corresponde a:'),
      f('12\\div3=4'),
      p('El concentrado representa 2 partes:'),
      f('2\\cdot4=8'),
      p('Se necesitan 8 litros.'),
    ],
  ),
  q(
    7,
    'GEOMETRIA',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Un terreno rectangular tiene un perímetro de 68 m y una diagonal de 26 m.'),
      p('¿Cuál es el área del terreno?'),
    ],
    [fOpt('204\\text{ m}^2', false), fOpt('220\\text{ m}^2', false), fOpt('240\\text{ m}^2', true), fOpt('260\\text{ m}^2', false)],
    [
      p('Si los lados del rectángulo son a y b, del perímetro se obtiene:'),
      f('a+b=34'),
      p('Además, por Pitágoras:'),
      f('a^2+b^2=26^2=676'),
      p('Usando:'),
      f('(a+b)^2=a^2+b^2+2ab'),
      p('se tiene:'),
      f('34^2=676+2ab'),
      f('1156=676+2ab'),
      f('2ab=480'),
      f('ab=240'),
      p('Por lo tanto, el área es:'),
      f('240\\text{ m}^2'),
    ],
  ),
  q(
    8,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'MODELAR',
    [
      p('En una función de cine se vendieron 120 entradas entre adultos y estudiantes.'),
      p('La entrada de adulto costaba $6.000 y la de estudiante $4.000. La recaudación total fue de $560.000.'),
      p('¿Cuántas entradas de adulto se vendieron?'),
    ],
    [tOpt('30', false), tOpt('40', true), tOpt('50', false), tOpt('60', false)],
    [
      p('Sea a la cantidad de entradas de adulto. Entonces las entradas de estudiante son:'),
      f('120-a'),
      p('La recaudación cumple:'),
      f('6000a+4000(120-a)=560000'),
      p('Resolviendo:'),
      f('2000a=80000'),
      f('a=40'),
    ],
  ),
  q(
    9,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('En una caja hay:'),
      p('5 fichas rojas;'),
      p('3 fichas azules;'),
      p('2 fichas verdes.'),
      p('Se extrae una ficha al azar.'),
      p('¿Cuál es la probabilidad de que la ficha extraída no sea roja?'),
    ],
    [fOpt('\\frac15', false), fOpt('\\frac3{10}', false), fOpt('\\frac7{10}', false), fOpt('\\frac12', true)],
    [
      p('Hay:'),
      f('5+3+2=10'),
      p('fichas en total.'),
      p('Las fichas que no son rojas son las azules y verdes:'),
      f('3+2=5'),
      p('Entonces:'),
      f('P(\\text{no roja})=\\frac5{10}=\\frac12'),
    ],
  ),
  q(
    10,
    'NUMEROS',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Sean a y b números positivos tales que:'),
      f('\\frac{a}{b}=\\frac32'),
      p('y:'),
      f('a^2-b^2=20'),
      p('¿Cuál es el valor de:'),
      f('a+b'),
      p('?'),
    ],
    [fOpt('8', false), fOpt('10', true), fOpt('12', false), fOpt('20', false)],
    [
      p('Como:'),
      f('\\frac ab=\\frac32'),
      p('podemos escribir:'),
      f('a=3t,\\qquad b=2t'),
      p('Entonces:'),
      f('a^2-b^2=9t^2-4t^2=5t^2'),
      p('Como esta diferencia vale 20:'),
      f('5t^2=20'),
      f('t=2'),
      p('porque a y b son positivos.'),
      p('Así:'),
      f('a+b=6+4=10'),
    ],
  ),
  q(
    11,
    'ALGEBRA_FUNCIONES',
    'FACIL',
    'REPRESENTAR',
    [
      p('Una función lineal está representada parcialmente en la siguiente tabla:'),
      p('x = 0, f(x) = 3'),
      p('x = 1, f(x) = 5'),
      p('x = 2, f(x) = 7'),
      p('x = 3, f(x) = 9'),
      p('¿Cuál expresión representa la función?'),
    ],
    [fOpt('f(x)=2x+3', true), fOpt('f(x)=3x+2', false), fOpt('f(x)=2x+1', false), fOpt('f(x)=3x', false)],
    [
      p('Cada vez que x aumenta en 1, el valor de f(x) aumenta en 2, por lo que la pendiente es 2.'),
      p('Además:'),
      f('f(0)=3'),
      p('Entonces:'),
      f('f(x)=2x+3'),
    ],
  ),
  q(
    12,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('El promedio de cuatro notas es 5,5.'),
      p('Si tres de ellas son:'),
      f('5,0,\\quad6,0,\\quad4,5'),
      p('¿cuál es la cuarta nota?'),
    ],
    [fOpt('5,5', false), fOpt('6,0', false), fOpt('7,0', false), fOpt('6,5', true)],
    [
      p('Si el promedio de cuatro notas es 5,5, la suma total es:'),
      f('4\\cdot5,5=22'),
      p('Las tres notas conocidas suman:'),
      f('5+6+4,5=15,5'),
      p('La cuarta nota es:'),
      f('22-15,5=6,5'),
    ],
  ),
  q(
    13,
    'GEOMETRIA',
    'MEDIA',
    'ARGUMENTAR',
    [
      p('En el plano cartesiano, el punto:'),
      f('P=(4,-2)'),
      p('se refleja respecto del eje y.'),
      p('¿Cuál es la imagen de P?'),
    ],
    [fOpt('(-4,-2)', true), fOpt('(4,2)', false), fOpt('(-4,2)', false), fOpt('(2,-4)', false)],
    [
      p('Una reflexión respecto del eje y cambia el signo de la coordenada x y mantiene la coordenada y.'),
      p('Por lo tanto:'),
      f('(4,-2)\\rightarrow(-4,-2)'),
    ],
  ),
  q(
    14,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'MODELAR',
    [
      p('La altura h, en metros, de una pelota después de t segundos está dada por:'),
      f('h(t)=-5t^2+20t+1'),
      p('¿En qué instante alcanza su altura máxima?'),
    ],
    [tOpt('1 s', false), tOpt('4 s', false), tOpt('2 s', true), tOpt('5 s', false)],
    [
      p('El instante correspondiente al vértice de una función cuadrática:'),
      f('at^2+bt+c'),
      p('se obtiene mediante:'),
      f('t=-\\frac{b}{2a}'),
      p('Aquí:'),
      f('a=-5,\\qquad b=20'),
      p('Entonces:'),
      f('t=-\\frac{20}{2(-5)}=2'),
      p('La altura máxima ocurre a los 2 segundos.'),
    ],
  ),
  q(
    15,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una cafetería permite elegir un desayuno combinando:'),
      p('3 tipos de pan;'),
      p('4 tipos de relleno;'),
      p('2 bebidas.'),
      p('Si se debe elegir exactamente una opción de cada categoría, ¿cuántos desayunos distintos pueden formarse?'),
    ],
    [tOpt('18', false), tOpt('24', true), tOpt('12', false), tOpt('9', false)],
    [
      p('Se aplica el principio multiplicativo.'),
      p('Existen 3 opciones de pan, 4 opciones de relleno y 2 bebidas.'),
      p('Por lo tanto:'),
      f('3\\cdot4\\cdot2=24'),
    ],
  ),
  q(
    16,
    'NUMEROS',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [p('¿Cuál es el valor de:'), f('\\frac{2^3\\cdot2^4}{2^2}'), p('?')],
    [tOpt('8', false), tOpt('16', false), tOpt('32', true), tOpt('64', false)],
    [
      p('Al multiplicar potencias de igual base se suman exponentes y al dividir se restan:'),
      f('\\frac{2^3\\cdot2^4}{2^2}=2^{3+4-2}=2^5=32'),
    ],
  ),
  q(
    17,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'REPRESENTAR',
    [
      p('Una función afín pasa por los puntos:'),
      f('(1,5)'),
      p('y:'),
      f('(3,9)'),
      p('¿Cuál de las siguientes expresiones representa esta función?'),
    ],
    [fOpt('f(x)=2x+3', true), fOpt('f(x)=3x+2', false), fOpt('f(x)=2x+5', false), fOpt('f(x)=4x+1', false)],
    [
      p('La pendiente entre los puntos es:'),
      f('m=\\frac{9-5}{3-1}=2'),
      p('Entonces:'),
      f('f(x)=2x+b'),
      p('Usando el punto (1,5):'),
      f('5=2(1)+b'),
      f('b=3'),
      p('Por lo tanto:'),
      f('f(x)=2x+3'),
    ],
  ),
  q(
    18,
    'GEOMETRIA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [p('Un rectángulo mide 7 cm de largo y 4 cm de ancho.'), p('¿Cuál es su perímetro?')],
    [tOpt('11 cm', false), tOpt('14 cm', false), tOpt('28 cm', false), tOpt('22 cm', true)],
    [
      p('El perímetro de un rectángulo es:'),
      f('P=2(largo+ancho)'),
      p('Entonces:'),
      f('P=2(7+4)=22\\text{ cm}'),
    ],
  ),
  q(
    19,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('Cinco mediciones tienen un promedio de 12.'),
      p('Si se agrega una sexta medición cuyo valor es 18, ¿cuál es el nuevo promedio?'),
    ],
    [tOpt('12,5', false), tOpt('13', true), tOpt('14', false), tOpt('15', false)],
    [
      p('Las cinco mediciones iniciales suman:'),
      f('5\\cdot12=60'),
      p('Al agregar 18:'),
      f('60+18=78'),
      p('Ahora existen seis mediciones:'),
      f('\\frac{78}{6}=13'),
    ],
  ),
  q(
    20,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'ARGUMENTAR',
    [p('¿Qué conjunto de valores satisface la inecuación:'), f('3x-4>8'), p('?')],
    [fOpt('x<4', false), fOpt('x\\geq4', false), fOpt('x>4', true), fOpt('x\\leq4', false)],
    [
      p('Se resuelve la inecuación:'),
      f('3x-4>8'),
      p('Sumando 4:'),
      f('3x>12'),
      p('Dividiendo por 3:'),
      f('x>4'),
    ],
  ),
  q(
    21,
    'GEOMETRIA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una caja tiene forma de prisma rectangular y sus dimensiones interiores son:'),
      f('5\\text{ cm},\\quad3\\text{ cm},\\quad4\\text{ cm}'),
      p('¿Cuál es su volumen?'),
    ],
    [fOpt('60\\text{ cm}^3', true), fOpt('24\\text{ cm}^3', false), fOpt('40\\text{ cm}^3', false), fOpt('120\\text{ cm}^3', false)],
    [
      p('El volumen de un prisma rectangular es el producto de sus tres dimensiones:'),
      f('V=5\\cdot3\\cdot4'),
      f('V=60\\text{ cm}^3'),
    ],
  ),
  q(
    22,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'MODELAR',
    [
      p('En una actividad hay 8 tarjetas idénticas por fuera. De ellas, 3 contienen un premio.'),
      p('Si una persona elige una tarjeta al azar, ¿cuál es la probabilidad de obtener un premio?'),
    ],
    [fOpt('\\frac13', false), fOpt('\\frac38', true), fOpt('\\frac58', false), fOpt('\\frac35', false)],
    [
      p('Existen 8 tarjetas en total y 3 contienen premio.'),
      p('Por lo tanto:'),
      f('P(\\text{premio})=\\frac38'),
    ],
  ),
  q(
    23,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [p('¿Cuál es el resultado de:'), f('-\\frac34+\\frac56'), p('?')],
    [fOpt('-\\frac{19}{12}', false), fOpt('-\\frac1{12}', false), fOpt('\\frac7{12}', false), fOpt('\\frac1{12}', true)],
    [
      p('Se utiliza denominador común 12:'),
      f('-\\frac34=-\\frac9{12}'),
      p('y:'),
      f('\\frac56=\\frac{10}{12}'),
      p('Entonces:'),
      f('-\\frac9{12}+\\frac{10}{12} = \\frac1{12}'),
    ],
  ),
  q(
    24,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('La parábola asociada a:'),
      f('f(x)=x^2-6x+k'),
      p('intersecta al eje x en dos puntos distintos cuyas coordenadas x difieren en 4 unidades.'),
      p('¿Cuál es el valor de k?'),
    ],
    [tOpt('4', false), tOpt('5', true), tOpt('8', false), tOpt('9', false)],
    [
      p('Si las raíces difieren en 4 y su suma es 6, pueden representarse como:'),
      f('r'),
      p('y:'),
      f('r+4'),
      p('Entonces:'),
      f('r+(r+4)=6'),
      f('2r=2'),
      f('r=1'),
      p('Las raíces son 1 y 5.'),
      p('Su producto corresponde a k:'),
      f('k=1\\cdot5=5'),
    ],
  ),
  q(
    25,
    'GEOMETRIA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('El punto:'),
      f('P=(4,-1)'),
      p('se traslada mediante el vector:'),
      f('(-2,5)'),
      p('¿Cuáles son las coordenadas de la imagen de P?'),
    ],
    [fOpt('(6,4)', false), fOpt('(2,4)', true), fOpt('(2,-6)', false), fOpt('(-2,5)', false)],
    [
      p('Una traslación suma el vector a las coordenadas originales:'),
      f('(4,-1)+(-2,5)=(2,4)'),
    ],
  ),
  q(
    26,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'ARGUMENTAR',
    [
      p('Se registraron los siguientes valores:'),
      f('10,\\;10,\\;12,\\;12,\\;12,\\;14,\\;16'),
      p('¿Cuál de las siguientes afirmaciones es correcta?'),
    ],
    [
      tOpt('La moda es 12.', true),
      tOpt('La moda es 10.', false),
      tOpt('La mediana es 10.', false),
      tOpt('El rango es 4.', false),
    ],
    [
      p('La moda es el valor que aparece con mayor frecuencia.'),
      p('En el conjunto:'),
      f('10,\\;10,\\;12,\\;12,\\;12,\\;14,\\;16'),
      p('el número 12 aparece tres veces.'),
      p('Por lo tanto, la moda es:'),
      f('12'),
    ],
  ),
  q(
    27,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('En una función se vendieron 120 entradas entre adultos y estudiantes.'),
      p('La entrada de adulto cuesta $6.000 y la de estudiante $4.000.'),
      p('Además, exactamente el 25% de las entradas de adulto se vendió con un descuento de $2.000 cada una.'),
      p('Si la recaudación total fue de $540.000, ¿cuántas entradas de adulto se vendieron?'),
    ],
    [tOpt('30', false), tOpt('40', true), tOpt('50', false), tOpt('60', false)],
    [
      p('Sea a la cantidad de entradas de adulto.'),
      p('Un 25% de ellas cuesta $4.000 después del descuento, mientras que el 75% restante cuesta $6.000.'),
      p('El ingreso promedio por entrada de adulto es:'),
      f('0,25(4000)+0,75(6000)=5500'),
      p('Las entradas de estudiantes son:'),
      f('120-a'),
      p('Entonces:'),
      f('5500a+4000(120-a)=540000'),
      f('1500a=60000'),
      f('a=40'),
    ],
  ),
  q(
    28,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Después de aumentar su precio en un 25%, un producto cuesta $30.000.'),
      p('¿Cuál era su precio antes del aumento?'),
    ],
    [tOpt('$22.500', false), tOpt('$23.000', false), tOpt('$24.000', true), tOpt('$25.000', false)],
    [
      p('Si P representa el precio original, después de aumentar un 25%:'),
      f('1,25P=30000'),
      p('Por lo tanto:'),
      f('P=\\frac{30000}{1,25}'),
      f('P=24000'),
    ],
  ),
  q(
    29,
    'GEOMETRIA',
    'DIFICIL',
    'MODELAR',
    [
      p('Un terreno rectangular tiene un área de:'),
      f('96\\text{ m}^2'),
      p('y su largo mide 4 m más que su ancho.'),
      p('¿Cuál es la distancia desde el centro del terreno hasta uno de sus vértices?'),
    ],
    [
      fOpt('2\\sqrt{13}\\text{ m}', true),
      fOpt('4\\sqrt{13}\\text{ m}', false),
      fOpt('2\\sqrt{26}\\text{ m}', false),
      fOpt('4\\sqrt{26}\\text{ m}', false),
    ],
    [
      p('Sea x el ancho del terreno. El largo es:'),
      f('x+4'),
      p('Como el área es 96:'),
      f('x(x+4)=96'),
      p('La solución positiva es:'),
      f('x=8'),
      p('por lo que el largo es 12.'),
      p('La distancia desde el centro hasta un vértice corresponde a la mitad de cada dimensión:'),
      f('4\\text{ y }6'),
      p('Aplicando Pitágoras:'),
      f('d=\\sqrt{4^2+6^2}=\\sqrt{52}=2\\sqrt{13}'),
    ],
  ),
  q(
    30,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Un código se forma utilizando:'),
      p('dos letras distintas elegidas entre A, B, C, D, donde el orden importa;'),
      p('luego un dígito elegido entre 1, 2, 3.'),
      p('No se puede repetir la letra.'),
      p('¿Cuántos códigos distintos pueden formarse?'),
    ],
    [tOpt('24', false), tOpt('36', true), tOpt('48', false), tOpt('64', false)],
    [
      p('Para la primera letra existen 4 posibilidades.'),
      p('Como no puede repetirse, para la segunda existen 3.'),
      p('Finalmente existen 3 posibilidades para el dígito.'),
      p('Entonces:'),
      f('4\\cdot3\\cdot3=36'),
    ],
  ),
  q(
    31,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [p('Una cuenta de $80.000 aumenta en un 15%.'), p('¿Cuál es el nuevo monto?')],
    [tOpt('$92.000', true), tOpt('$88.000', false), tOpt('$95.000', false), tOpt('$98.000', false)],
    [
      p('El aumento corresponde a:'),
      f('80000\\cdot0,15=12000'),
      p('Por lo tanto:'),
      f('80000+12000=92000'),
    ],
  ),
  q(
    32,
    'ALGEBRA_FUNCIONES',
    'FACIL',
    'REPRESENTAR',
    [p('¿Cuál de las siguientes expresiones es equivalente a:'), f('3(x+4)-2x'), p('?')],
    [fOpt('x+4', false), fOpt('x+12', true), fOpt('5x+12', false), fOpt('x+10', false)],
    [
      p('Distribuyendo:'),
      f('3(x+4)=3x+12'),
      p('Luego:'),
      f('3x+12-2x=x+12'),
    ],
  ),
  q(
    33,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('La siguiente tabla muestra la cantidad de libros leídos por un grupo de estudiantes durante un mes:'),
      p('Libros leídos: 0 — Cantidad de estudiantes: 2'),
      p('Libros leídos: 1 — Cantidad de estudiantes: 5'),
      p('Libros leídos: 2 — Cantidad de estudiantes: 7'),
      p('Libros leídos: 3 — Cantidad de estudiantes: 4'),
      p('Libros leídos: 4 — Cantidad de estudiantes: 2'),
      p('¿Cuántos estudiantes participaron en total?'),
    ],
    [tOpt('18', false), tOpt('19', false), tOpt('20', true), tOpt('22', false)],
    [
      p('La cantidad total de estudiantes corresponde a la suma de las frecuencias:'),
      f('2+5+7+4+2=20'),
    ],
  ),
  q(
    34,
    'GEOMETRIA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [p('Un cuadrado tiene área:'), f('144\\text{ cm}^2'), p('¿Cuál es su perímetro?')],
    [tOpt('24 cm', false), tOpt('36 cm', false), tOpt('72 cm', false), tOpt('48 cm', true)],
    [
      p('Si s es el lado del cuadrado:'),
      f('s^2=144'),
      p('Entonces:'),
      f('s=12'),
      p('El perímetro es:'),
      f('4\\cdot12=48\\text{ cm}'),
    ],
  ),
  q(
    35,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'MODELAR',
    [
      p('Una empresa cobra por un servicio según la expresión:'),
      f('C(n)=2500+800n'),
      p('donde n representa la cantidad de unidades utilizadas.'),
      p('Si una persona pagó $8.900, ¿cuántas unidades utilizó?'),
    ],
    [tOpt('8', true), tOpt('6', false), tOpt('9', false), tOpt('7', false)],
    [
      p('Se iguala el costo a $8.900:'),
      f('2500+800n=8900'),
      p('Entonces:'),
      f('800n=6400'),
      f('n=8'),
    ],
  ),
  q(
    36,
    'NUMEROS',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('El precio de un producto aumenta en un 25%. Posteriormente, el nuevo precio se rebaja en un cierto porcentaje y vuelve exactamente a su precio original.'),
      p('¿Qué porcentaje de descuento se aplicó sobre el precio aumentado?'),
    ],
    [tOpt('15%', false), tOpt('25%', false), tOpt('20%', true), tOpt('30%', false)],
    [
      p('Si el precio original es P, después del aumento queda:'),
      f('1,25P'),
      p('Para volver al precio original debe descontarse:'),
      f('1,25P-P=0,25P'),
      p('Ese descuento se calcula sobre el precio aumentado:'),
      f('\\frac{0,25P}{1,25P}=0,20'),
      p('Por lo tanto, corresponde a un descuento del:'),
      f('20\\%'),
    ],
  ),
  q(
    37,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('En una bolsa hay 12 fichas: 7 blancas y 5 negras.'),
      p('Se extrae una ficha al azar.'),
      p('¿Cuál es la probabilidad de obtener una ficha negra?'),
    ],
    [fOpt('\\frac7{12}', false), fOpt('\\frac5{12}', true), fOpt('\\frac57', false), fOpt('\\frac75', false)],
    [
      p('Hay 5 fichas negras entre 12 fichas totales.'),
      p('Entonces:'),
      f('P(\\text{negra})=\\frac5{12}'),
    ],
  ),
  q(
    38,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('La función cuadrática:'),
      f('f(x)=x^2-6x+k'),
      p('tiene su valor mínimo igual a -4.'),
      p('¿Cuál es el valor de k?'),
    ],
    [tOpt('3', false), tOpt('4', false), tOpt('9', false), tOpt('5', true)],
    [
      p('El vértice de:'),
      f('f(x)=x^2-6x+k'),
      p('ocurre en:'),
      f('x=3'),
      p('Como el valor mínimo es -4:'),
      f('f(3)=-4'),
      p('Entonces:'),
      f('9-18+k=-4'),
      f('k=5'),
    ],
  ),
  q(
    39,
    'GEOMETRIA',
    'FACIL',
    'REPRESENTAR',
    [
      p('Un punto:'),
      f('A=(2,3)'),
      p('se refleja respecto del eje x.'),
      p('¿Cuál es su imagen?'),
    ],
    [fOpt('(2,-3)', true), fOpt('(-2,3)', false), fOpt('(3,2)', false), fOpt('(-2,-3)', false)],
    [
      p('Al reflejar un punto respecto del eje x, se conserva la primera coordenada y cambia el signo de la segunda:'),
      f('(2,3)\\rightarrow(2,-3)'),
    ],
  ),
  q(
    40,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'MODELAR',
    [
      p('En una encuesta a 200 estudiantes, el 35% señaló que utiliza bicicleta para trasladarse al menos una vez por semana.'),
      p('¿Cuántos estudiantes representan ese porcentaje?'),
    ],
    [tOpt('55', false), tOpt('65', false), tOpt('70', true), tOpt('75', false)],
    [
      p('El 35% de 200 corresponde a:'),
      f('200\\cdot0,35=70'),
      p('Por lo tanto, son 70 estudiantes.'),
    ],
  ),
  q(
    41,
    'NUMEROS',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Una población comienza con 150 individuos y duplica su tamaño al término de cada hora.'),
      p('Otra población permanece constante en 2.400 individuos.'),
      p('¿Cuántas horas completas deben transcurrir para que la primera población alcance por primera vez a la segunda?'),
    ],
    [tOpt('3', false), tOpt('4', true), tOpt('5', false), tOpt('8', false)],
    [
      p('La primera población evoluciona como:'),
      f('150\\cdot2^t'),
      p('Se busca cuándo alcanza 2400:'),
      f('150\\cdot2^t=2400'),
      p('Dividiendo por 150:'),
      f('2^t=16'),
      p('Como:'),
      f('16=2^4'),
      p('deben transcurrir:'),
      f('4'),
      p('horas.'),
    ],
  ),
  q(
    42,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'ARGUMENTAR',
    [p('La función:'), f('f(x)=-2x+6'), p('¿cuál de las siguientes afirmaciones es correcta?')],
    [
      tOpt('Es decreciente y corta al eje y en 6.', true),
      tOpt('Es creciente y corta al eje y en -2.', false),
      tOpt('Es creciente y corta al eje x en 6.', false),
      tOpt('Es decreciente y no corta al eje x.', false),
    ],
    [
      p('La pendiente de:'),
      f('f(x)=-2x+6'),
      p('es negativa, por lo que la función es decreciente.'),
      p('Además:'),
      f('f(0)=6'),
      p('Así, corta al eje y en 6.'),
    ],
  ),
  q(
    43,
    'PROBABILIDAD_ESTADISTICA',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('El grupo A está formado por 5 estudiantes y tiene promedio 14.'),
      p('El grupo B también está formado por 5 estudiantes y tiene promedio 18.'),
      p('Un estudiante del grupo B se cambia al grupo A. Después del cambio, el promedio del grupo A pasa a ser 15.'),
      p('¿Cuál es el nuevo promedio del grupo B?'),
    ],
    [tOpt('16,5', false), tOpt('17', false), tOpt('18', false), tOpt('17,5', true)],
    [
      p('El grupo A tenía una suma de edades equivalente a:'),
      f('5\\cdot14=70'),
      p('Después de recibir al estudiante, su suma pasa a:'),
      f('6\\cdot15=90'),
      p('Por lo tanto, la edad del estudiante trasladado es:'),
      f('90-70=20'),
      p('El grupo B tenía suma:'),
      f('5\\cdot18=90'),
      p('Al retirar a esa persona:'),
      f('90-20=70'),
      p('Quedan 4 estudiantes, así que:'),
      f('\\frac{70}{4}=17,5'),
    ],
  ),
  q(
    44,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Un terreno triangular tiene base de 18 m y área de:'),
      f('108\\text{ m}^2'),
      p('¿Cuál es su altura correspondiente a esa base?'),
    ],
    [tOpt('6 m', false), tOpt('18 m', false), tOpt('12 m', true), tOpt('24 m', false)],
    [
      p('El área de un triángulo es:'),
      f('A=\\frac{bh}{2}'),
      p('Entonces:'),
      f('108=\\frac{18h}{2}'),
      f('108=9h'),
      f('h=12'),
    ],
  ),
  q(
    45,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una receta utiliza harina y avena en razón:'),
      f('5:2'),
      p('Si se desea preparar una mezcla con 21 kg en total manteniendo la misma razón, ¿cuántos kilogramos de harina se necesitan?'),
    ],
    [tOpt('12', false), tOpt('15', true), tOpt('17,5', false), tOpt('18', false)],
    [
      p('La razón total contiene:'),
      f('5+2=7'),
      p('partes.'),
      p('Si las 7 partes equivalen a 21 kg:'),
      f('21\\div7=3'),
      p('kg por parte.'),
      p('La harina representa 5 partes:'),
      f('5\\cdot3=15'),
      p('kg.'),
    ],
  ),
  q(
    46,
    'ALGEBRA_FUNCIONES',
    'FACIL',
    'REPRESENTAR',
    [p('La función:'), f('f(x)=3x-4'), p('¿cuál es el valor de:'), f('f(5)?')],
    [tOpt('15', false), tOpt('7', false), tOpt('19', false), tOpt('11', true)],
    [
      p('Se reemplaza x=5:'),
      f('f(5)=3(5)-4=15-4=11'),
    ],
  ),
  q(
    47,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Un depósito contiene 240 litros de agua.'),
      p('Durante la mañana se utiliza:'),
      f('\\frac38'),
      p('del contenido.'),
      p('¿Cuántos litros quedan en el depósito?'),
    ],
    [tOpt('150', true), tOpt('90', false), tOpt('180', false), tOpt('120', false)],
    [
      p('La cantidad utilizada es:'),
      f('240\\cdot\\frac38=90'),
      p('Entonces quedan:'),
      f('240-90=150'),
      p('litros.'),
    ],
  ),
  q(
    48,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Una plaza rectangular tiene un largo de 30 m y un ancho de 20 m.'),
      p('Se construye en todo su borde interior una franja de 2 m de ancho.'),
      p('¿Cuál es el área de la parte central que queda fuera de la franja?'),
    ],
    [fOpt('480\\text{ m}^2', false), fOpt('416\\text{ m}^2', true), fOpt('520\\text{ m}^2', false), fOpt('496\\text{ m}^2', false)],
    [
      p('La franja mide 2 m en cada borde, por lo que se deben descontar 4 m de cada dimensión total.'),
      p('Las dimensiones interiores son:'),
      f('30-4=26'),
      p('y:'),
      f('20-4=16'),
      p('Por lo tanto:'),
      f('26\\cdot16=416\\text{ m}^2'),
    ],
  ),
  q(
    49,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'REPRESENTAR',
    [p('Las edades de cinco personas son:'), f('14,\\;15,\\;15,\\;16,\\;20'), p('¿Cuál es el rango?')],
    [tOpt('5', false), tOpt('7', false), tOpt('6', true), tOpt('4', false)],
    [
      p('El rango se obtiene restando el menor valor al mayor:'),
      f('20-14=6'),
    ],
  ),
  q(
    50,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [p('Resuelve:'), f('2(x+3)-5=x+8')],
    [fOpt('x=7', true), fOpt('x=5', false), fOpt('x=8', false), fOpt('x=6', false)],
    [
      p('Se desarrolla:'),
      f('2(x+3)-5=x+8'),
      f('2x+6-5=x+8'),
      f('2x+1=x+8'),
      p('Por lo tanto:'),
      f('x=7'),
    ],
  ),
  q(
    51,
    'NUMEROS',
    'MEDIA',
    'MODELAR',
    [
      p('Una tienda compra un artículo en $24.000 y desea venderlo con una ganancia equivalente al 25% del costo.'),
      p('¿A qué precio debe venderlo?'),
    ],
    [tOpt('$28.000', false), tOpt('$32.000', false), tOpt('$36.000', false), tOpt('$30.000', true)],
    [
      p('La ganancia corresponde al 25% del costo:'),
      f('24000\\cdot0,25=6000'),
      p('Entonces el precio de venta debe ser:'),
      f('24000+6000=30000'),
    ],
  ),
  q(
    52,
    'GEOMETRIA',
    'FACIL',
    'REPRESENTAR',
    [p('Un triángulo rectángulo tiene catetos de 6 cm y 8 cm.'), p('¿Cuánto mide su hipotenusa?')],
    [tOpt('12 cm', false), tOpt('14 cm', false), tOpt('10 cm', true), tOpt('16 cm', false)],
    [
      p('Aplicando el teorema de Pitágoras:'),
      f('c^2=6^2+8^2'),
      f('c^2=36+64=100'),
      p('Entonces:'),
      f('c=10'),
    ],
  ),
  q(
    53,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('Dos planes de arriendo cobran:'),
      f('A(t)=2500+900t'),
      p('y:'),
      f('B(t)=4300+600t'),
      p('donde t es la cantidad de horas utilizadas.'),
      p('¿Cuál es la menor cantidad entera de horas para la cual el costo del Plan B es al menos un 15% menor que el costo del Plan A?'),
    ],
    [tOpt('12', false), tOpt('13', false), tOpt('14', true), tOpt('15', false)],
    [
      p('Para que el Plan B sea al menos un 15% menor que A debe cumplirse:'),
      f('B(t)\\leq0,85A(t)'),
      p('Entonces:'),
      f('4300+600t\\leq0,85(2500+900t)'),
      f('4300+600t\\leq2125+765t'),
      f('2175\\leq165t'),
      f('t\\geq13,18\\ldots'),
      p('Como se pide una cantidad entera de horas, la menor posible es:'),
      f('14'),
    ],
  ),
  q(
    54,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [p('Se lanzan dos monedas equilibradas.'), p('¿Cuál es la probabilidad de obtener exactamente una cara?')],
    [fOpt('\\frac12', true), fOpt('\\frac14', false), fOpt('1', false), fOpt('\\frac34', false)],
    [
      p('Los resultados posibles al lanzar dos monedas son:'),
      f('CC,\\;CS,\\;SC,\\;SS'),
      p('Exactamente una cara aparece en:'),
      f('CS'),
      p('y:'),
      f('SC'),
      p('Son 2 casos de 4:'),
      f('\\frac24=\\frac12'),
    ],
  ),
  q(
    55,
    'GEOMETRIA',
    'DIFICIL',
    'MODELAR',
    [
      p('Una caja con forma de prisma rectangular tiene dimensiones interiores:'),
      f('x,\\qquad x+2,\\qquad5'),
      p('medidas en centímetros.'),
      p('Si su volumen es:'),
      f('240\\text{ cm}^3'),
      p('¿cuál es el área total de sus seis caras?'),
    ],
    [fOpt('196\\text{ cm}^2', false), fOpt('216\\text{ cm}^2', false), fOpt('228\\text{ cm}^2', false), fOpt('236\\text{ cm}^2', true)],
    [
      p('El volumen cumple:'),
      f('5x(x+2)=240'),
      p('Entonces:'),
      f('x(x+2)=48'),
      f('x^2+2x-48=0'),
      p('La solución positiva es:'),
      f('x=6'),
      p('Las dimensiones son:'),
      f('6,\\;8,\\;5'),
      p('El área total es:'),
      f('2(6\\cdot8+6\\cdot5+8\\cdot5)=2(48+30+40)=236\\text{ cm}^2'),
    ],
  ),
  q(
    56,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'REPRESENTAR',
    [p('La función:'), f('f(x)=x^2-4x+3'), p('¿cuáles son sus ceros?')],
    [
      tOpt('x=-1 y x=-3', false),
      tOpt('x=1 y x=3', true),
      tOpt('x=1 y x=-3', false),
      tOpt('x=-1 y x=3', false),
    ],
    [
      p('Factorizando:'),
      f('x^2-4x+3'),
      p('se obtiene:'),
      f('(x-1)(x-3)'),
      p('Por lo tanto, los ceros son:'),
      f('x=1'),
      p('y:'),
      f('x=3'),
    ],
  ),
  q(
    57,
    'NUMEROS',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Un estanque está lleno al 60% de su capacidad.'),
      p('Después de agregar 120 litros, queda lleno al 75%.'),
      p('¿Cuál es la capacidad total del estanque?'),
    ],
    [tOpt('720 L', false), tOpt('600 L', false), tOpt('800 L', true), tOpt('900 L', false)],
    [
      p('El aumento desde 60% hasta 75% representa:'),
      f('15\\%'),
      p('de la capacidad total.'),
      p('Si ese 15% corresponde a 120 litros:'),
      f('0,15C=120'),
      p('Entonces:'),
      f('C=\\frac{120}{0,15}=800'),
      p('La capacidad es 800 litros.'),
    ],
  ),
  q(
    58,
    'PROBABILIDAD_ESTADISTICA',
    'DIFICIL',
    'MODELAR',
    [
      p('En una caja hay fichas rojas y azules.'),
      p('La probabilidad de extraer una ficha roja es:'),
      f('\\frac35'),
      p('Después de agregar 4 fichas azules, la probabilidad de extraer una roja pasa a ser:'),
      f('\\frac12'),
      p('¿Cuántas fichas había inicialmente en la caja?'),
    ],
    [tOpt('12', false), tOpt('24', false), tOpt('16', false), tOpt('20', true)],
    [
      p('Sea N la cantidad inicial de fichas.'),
      p('Como 3/5 son rojas, hay:'),
      f('\\frac35N'),
      p('fichas rojas.'),
      p('Después de agregar 4 azules:'),
      f('\\frac{\\frac35N}{N+4}=\\frac12'),
      p('Resolviendo:'),
      f('\\frac65N=N+4'),
      f('\\frac15N=4'),
      f('N=20'),
    ],
  ),
  q(
    59,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('La altura h, en metros, de un objeto está modelada por:'),
      f('h(t)=-5t^2+30t+10'),
      p('donde t se mide en segundos.'),
      p('El objeto alcanza una altura de 30 m en dos instantes distintos.'),
      p('¿Cuál es la diferencia entre esos dos instantes?'),
    ],
    [fOpt('2\\sqrt5\\text{ s}', true), fOpt('\\sqrt5\\text{ s}', false), fOpt('3\\sqrt5\\text{ s}', false), fOpt('4\\sqrt5\\text{ s}', false)],
    [
      p('Se busca cuándo:'),
      f('-5t^2+30t+10=30'),
      p('Entonces:'),
      f('-5t^2+30t-20=0'),
      p('Dividiendo por -5:'),
      f('t^2-6t+4=0'),
      p('Las soluciones son:'),
      f('t=3\\pm\\sqrt5'),
      p('La diferencia entre ellas es:'),
      f('(3+\\sqrt5)-(3-\\sqrt5)=2\\sqrt5'),
      p('segundos.'),
    ],
  ),
  q(
    60,
    'GEOMETRIA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('Los vértices de un rectángulo son:'),
      f('(1,2),\\;(7,2),\\;(7,6),\\;(1,6)'),
      p('¿Cuál es su área?'),
    ],
    [tOpt('20', false), tOpt('28', false), tOpt('24', true), tOpt('32', false)],
    [
      p('La dimensión horizontal del rectángulo es:'),
      f('7-1=6'),
      p('y la vertical:'),
      f('6-2=4'),
      p('Por lo tanto, su área es:'),
      f('6\\cdot4=24'),
    ],
  ),
  q(
    61,
    'NUMEROS',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Una botella contiene:'),
      f('1,5\\text{ L}'),
      p('de agua.'),
      p('Si se utilizan:'),
      f('600\\text{ mL}'),
      p('¿cuántos mililitros quedan?'),
    ],
    [fOpt('600\\text{ mL}', false), fOpt('750\\text{ mL}', false), fOpt('1.100\\text{ mL}', false), fOpt('900\\text{ mL}', true)],
    [
      p('Primero convertimos:'),
      f('1,5\\text{ L}=1500\\text{ mL}'),
      p('Después:'),
      f('1500-600=900'),
      p('Quedan:'),
      f('900\\text{ mL}'),
    ],
  ),
  q(
    62,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una función afín está dada por:'),
      f('f(x)=ax+5'),
      p('y se sabe que:'),
      f('f(4)=17'),
      p('¿Cuál es el valor de:'),
      f('f(7)?'),
    ],
    [tOpt('21', false), tOpt('26', true), tOpt('28', false), tOpt('40', false)],
    [
      p('Como:'),
      f('f(4)=17'),
      p('se cumple:'),
      f('4a+5=17'),
      p('Entonces:'),
      f('a=3'),
      p('Por lo tanto:'),
      f('f(7)=3(7)+5=26'),
    ],
  ),
  q(
    63,
    'GEOMETRIA',
    'MEDIA',
    'ARGUMENTAR',
    [
      p('Un triángulo tiene lados de longitudes:'),
      f('6\\text{ cm},\\quad8\\text{ cm},\\quad10\\text{ cm}'),
      p('¿Cuál afirmación permite concluir correctamente que el triángulo es rectángulo?'),
    ],
    [fOpt('6+8>10', false), fOpt('6^2+10^2>8^2', false), fOpt('6\\cdot8=48', false), fOpt('6^2+8^2=10^2', true)],
    [
      p('El lado mayor mide 10 cm.'),
      p('Se cumple:'),
      f('6^2+8^2 = 36+64 = 100'),
      p('y:'),
      f('10^2=100'),
      p('Por el recíproco del teorema de Pitágoras, el triángulo es rectángulo.'),
    ],
  ),
  q(
    64,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('En un curso de 40 estudiantes, 14 prefieren estudiar por la mañana.'),
      p('Si se selecciona un estudiante al azar, ¿cuál es la probabilidad de que no prefiera estudiar por la mañana?'),
    ],
    [fOpt('\\frac7{20}', false), fOpt('\\frac{13}{20}', true), fOpt('\\frac{14}{40}', false), fOpt('\\frac{27}{40}', false)],
    [
      p('Los estudiantes que no prefieren estudiar por la mañana son:'),
      f('40-14=26'),
      p('Por lo tanto:'),
      f('P=\\frac{26}{40}'),
      p('Simplificando:'),
      f('P=\\frac{13}{20}'),
    ],
  ),
  q(
    65,
    'NUMEROS',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('El precio de un producto aumenta primero en un 20%.'),
      p('Luego se aplica un descuento sobre el precio aumentado y el precio final resulta ser un 6% menor que el precio original.'),
      p('¿Qué porcentaje de descuento se aplicó sobre el precio aumentado?'),
    ],
    [fOpt('20\\%', false), fOpt('21\\frac23\\%', true), fOpt('22\\%', false), fOpt('26\\%', false)],
    [
      p('Sea P el precio original.'),
      p('Después del aumento del 20%:'),
      f('1,2P'),
      p('El precio final es un 6% menor que el original:'),
      f('0,94P'),
      p('Si d es el descuento aplicado:'),
      f('1,2P(1-d)=0,94P'),
      p('Entonces:'),
      f('1-d=\\frac{0,94}{1,2}'),
      f('1-d=\\frac{47}{60}'),
      p('Por lo tanto:'),
      f('d=\\frac{13}{60}'),
      f('d=0,2166\\ldots'),
      p('Es decir:'),
      f('21\\frac23\\%'),
    ],
  ),
];

const ensayoPaesM1: ExamSourceModule = {
  examKey: 'ENSAYO.M1',
  title: 'Ensayo PAES M1',
  subjectKey: 'matematica',
  durationMinutes: 140,
  questions,
};

export default ensayoPaesM1;
