// ENSAYOS-M2 -- SOURCE del Ensayo PAES M2 ZETRYND.
// Contenido editorial DEFINITIVO, transcrito VERBATIM del handoff
// "ENSAYOS-M2 — IMPLEMENTACIÓN DEFINITIVA" (55 preguntas + explicaciones +
// clasificación por eje / dificultad / habilidad + clave).
//
// Correcciones editoriales DEFINITIVAS ya incorporadas (autorizadas en el
// handoff):
//   - Q6: alternativas 6√2 / 3√2 / 4√3 / 6√3, correcta A (la versión antigua
//     tenía distractores matemáticamente equivalentes).
//   - Q37: ganancia de al menos 192 (miles de pesos), correcta B (16 ≤ x ≤ 32);
//     la versión antigua usaba 256, incompatible con ese intervalo.
//   - Q10: dificultad MEDIA (resolución de "ENSAYOS-M2 — DIFFICULTY
//     CONTRADICTION RESOLUTION"; la etiqueta DIFICIL previa era un error de
//     metadata). Todo lo demás de Q10 queda idéntico.
//
// Únicas adaptaciones aplicadas -- puramente técnicas, contenido visible
// idéntico (mismo criterio que `content/ensayo/m1/ensayo-paes-m1.ts`,
// ENSAYOS-M1-A §15):
//   - `$$...$$` de la fuente -> bloque `formula` con el LaTeX interior.
//   - Matemática inline en prosa (`\(x\)`, `40\%`, `90^\circ`, ...) -> texto
//     plano visualmente idéntico al render.
//   - El artefacto markdown de "render + LaTeX crudo" duplicado
//     (p. ej. `0,40⋅0,30=0,120,40\cdot0,30=0,12`) se reconstruye como la única
//     fórmula intencionada.
//   - Listas del enunciado -> un párrafo por ítem, sin pérdida.
//   - Referencias inline a potencias en Q54 (`n^2`, `2^3`, `2^4`) -> texto con
//     superíndices Unicode (n², 2³, 2⁴), visualmente idéntico.
//
// Cero cambios de cifras, fórmulas, alternativas, respuesta correcta,
// procedimiento ni estilo. Este archivo NO se importa a DB por sí mismo (eso
// es el importer `scripts/import-ensayo.ts`) y NO forma parte del
// `CONTENT_MANIFEST` de Study.
import type { ExamSourceModule, ExamSourceQuestion, ExamSourceOption } from '../schema';

type Block = { type: 'paragraph'; text: string } | { type: 'formula'; latex: string };
const p = (text: string): Block => ({ type: 'paragraph', text });
const f = (latex: string): Block => ({ type: 'formula', latex });
const withOrder = (blocks: Block[]) => blocks.map((b, order) => ({ ...b, order }));

const tOpt = (text: string, correct: boolean): ExamSourceOption => ({ content: { type: 'paragraph', order: 0, text }, correct });
const fOpt = (latex: string, correct: boolean): ExamSourceOption => ({ content: { type: 'formula', order: 0, latex }, correct });

const q = (
  n: number,
  axis: ExamSourceQuestion['axis'],
  difficulty: ExamSourceQuestion['difficulty'],
  primarySkill: ExamSourceQuestion['primarySkill'],
  stem: Block[],
  options: ExamSourceOption[],
  explanation: Block[],
): ExamSourceQuestion => ({
  questionKey: `ENSAYO.M2.Q${n}`,
  displayOrder: n,
  axis,
  difficulty,
  primarySkill,
  stemContent: withOrder(stem),
  options,
  explanationContent: withOrder(explanation),
});

/** Alternativas estándar de una pregunta de Suficiencia de Datos. */
const dsOptions = (correct: 'A' | 'B' | 'C' | 'D'): ExamSourceOption[] => [
  tOpt('La información (1) por sí sola es suficiente, pero (2) por sí sola no.', correct === 'A'),
  tOpt('La información (2) por sí sola es suficiente, pero (1) por sí sola no.', correct === 'B'),
  tOpt('Cada información por separado es suficiente.', correct === 'C'),
  tOpt('Se necesitan conjuntamente (1) y (2).', correct === 'D'),
];

const questions: ExamSourceQuestion[] = [
  q(
    1,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Un laboratorio prepara una solución mezclando dos sustancias. La primera representa el 40% del volumen total y contiene un 30% de un compuesto activo. La segunda representa el 60% restante y contiene un 50% del mismo compuesto.'),
      p('¿Qué porcentaje del volumen total de la mezcla corresponde al compuesto activo?'),
    ],
    [fOpt('38\\%', false), fOpt('42\\%', true), fOpt('44\\%', false), fOpt('48\\%', false)],
    [
      p('La primera sustancia aporta:'),
      f('0,40\\cdot0,30=0,12'),
      p('del volumen total.'),
      p('La segunda aporta:'),
      f('0,60\\cdot0,50=0,30'),
      p('Entonces:'),
      f('0,12+0,30=0,42'),
      p('Por lo tanto, el compuesto activo representa:'),
      f('42\\%'),
      p('del volumen total.'),
    ],
  ),
  q(
    2,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'REPRESENTAR',
    [
      p('Una función exponencial tiene la forma:'),
      f('f(x)=a\\cdot2^x'),
      p('y se sabe que:'),
      f('f(3)=40'),
      p('¿Cuál es el valor de f(5)?'),
    ],
    [fOpt('80', false), fOpt('120', false), fOpt('160', true), fOpt('200', false)],
    [
      p('Como:'),
      f('a\\cdot2^3=40'),
      p('se obtiene:'),
      f('8a=40'),
      f('a=5'),
      p('Entonces:'),
      f('f(5)=5\\cdot2^5=5\\cdot32=160'),
    ],
  ),
  q(
    3,
    'GEOMETRIA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('En el plano cartesiano, los extremos de un diámetro de una circunferencia son:'),
      f('A=(-2,4)'),
      p('y:'),
      f('B=(6,-2)'),
      p('¿Cuál es el radio de la circunferencia?'),
    ],
    [fOpt('5', true), fOpt('10', false), fOpt('2\\sqrt{10}', false), fOpt('5\\sqrt{2}', false)],
    [
      p('La longitud del diámetro es:'),
      f('AB=\\sqrt{(6-(-2))^2+(-2-4)^2}=\\sqrt{8^2+(-6)^2}=\\sqrt{100}=10'),
      p('El radio es la mitad:'),
      f('r=5'),
    ],
  ),
  q(
    4,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('En un curso, el 60% de los estudiantes practica algún deporte. Entre quienes practican deporte, el 25% pertenece a un equipo competitivo.'),
      p('Si se elige un estudiante al azar, ¿cuál es la probabilidad de que practique deporte y pertenezca a un equipo competitivo?'),
    ],
    [fOpt('10\\%', false), fOpt('20\\%', false), fOpt('35\\%', false), fOpt('15\\%', true)],
    [
      p('Se requiere que ocurran ambas condiciones:'),
      f('0,60\\cdot0,25=0,15'),
      p('Por lo tanto:'),
      f('P=15\\%'),
    ],
  ),
  q(
    5,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('La función:'),
      f('f(x)=x^2-2kx+3k+4'),
      p('tiene exactamente una intersección con el eje x.'),
      p('¿Cuáles son los posibles valores de k?'),
    ],
    [
      fOpt('k=-4\\text{ o }1', false),
      fOpt('k=-1\\text{ o }4', true),
      fOpt('k=1\\text{ o }3', false),
      fOpt('k=-3\\text{ o }4', false),
    ],
    [
      p('Para que la función tenga exactamente una intersección con el eje x:'),
      f('\\Delta=0'),
      p('Entonces:'),
      f('(-2k)^2-4(3k+4)=0'),
      f('4k^2-12k-16=0'),
      p('Dividiendo por 4:'),
      f('k^2-3k-4=0'),
      p('Factorizando:'),
      f('(k-4)(k+1)=0'),
      p('Por lo tanto:'),
      f('k=4'),
      p('o:'),
      f('k=-1'),
    ],
  ),
  q(
    6,
    'NUMEROS',
    'FACIL',
    'REPRESENTAR',
    [
      p('¿Cuál de las siguientes expresiones es equivalente a:'),
      f('\\sqrt{72}'),
      p('?'),
    ],
    [fOpt('6\\sqrt{2}', true), fOpt('3\\sqrt{2}', false), fOpt('4\\sqrt{3}', false), fOpt('6\\sqrt{3}', false)],
    [
      p('Se factoriza:'),
      f('72=36\\cdot2'),
      p('Entonces:'),
      f('\\sqrt{72}=\\sqrt{36\\cdot2}=6\\sqrt{2}'),
    ],
  ),
  q(
    7,
    'GEOMETRIA',
    'DIFICIL',
    'MODELAR',
    [
      p('Dos triángulos son semejantes.'),
      p('El área del triángulo menor es:'),
      f('54\\text{ cm}^2'),
      p('y un lado correspondiente mide 6 cm.'),
      p('En el triángulo mayor, ese lado correspondiente mide 10 cm.'),
      p('¿Cuál es el área del triángulo mayor?'),
    ],
    [
      fOpt('90\\text{ cm}^2', false),
      fOpt('120\\text{ cm}^2', false),
      fOpt('150\\text{ cm}^2', true),
      fOpt('180\\text{ cm}^2', false),
    ],
    [
      p('La razón entre lados es:'),
      f('\\frac{10}{6}=\\frac{5}{3}'),
      p('Las áreas se relacionan mediante el cuadrado de la razón:'),
      f('\\left(\\frac{5}{3}\\right)^2=\\frac{25}{9}'),
      p('Entonces:'),
      f('54\\cdot\\frac{25}{9}=150'),
      p('Por lo tanto:'),
      f('150\\text{ cm}^2'),
    ],
  ),
  q(
    8,
    'PROBABILIDAD_ESTADISTICA',
    'DIFICIL',
    'MODELAR',
    [
      p('Una máquina produce piezas defectuosas con probabilidad:'),
      f('0,1'),
      p('de manera independiente.'),
      p('Si se seleccionan 3 piezas, ¿cuál es la probabilidad de que exactamente una sea defectuosa?'),
    ],
    [fOpt('0,081', false), fOpt('0,243', true), fOpt('0,729', false), fOpt('0,027', false)],
    [
      p('La pieza defectuosa puede ocupar cualquiera de las tres posiciones:'),
      f('3(0,1)(0,9)^2=3(0,1)(0,81)=0,243'),
    ],
  ),
  q(
    9,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se desea determinar el valor de x.'),
      p('Se dispone de las siguientes informaciones:'),
      p('(1)'),
      f('x+y=10'),
      p('(2)'),
      f('x-y=4'),
      p('¿Cuál de las siguientes afirmaciones es correcta?'),
    ],
    dsOptions('D'),
    [
      p('Con cada ecuación individual existen múltiples valores posibles.'),
      p('Usando ambas:'),
      f('x+y=10'),
      f('x-y=4'),
      p('Sumando:'),
      f('2x=14'),
      f('x=7'),
      p('Por lo tanto, se necesitan conjuntamente.'),
    ],
  ),
  q(
    10,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Si:'),
      f('x=8^{\\frac{2}{3}}'),
      p('y:'),
      f('y=16^{\\frac{3}{4}}'),
      p('¿cuál es el valor de:'),
      f('\\frac{y}{x}'),
      p('?'),
    ],
    [fOpt('1', false), fOpt('4', false), fOpt('2', true), fOpt('8', false)],
    [
      f('8^{\\frac{2}{3}}=(\\sqrt[3]{8})^2=4'),
      p('y:'),
      f('16^{\\frac{3}{4}}=(\\sqrt[4]{16})^3=8'),
      p('Entonces:'),
      f('\\frac{y}{x}=\\frac{8}{4}=2'),
    ],
  ),
  q(
    11,
    'ALGEBRA_FUNCIONES',
    'FACIL',
    'REPRESENTAR',
    [
      p('Sean:'),
      f('f(x)=2x-1'),
      p('y:'),
      f('g(x)=x+3'),
      p('¿Cuál es el valor de:'),
      f('(f\\circ g)(2)'),
      p('?'),
    ],
    [fOpt('9', true), fOpt('7', false), fOpt('5', false), fOpt('11', false)],
    [
      f('g(2)=5'),
      p('Luego:'),
      f('f(5)=2(5)-1=9'),
    ],
  ),
  q(
    12,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'ARGUMENTAR',
    [
      p('Se tienen dos conjuntos de datos, A y B.'),
      p('Ambos poseen:'),
      p('igual cantidad de datos;'),
      p('igual promedio.'),
      p('Sin embargo, los valores de A están más concentrados alrededor del promedio que los valores de B.'),
      p('¿Cuál afirmación es necesariamente correcta?'),
    ],
    [
      tOpt('A tiene un promedio menor que B.', false),
      tOpt('A tiene un rango necesariamente igual a cero.', false),
      tOpt('B tiene una mediana mayor que A.', false),
      tOpt('A tiene menor dispersión que B.', true),
    ],
    [
      p('Que los valores estén más concentrados alrededor del promedio significa que presentan menor variabilidad o dispersión.'),
      p('Esto no permite concluir diferencias en promedio o mediana.'),
      p('Por lo tanto, A tiene menor dispersión que B.'),
    ],
  ),
  q(
    13,
    'GEOMETRIA',
    'DIFICIL',
    'MODELAR',
    [
      p('Los puntos:'),
      f('A=(1,2)'),
      p('y:'),
      f('B=(7,5)'),
      p('son dos vértices consecutivos de un cuadrado.'),
      p('¿Cuál es el área del cuadrado?'),
    ],
    [fOpt('45', true), fOpt('36', false), fOpt('27', false), fOpt('18', false)],
    [
      f('AB=\\sqrt{(7-1)^2+(5-2)^2}=\\sqrt{36+9}=\\sqrt{45}'),
      p('El área es:'),
      f('(\\sqrt{45})^2=45'),
    ],
  ),
  q(
    14,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('De un grupo de 6 estudiantes se elegirán 2 para representar al curso.'),
      p('¿Cuántas parejas distintas pueden formarse?'),
    ],
    [fOpt('12', false), fOpt('15', true), fOpt('30', false), fOpt('36', false)],
    [f('\\binom{6}{2}=\\frac{6\\cdot5}{2}=15')],
  ),
  q(
    15,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('Las funciones:'),
      f('f(x)=x^2-4x+7'),
      p('y:'),
      f('g(x)=mx+3'),
      p('se intersectan en exactamente un punto.'),
      p('¿Cuáles son los posibles valores de m?'),
    ],
    [
      fOpt('m=-2\\text{ o }6', false),
      fOpt('m=-4\\text{ o }4', false),
      fOpt('m=-6\\text{ o }2', false),
      fOpt('m=-8\\text{ o }0', true),
    ],
    [
      p('En la intersección:'),
      f('x^2-(m+4)x+4=0'),
      p('Para una única solución:'),
      f('\\Delta=0'),
      p('Entonces:'),
      f('(m+4)^2-16=0'),
      f('m+4=\\pm4'),
      p('De donde:'),
      f('m=0'),
      p('o:'),
      f('m=-8'),
    ],
  ),
  q(
    16,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Un cultivo contiene inicialmente 2.400 microorganismos. Después de cierto tratamiento, su cantidad disminuye en un 15%.'),
      p('Posteriormente, la cantidad restante aumenta en un 20%.'),
      p('¿Cuántos microorganismos hay al final?'),
    ],
    [fOpt('2.244', false), fOpt('2.400', false), fOpt('2.448', true), fOpt('2.520', false)],
    [
      f('2400\\cdot0,85=2040'),
      p('Luego:'),
      f('2040\\cdot1,20=2448'),
    ],
  ),
  q(
    17,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'REPRESENTAR',
    [
      p('La función:'),
      f('f(x)=\\frac{2x-3}{5}'),
      p('es invertible.'),
      p('¿Cuál es la expresión de:'),
      f('f^{-1}(x)'),
      p('?'),
    ],
    [
      fOpt('f^{-1}(x)=\\frac{5x+3}{2}', true),
      fOpt('f^{-1}(x)=\\frac{5x-3}{2}', false),
      fOpt('f^{-1}(x)=\\frac{2x+3}{5}', false),
      fOpt('f^{-1}(x)=\\frac{5x+2}{3}', false),
    ],
    [
      p('Sea:'),
      f('y=\\frac{2x-3}{5}'),
      p('Entonces:'),
      f('5y=2x-3'),
      f('2x=5y+3'),
      f('x=\\frac{5y+3}{2}'),
      p('Por lo tanto:'),
      f('f^{-1}(x)=\\frac{5x+3}{2}'),
    ],
  ),
  q(
    18,
    'GEOMETRIA',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se desea determinar el área de un triángulo.'),
      p('(1) Dos de sus lados miden 6 cm y 8 cm.'),
      p('(2) El ángulo comprendido entre esos dos lados mide 90°.'),
      p('¿Cuál afirmación es correcta?'),
    ],
    [
      tOpt('La información (1) por sí sola es suficiente.', false),
      tOpt('La información (2) por sí sola es suficiente.', false),
      tOpt('Cada una por separado es suficiente.', false),
      tOpt('Se necesitan conjuntamente (1) y (2).', true),
    ],
    [
      p('Dos lados por sí solos no determinan el área.'),
      p('Un ángulo recto sin longitudes tampoco.'),
      p('Con ambas:'),
      f('A=\\frac{6\\cdot8}{2}=24\\text{ cm}^2'),
    ],
  ),
  q(
    19,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Una urna contiene 4 fichas rojas y 6 azules.'),
      p('Se realizan dos extracciones con reposición.'),
      p('¿Cuál es la probabilidad de obtener roja en ambas?'),
    ],
    [fOpt('\\frac{4}{25}', true), fOpt('\\frac{2}{5}', false), fOpt('\\frac{8}{25}', false), fOpt('\\frac{16}{25}', false)],
    [
      f('P(R)=\\frac{4}{10}=\\frac{2}{5}'),
      p('Como hay reposición:'),
      f('P(R,R)=\\frac{2}{5}\\cdot\\frac{2}{5}=\\frac{4}{25}'),
    ],
  ),
  q(
    20,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('El número de usuarios de dos plataformas después de t meses se modela por:'),
      f('A(t)=800\\cdot2^t'),
      f('B(t)=6400'),
      p('A supera significativamente a B cuando tiene al menos el doble de usuarios.'),
      p('¿Cuál es la menor cantidad entera de meses?'),
    ],
    [fOpt('3', false), fOpt('4', true), fOpt('5', false), fOpt('6', false)],
    [
      f('800\\cdot2^t\\geq12800'),
      f('2^t\\geq16'),
      p('Como:'),
      f('16=2^4'),
      p('se obtiene:'),
      f('t=4'),
    ],
  ),
  q(
    21,
    'NUMEROS',
    'FACIL',
    'REPRESENTAR',
    [
      p('¿Cuál expresión equivale a:'),
      f('\\frac{3^5\\cdot3^{-2}}{3}'),
      p('?'),
    ],
    [fOpt('3', false), fOpt('9', true), fOpt('27', false), fOpt('81', false)],
    [f('3^{5-2-1}=3^2=9')],
  ),
  q(
    22,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'ARGUMENTAR',
    [
      p('Grupo A:'),
      p('promedio 70;'),
      p('desviación estándar 4.'),
      p('Grupo B:'),
      p('promedio 70;'),
      p('desviación estándar 12.'),
      p('¿Cuál afirmación está mejor respaldada?'),
    ],
    [
      tOpt('Todos en A obtuvieron exactamente 70.', false),
      tOpt('B necesariamente tiene mediana menor que 70.', false),
      tOpt('A está más concentrado alrededor del promedio.', true),
      tOpt('B necesariamente tiene mayor puntaje máximo.', false),
    ],
    [
      p('Una desviación estándar menor indica menor dispersión.'),
      p('Como:'),
      f('4<12'),
      p('los resultados de A están más concentrados alrededor del promedio.'),
    ],
  ),
  q(
    23,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Una circunferencia tiene centro:'),
      f('C=(3,-2)'),
      p('y pasa por:'),
      f('P=(7,1)'),
      p('¿Cuál es su área?'),
    ],
    [fOpt('5\\pi', false), fOpt('13\\pi', false), fOpt('25\\pi', true), fOpt('49\\pi', false)],
    [
      f('r=\\sqrt{(7-3)^2+(1+2)^2}=\\sqrt{16+9}=5'),
      p('Entonces:'),
      f('A=\\pi r^2=25\\pi'),
    ],
  ),
  q(
    24,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Para cierto valor de k>1:'),
      f('f(x)=x^2-(k+2)x+2k'),
      p('tiene dos raíces reales distintas y una es el doble de la otra.'),
      p('¿Cuál es k?'),
    ],
    [fOpt('1', false), fOpt('2', false), fOpt('4', true), fOpt('8', false)],
    [
      p('Sean las raíces r y 2r.'),
      f('3r=k+2'),
      p('y:'),
      f('2r^2=2k'),
      p('Entonces:'),
      f('k=r^2'),
      p('Sustituyendo:'),
      f('r^2-3r+2=0'),
      f('(r-1)(r-2)=0'),
      p('Los candidatos son k=1 y k=4.'),
      p('Como:'),
      f('k>1'),
      p('queda:'),
      f('k=4'),
    ],
  ),
  q(
    25,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('De cartas numeradas:'),
      f('1,2,3,4,5'),
      p('se extraen simultáneamente dos.'),
      p('¿Cuál es la probabilidad de que su suma sea par?'),
    ],
    [fOpt('\\frac{2}{5}', true), fOpt('\\frac{1}{2}', false), fOpt('\\frac{3}{5}', false), fOpt('\\frac{7}{10}', false)],
    [
      p('La suma es par si ambas tienen la misma paridad.'),
      f('\\binom{3}{2}+\\binom{2}{2}=4'),
      p('Total:'),
      f('\\binom{5}{2}=10'),
      p('Entonces:'),
      f('P=\\frac{4}{10}=\\frac{2}{5}'),
    ],
  ),
  q(
    26,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Un laboratorio dispone de:'),
      f('1,8\\cdot10^6'),
      p('unidades.'),
      p('Pierde 20% y luego distribuye lo restante en recipientes de:'),
      f('3,6\\cdot10^5'),
      p('unidades.'),
      p('¿Cuántos recipientes completos llena?'),
    ],
    [fOpt('3', false), fOpt('5', false), fOpt('6', false), fOpt('4', true)],
    [
      f('1,8\\cdot10^6\\cdot0,8=1,44\\cdot10^6'),
      f('\\frac{1,44\\cdot10^6}{3,6\\cdot10^5}=4'),
    ],
  ),
  q(
    27,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('Una empresa vende x unidades mensuales de un producto.'),
      p('El precio, en pesos, de cada unidad está modelado por:'),
      f('p(x)=1000-20x'),
      p('y el costo total mensual está dado por:'),
      f('C(x)=200x+3000'),
      p('¿Para qué valores de x la ganancia es de al menos 3000 pesos?'),
    ],
    [
      fOpt('0\\leq x\\leq20', false),
      fOpt('10\\leq x\\leq30', true),
      fOpt('x\\geq30', false),
      fOpt('10\\leq x\\leq20', false),
    ],
    [
      f('I(x)=1000x-20x^2'),
      f('G(x)=-20x^2+800x-3000'),
      p('Se requiere:'),
      f('G(x)\\geq3000'),
      p('Entonces:'),
      f('x^2-40x+300\\leq0'),
      f('(x-10)(x-30)\\leq0'),
      p('Por lo tanto:'),
      f('10\\leq x\\leq30'),
    ],
  ),
  q(
    28,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('En una encuesta de 120 personas:'),
      f('A\\cap B=42'),
      f('B\\cap A^c=28'),
      f('A\\cap B^c=18'),
      p('ninguna de las dos: 32.'),
      p('Si se selecciona una persona entre quienes cumplen B, ¿cuál es la probabilidad de que también cumpla A?'),
    ],
    [fOpt('\\frac{3}{5}', true), fOpt('\\frac{7}{20}', false), fOpt('\\frac{7}{12}', false), fOpt('\\frac{21}{50}', false)],
    [
      p('Entre quienes cumplen B:'),
      f('42+28=70'),
      p('Entonces:'),
      f('P(A\\mid B)=\\frac{42}{70}=\\frac{3}{5}'),
    ],
  ),
  q(
    29,
    'GEOMETRIA',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('La recta:'),
      f('x+y=6'),
      p('intersecta:'),
      f('x^2+y^2=20'),
      p('en A y B.'),
      p('¿Cuál es AB?'),
    ],
    [fOpt('\\sqrt{2}', false), fOpt('4', false), fOpt('2\\sqrt{2}', true), fOpt('4\\sqrt{2}', false)],
    [
      f('y=6-x'),
      p('Entonces:'),
      f('x^2+(6-x)^2=20'),
      f('x^2-6x+8=0'),
      p('Los puntos son:'),
      f('(2,4)'),
      p('y:'),
      f('(4,2)'),
      p('Por lo tanto:'),
      f('AB=\\sqrt{(2)^2+(-2)^2}=2\\sqrt{2}'),
    ],
  ),
  q(
    30,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'REPRESENTAR',
    [
      p('El punto:'),
      f('(1,-2)'),
      p('pertenece a f.'),
      p('Se define:'),
      f('g(x)=-2f(x-3)+1'),
      p('¿Qué punto pertenece necesariamente a g?'),
    ],
    [fOpt('(-2,5)', false), fOpt('(4,-3)', false), fOpt('(1,5)', false), fOpt('(4,5)', true)],
    [
      p('Para usar f(1):'),
      f('x-3=1'),
      f('x=4'),
      p('Entonces:'),
      f('g(4)=-2(-2)+1=5'),
      p('Por lo tanto:'),
      f('(4,5)'),
    ],
  ),
  q(
    31,
    'NUMEROS',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se desea determinar un entero positivo:'),
      f('n<20'),
      p('(1) n es múltiplo de 6.'),
      p('(2) n tiene exactamente 4 divisores positivos.'),
    ],
    [
      tOpt('La información (1) por sí sola es suficiente.', false),
      tOpt('La información (2) por sí sola es suficiente.', false),
      tOpt('Cada una por separado es suficiente.', false),
      tOpt('Se necesitan conjuntamente.', true),
    ],
    [
      p('Con (1):'),
      f('6,12,18'),
      p('Con (2):'),
      f('6,8,10,14,15'),
      p('La única intersección es:'),
      f('n=6'),
    ],
  ),
  q(
    32,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Se elige al azar un entero del 1 al 10.'),
      p('¿Cuál es la probabilidad de que sea múltiplo de 2 o de 5?'),
    ],
    [fOpt('\\frac{1}{2}', false), fOpt('\\frac{3}{5}', true), fOpt('\\frac{7}{10}', false), fOpt('\\frac{4}{5}', false)],
    [
      p('Favorables:'),
      f('2,4,5,6,8,10'),
      p('Entonces:'),
      f('P=\\frac{6}{10}=\\frac{3}{5}'),
    ],
  ),
  q(
    33,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Una recta pasa por:'),
      f('P=(2,5)'),
      p('y es perpendicular a:'),
      f('3x-2y=7'),
      p('¿Cuál puede ser su ecuación?'),
    ],
    [fOpt('2x+3y=19', true), fOpt('3x-2y=-4', false), fOpt('2x-3y=-11', false), fOpt('3x+2y=16', false)],
    [
      p('La pendiente original es:'),
      f('\\frac{3}{2}'),
      p('La perpendicular:'),
      f('-\\frac{2}{3}'),
      p('Entonces:'),
      f('y-5=-\\frac{2}{3}(x-2)'),
      p('equivale a:'),
      f('2x+3y=19'),
    ],
  ),
  q(
    34,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Una función está definida por:'),
      f('f(x)=\\frac{ax+b}{x+1}'),
      p('Se sabe:'),
      f('f(0)=2'),
      f('f(1)=3'),
      p('¿Cuál es:'),
      f('f^{-1}(5)'),
      p('?'),
    ],
    [fOpt('-5', false), fOpt('-2', false), fOpt('-3', true), fOpt('3', false)],
    [
      p('De f(0)=2:'),
      f('b=2'),
      p('De f(1)=3:'),
      f('\\frac{a+2}{2}=3'),
      f('a=4'),
      p('Entonces:'),
      f('\\frac{4x+2}{x+1}=5'),
      f('x=-3'),
    ],
  ),
  q(
    35,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'MODELAR',
    [
      p('Una caja contiene:'),
      p('5 verdes;'),
      p('3 amarillas;'),
      p('2 rojas.'),
      p('Se extraen 2 simultáneamente.'),
      p('¿Cuál es la probabilidad de que al menos una sea roja?'),
    ],
    [fOpt('\\frac{2}{9}', false), fOpt('\\frac{17}{45}', true), fOpt('\\frac{28}{45}', false), fOpt('\\frac{4}{5}', false)],
    [
      p('Total:'),
      f('\\binom{10}{2}=45'),
      p('Sin rojas:'),
      f('\\binom{8}{2}=28'),
      p('Entonces:'),
      f('1-\\frac{28}{45}=\\frac{17}{45}'),
    ],
  ),
  q(
    36,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Se distribuyen:'),
      f('6\\cdot10^8'),
      p('células entre:'),
      f('2,4\\cdot10^3'),
      p('muestras.'),
      p('Luego se elimina el 20% de cada muestra.'),
      p('¿Cuántas quedan por muestra?'),
    ],
    [
      fOpt('1,5\\cdot10^5', false),
      fOpt('1,8\\cdot10^5', false),
      fOpt('2\\cdot10^5', true),
      fOpt('2,5\\cdot10^5', false),
    ],
    [
      f('\\frac{6\\cdot10^8}{2,4\\cdot10^3}=2,5\\cdot10^5'),
      p('Luego:'),
      f('2,5\\cdot10^5(0,8)=2\\cdot10^5'),
    ],
  ),
  q(
    37,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('Una empresa vende x unidades de un producto.'),
      p('El ingreso total, en miles de pesos, está modelado por:'),
      f('I(x)=60x-x^2'),
      p('mientras que el costo total es:'),
      f('C(x)=12x+320'),
      p('¿Para qué valores de x la ganancia es de al menos 192 miles de pesos?'),
    ],
    [
      fOpt('8\\leq x\\leq32', false),
      fOpt('16\\leq x\\leq32', true),
      fOpt('x\\geq32', false),
      fOpt('16\\leq x\\leq48', false),
    ],
    [
      p('La ganancia es:'),
      f('G(x)=I(x)-C(x)'),
      f('G(x)=-x^2+48x-320'),
      p('Se requiere:'),
      f('G(x)\\geq192'),
      p('Entonces:'),
      f('-x^2+48x-320\\geq192'),
      f('-x^2+48x-512\\geq0'),
      p('Multiplicando por -1:'),
      f('x^2-48x+512\\leq0'),
      p('Factorizando:'),
      f('(x-16)(x-32)\\leq0'),
      p('Por lo tanto:'),
      f('16\\leq x\\leq32'),
    ],
  ),
  q(
    38,
    'GEOMETRIA',
    'MEDIA',
    'REPRESENTAR',
    [
      p('El punto:'),
      f('P=(3,-1)'),
      p('se rota 90° antihorario respecto del origen y luego se traslada por:'),
      f('(2,4)'),
      p('¿Cuál es el punto final?'),
    ],
    [fOpt('(1,7)', false), fOpt('(-3,5)', false), fOpt('(5,3)', false), fOpt('(3,7)', true)],
    [
      f('(3,-1)\\rightarrow(1,3)'),
      p('Luego:'),
      f('(1,3)+(2,4)=(3,7)'),
    ],
  ),
  q(
    39,
    'PROBABILIDAD_ESTADISTICA',
    'FACIL',
    'RESOLVER_PROBLEMAS',
    [
      p('Se lanza una moneda equilibrada y un dado equilibrado.'),
      p('¿Cuál es la probabilidad de obtener cara y número par?'),
    ],
    [fOpt('\\frac{1}{4}', true), fOpt('\\frac{1}{3}', false), fOpt('\\frac{1}{2}', false), fOpt('\\frac{3}{4}', false)],
    [f('\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}')],
  ),
  q(
    40,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se desea determinar un real positivo x.'),
      p('(1)'),
      f('x+\\frac{1}{x}=\\frac{5}{2}'),
      p('(2)'),
      f('x>1'),
    ],
    [
      tOpt('La información (1) por sí sola es suficiente.', false),
      tOpt('La información (2) por sí sola es suficiente.', false),
      tOpt('Cada una por separado es suficiente.', false),
      tOpt('Se necesitan conjuntamente.', true),
    ],
    [
      p('De (1):'),
      f('2x^2-5x+2=0'),
      f('(2x-1)(x-2)=0'),
      p('Entonces:'),
      f('x=\\frac{1}{2}'),
      p('o:'),
      f('x=2'),
      p('(1) sola no basta.'),
      p('(2) sola tampoco.'),
      p('Juntas determinan:'),
      f('x=2'),
    ],
  ),
  q(
    41,
    'GEOMETRIA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una circunferencia tiene radio 10 cm.'),
      p('Una cuerda está a 6 cm del centro.'),
      p('¿Cuál es su longitud?'),
    ],
    [tOpt('8 cm', false), tOpt('12 cm', false), tOpt('16 cm', true), tOpt('20 cm', false)],
    [
      p('La mitad de la cuerda satisface:'),
      f('a^2+6^2=10^2'),
      f('a=8'),
      p('Entonces la cuerda completa mide 16 cm.'),
    ],
  ),
  q(
    42,
    'NUMEROS',
    'FACIL',
    'REPRESENTAR',
    [
      p('¿Cuál es:'),
      f('81^{-\\frac{1}{2}}'),
      p('?'),
    ],
    [fOpt('-\\frac{1}{9}', false), fOpt('\\frac{1}{9}', true), fOpt('9', false), fOpt('-9', false)],
    [f('81^{-\\frac{1}{2}}=\\frac{1}{\\sqrt{81}}=\\frac{1}{9}')],
  ),
  q(
    43,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'MODELAR',
    [
      p('Una semilla germina con probabilidad:'),
      f('\\frac{1}{4}'),
      p('Si se plantan 4 semillas independientes, ¿cuál es la probabilidad de que germinen exactamente 2?'),
    ],
    [
      fOpt('\\frac{27}{128}', true),
      fOpt('\\frac{9}{64}', false),
      fOpt('\\frac{27}{64}', false),
      fOpt('\\frac{81}{256}', false),
    ],
    [f('\\binom{4}{2}\\left(\\frac{1}{4}\\right)^2\\left(\\frac{3}{4}\\right)^2=6\\cdot\\frac{1}{16}\\cdot\\frac{9}{16}=\\frac{27}{128}')],
  ),
  q(
    44,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'RESOLVER_PROBLEMAS',
    [
      p('La ecuación:'),
      f('|2x-3|=x+5'),
      p('tiene dos soluciones.'),
      p('¿Cuál es su suma?'),
    ],
    [fOpt('\\frac{16}{3}', false), fOpt('\\frac{20}{3}', false), fOpt('\\frac{22}{3}', true), fOpt('\\frac{26}{3}', false)],
    [
      p('Primer caso:'),
      f('2x-3=x+5'),
      f('x=8'),
      p('Segundo:'),
      f('3-2x=x+5'),
      f('x=-\\frac{2}{3}'),
      p('Entonces:'),
      f('8-\\frac{2}{3}=\\frac{22}{3}'),
    ],
  ),
  q(
    45,
    'GEOMETRIA',
    'MEDIA',
    'ARGUMENTAR',
    [
      p('En el plano cartesiano se consideran los puntos:'),
      f('A=(0,0)'),
      f('B=(4,1)'),
      f('C=(5,5)'),
      f('D=(1,4)'),
      p('¿Qué tipo de cuadrilátero es ABCD?'),
    ],
    [
      tOpt('Rectángulo que no es cuadrado.', false),
      tOpt('Rombo que no es cuadrado.', true),
      tOpt('Cuadrado.', false),
      tOpt('Paralelogramo que no es rectángulo ni rombo.', false),
    ],
    [
      p('Los cuatro lados tienen longitud:'),
      f('\\sqrt{17}'),
      p('Además, los lados opuestos son paralelos.'),
      p('Por lo tanto, es un rombo.'),
      p('Pero:'),
      f('\\overrightarrow{AB}\\cdot\\overrightarrow{BC}=(4)(1)+(1)(4)=8\\neq0'),
      p('No existen ángulos rectos.'),
      p('Por tanto, es un rombo que no es cuadrado.'),
    ],
  ),
  q(
    46,
    'NUMEROS',
    'FACIL',
    'REPRESENTAR',
    [
      p('¿Cuál es:'),
      f('32^{\\frac{2}{5}}'),
      p('?'),
    ],
    [fOpt('2', false), fOpt('4', true), fOpt('8', false), fOpt('16', false)],
    [
      f('32=2^5'),
      p('Entonces:'),
      f('32^{\\frac{2}{5}}=(2^5)^{\\frac{2}{5}}=2^2=4'),
    ],
  ),
  q(
    47,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('¿Cuál es la solución de:'),
      f('2^{x+1}=8^{x-1}'),
      p('?'),
    ],
    [fOpt('x=\\frac{1}{2}', false), fOpt('x=1', false), fOpt('x=2', true), fOpt('x=3', false)],
    [
      f('8=2^3'),
      p('Entonces:'),
      f('2^{x+1}=2^{3x-3}'),
      f('x+1=3x-3'),
      f('x=2'),
    ],
  ),
  q(
    48,
    'GEOMETRIA',
    'MEDIA',
    'MODELAR',
    [
      p('Una ruta une:'),
      f('A=(-2,1)'),
      p('con:'),
      f('B=(7,7)'),
      p('P está a dos tercios del recorrido desde A hacia B.'),
      p('¿Cuáles son sus coordenadas?'),
    ],
    [fOpt('(4,5)', true), fOpt('(1,3)', false), fOpt('(5,4)', false), fOpt('(3,5)', false)],
    [
      f('\\overrightarrow{AB}=(9,6)'),
      f('\\frac{2}{3}(9,6)=(6,4)'),
      p('Entonces:'),
      f('P=(-2,1)+(6,4)=(4,5)'),
    ],
  ),
  q(
    49,
    'PROBABILIDAD_ESTADISTICA',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Se sabe:'),
      f('P(A)=0,6'),
      p('Se desea determinar:'),
      f('P(A\\cap B)'),
      p('(1)'),
      f('P(B)=0,5'),
      p('(2)'),
      f('P(A\\cup B)=0,8'),
    ],
    [
      tOpt('La información (1) por sí sola es suficiente.', false),
      tOpt('La información (2) por sí sola es suficiente.', false),
      tOpt('Cada una por separado es suficiente.', false),
      tOpt('Se necesitan conjuntamente.', true),
    ],
    [
      f('P(A\\cup B)=P(A)+P(B)-P(A\\cap B)'),
      p('Cada dato por separado deja un término desconocido.'),
      p('Con ambos:'),
      f('0,8=0,6+0,5-P(A\\cap B)'),
      p('Por lo tanto:'),
      f('P(A\\cap B)=0,3'),
    ],
  ),
  q(
    50,
    'NUMEROS',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una inversión inicial de $500.000 aumenta 10% durante dos años consecutivos y luego disminuye 20%.'),
      p('¿Cuál es su valor final?'),
    ],
    [tOpt('$440.000', false), tOpt('$480.000', false), tOpt('$484.000', true), tOpt('$500.000', false)],
    [
      f('500.000(1,10)^2=605.000'),
      p('Luego:'),
      f('605.000(0,80)=484.000'),
    ],
  ),
  q(
    51,
    'ALGEBRA_FUNCIONES',
    'DIFICIL',
    'MODELAR',
    [
      p('La altura, en metros, de un objeto durante cierto intervalo de movimiento está modelada por:'),
      f('h(t)=-5t^2+30t+10'),
      p('¿Durante qué intervalo la altura es de al menos 40 metros?'),
    ],
    [
      fOpt('0\\leq t\\leq3-\\sqrt{3}', false),
      fOpt('3-\\sqrt{3}\\leq t\\leq3+\\sqrt{3}', true),
      fOpt('t\\geq3+\\sqrt{3}', false),
      fOpt('0\\leq t\\leq3+\\sqrt{3}', false),
    ],
    [
      f('-5t^2+30t+10\\geq40'),
      f('t^2-6t+6\\leq0'),
      p('Las raíces son:'),
      f('3\\pm\\sqrt{3}'),
      p('Por lo tanto:'),
      f('3-\\sqrt{3}\\leq t\\leq3+\\sqrt{3}'),
    ],
  ),
  q(
    52,
    'GEOMETRIA',
    'FACIL',
    'REPRESENTAR',
    [
      p('El punto:'),
      f('P=(-2,5)'),
      p('se refleja respecto de:'),
      f('y=x'),
      p('¿Cuál es su imagen?'),
    ],
    [fOpt('(5,-2)', true), fOpt('(2,-5)', false), fOpt('(-5,2)', false), fOpt('(5,2)', false)],
    [
      p('La reflexión respecto de y=x intercambia las coordenadas:'),
      f('(x,y)\\rightarrow(y,x)'),
      p('Por lo tanto:'),
      f('(-2,5)\\rightarrow(5,-2)'),
    ],
  ),
  q(
    53,
    'PROBABILIDAD_ESTADISTICA',
    'MEDIA',
    'RESOLVER_PROBLEMAS',
    [
      p('Una urna contiene 5 fichas rojas y 4 azules.'),
      p('Se extraen simultáneamente 3.'),
      p('¿Cuál es la probabilidad de obtener exactamente una roja?'),
    ],
    [fOpt('\\frac{5}{21}', false), fOpt('\\frac{10}{21}', false), fOpt('\\frac{5}{14}', true), fOpt('\\frac{9}{14}', false)],
    [
      p('Total:'),
      f('\\binom{9}{3}=84'),
      p('Favorables:'),
      f('\\binom{5}{1}\\binom{4}{2}=5\\cdot6=30'),
      p('Entonces:'),
      f('P=\\frac{30}{84}=\\frac{5}{14}'),
    ],
  ),
  q(
    54,
    'NUMEROS',
    'DIFICIL',
    'ARGUMENTAR',
    [
      p('Sea n un entero positivo.'),
      p('Se sabe que:'),
      f('72\\mid n^2'),
      p('¿Cuál afirmación es necesariamente verdadera?'),
    ],
    [
      tOpt('n puede ser múltiplo de 6 sin ser múltiplo de 12.', false),
      tOpt('n es múltiplo de 12.', true),
      tOpt('n necesariamente es múltiplo de 18.', false),
      tOpt('n necesariamente es múltiplo de 24.', false),
    ],
    [
      f('72=2^3\\cdot3^2'),
      p('Como los exponentes de los factores primos de n² son pares, para contener 2³ debe contener al menos 2⁴.'),
      p('Entonces n contiene al menos:'),
      f('2^2'),
      p('y también:'),
      f('3'),
      p('Por tanto:'),
      f('12\\mid n'),
      p('Por ejemplo:'),
      f('n=12'),
      p('satisface la condición y demuestra que 18 y 24 no son obligatorios.'),
    ],
  ),
  q(
    55,
    'ALGEBRA_FUNCIONES',
    'MEDIA',
    'MODELAR',
    [
      p('Una sustancia disminuye a la mitad cada 6 horas.'),
      p('Inicialmente hay:'),
      f('320\\text{ mg}'),
      p('y:'),
      f('M(t)=320\\left(\\frac{1}{2}\\right)^{t/6}'),
      p('¿Cuántas horas deben transcurrir para que queden:'),
      f('40\\text{ mg}'),
      p('?'),
    ],
    [fOpt('6', false), fOpt('12', false), fOpt('15', false), fOpt('18', true)],
    [
      f('320\\left(\\frac{1}{2}\\right)^{t/6}=40'),
      f('\\left(\\frac{1}{2}\\right)^{t/6}=\\frac{1}{8}'),
      p('Como:'),
      f('\\frac{1}{8}=\\left(\\frac{1}{2}\\right)^3'),
      p('entonces:'),
      f('\\frac{t}{6}=3'),
      f('t=18'),
    ],
  ),
];

const ensayoPaesM2: ExamSourceModule = {
  examKey: 'ENSAYO.M2',
  title: 'Ensayo PAES M2',
  subjectKey: 'matematica-m2',
  durationMinutes: 140,
  questions,
};

export default ensayoPaesM2;
